### ISSUE TITLE
Can't delete data in extra_data fields in Building Detail

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1027]
It seems that in the old data model (V1.5) does not allow deleting existing text in extra_data fields in Building Detail. However, it IS possible to delete data in structured fields in the building snapshot table.

**Comment by RDmitchell** [comment]
Here is a link to a sample data file that has both real fields and extra_data fields. 
https://drive.google.com/open?id=0B3fTKpZ9Dx7Lano3OXp3Z2syX2M

Steps to replicate:
* Import the file into SEED, mapping the Extra Data fields so that they stay in extra_data
![image](https://cloud.githubusercontent.com/assets/6314950/17119851/7609c5e4-527d-11e6-8bd4-c3c019060302.png)

* Delete "triangle town" which is an extra data field using "Edit" in the Detailed view and save it. It looks like it is deleted when you are still in Detailed view
![image](https://cloud.githubusercontent.com/assets/6314950/17119971/3483397e-527e-11e6-9f1e-8ee4db2874b6.png)

* Go back to the Building List view, and you will see that the data is still displaying in that field. 
![image](https://cloud.githubusercontent.com/assets/6314950/17120339/641c1866-5280-11e6-8c28-7e9cc14e2630.png)

* Do the exact same thing with the field **City**, which is NOT in extra_data, but is in the structured field called "city", and the program will actually delete the value. 

So it appears that this is not working in the extra_data fields.

**Comment by RDmitchell** [comment]
@tallus -- can you take a look at this and determine the level of effort to fix it? Then we can decide whether to fix it now or just wait for the September release. thx

**Comment by tallus** [comment]
updating extra data  uses merge_extra_data  from [seed/mappings/mapper.py](https://github.com/SEED-platform/seed/blob/develop/seed/mappings/mapper.py#L60)
This *merges* extra data so it won't overwrite keys with blank values:
changing 
   k: default_extra_data.get(k) or non_default_extra_data.get(k)
to
 k: default_extra_data[k] if k in default_extra_data else  non_default_  extra_data.get(k)
on line 85 "fixes" the problem.

This won't take that long since I've done the hard work already.
 
Note however there is a unit test to ensure it doesn't do this (i.e. override with blank data).

So we also need ensure this won't have impact elsewhere (it shouldn't as the function is only called 
in one place) and that this is really what we want and won't have unintentional side-effects*, given that the unit tests say it shouldn't do this. This might take more time.

*like deleting data unintentionally.

**Comment by RDmitchell** [comment]
Paul -- we definitely don't want the program to overwrite existing data in the canonical building / building snapshot with blank data on import. 

However, this is a different situation, ie, the user explicitly wants to delete existing data and not put new data in there. So if the same method is used in both cases, then we can't break the existing functionality that on import the program doesn't overwrite existing data with blank data. 

so is this the case, that if we allow it in editing it breaks the existing functionality for data import?

**Comment by tallus** [comment]
I did some more tracing on the code patch and this also gets called in merge_building which gets called by save_snapshot_match which gets called by the save_match view and the match_building tasks which is where we wouldn't want it to overwrite data.

That said I think adding a flag to the function to specifically allow overwriting should be safe, as we can isolate it to the call to the function in update_building in seed/models/models.py which is where it gets called during editing.

That shouldn't be a big task so I can prepare it for adding to 1.5

**Comment by RDmitchell** [comment]
Is update_building only used when the user is hand editing a value in the building detail view? We want to make sure existing data doesn't get overwritten by blank data in any of the "automated" ways that building records get updated.

**Comment by tallus** [comment]
update_building in models.py only gets called by the update_building view: this states in it's doc string its for manually updating a building.

This gets called by the building_service angular service and the only place I see a reference to this is in the building_detail angular controller (which is what does the editing).

The view does have an api_endpoint decorator so it might be getting accessed directly. I would have thought that the behaviour we want in manually editing would be the same as what we want when manually editing. 

We can also add something into the endpoint which would get passed through to the update_building function in models.py which would set the flag if present, if we don't think this is the case or we want to be extra cautious.

**Comment by tallus** [comment]
#1043 is a hot-fix against release 1.5.0, as such it tries not to introduce any extraneous or breaking changes. As this leaves other, existing issues with the code touched,  in place.

These are:
seed.models.update_building takes unlimited arguments and positional arguments (*args, **kwargs) but never references them, Its not clear at all what it might do with them in and it is never supplied with any in any call. This should just be dropped altogether.

seed.mapping.mapper.merge_extra_data takes three arguments two compulsory positional arguments (b1 & b2) and optional one(default).

It is always called in the form merge_extra_data(new, old, default=new). Setting default to new means values in new take precedence. This is unnecessary since merge_extra_data(new, old) does the same thing. Moreover the ambiguity it clarifies exists only because the default parameter itself exists, without it  the first snapshot supplied would always take place over the second and there would be no ambiguity. (If you want old to take precedence you would only have to reverse the order as neither snapshot is altered by function). 

Worse still it does this task very ineffectively. Default takes a building snapshot  thus 
 merge_extra_data(new, old, default=other) is perfectly legal. This would result in other and new being merged with old being ignored.

Not only does this mean that an optional parameter takes precedence over a compulsory one (as well as unnecessary duplication of data) with the compulsory one being dropped silently, it goes against the typical Python convention (as in dict.get) where default would typically be expected to provide values that are in nether old nor new. This might be a reasonable use case for default, though using a building snapshot here (vs a dict of default values) does not make much sense and there is nowhere where a user might set these default values (and providing one would not be straight forward), nor it is necessarily clear why this might be wanted.

Default should also be dropped and the code updated (this is a breaking change since it is called everywhere with the default argument supplied).

Any changes against develop would also need to account for the new api and data structure.

**Comment by RDmitchell** [comment]
This is no longer an issue, closing
