### ISSUE TITLE
Investigate Sentry error

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1031]
Paul -- can you investigate this Sentry error? Miles is going to invite you to our Sentry account tonight, which should help you debug it. 

https://app.getsentry.com/lawrence-berkeley-national-lab/seed-django-production/issues/145481270/

I will forward you the email I got for this error, but really you will need to log into Sentry to figure it out.

**Comment by RDmitchell** [comment]
This error was generated through the UI, not through an API call.

**Comment by tallus** [comment]
It looks like it is generated during  the data mapping stage once Step 1 has been completed (when the user can 'Save Mappings'). On this page clicking on any of the table headings sends a request to search_building_snapshots with order_by set to that column name.

However since this gets translated directly into a DB call it only works for columns that correspond to fields in the database, not on extra data as orderby_by with JSONFields is not currently supported by Django:

https://stackoverflow.com/questions/36641759/django-1-9-jsonfield-order-by

It can be down with Raw SQL (though that's not ideal), I will take a look as to what can be done with that.

**Comment by tallus** [comment]
Pull request is in
https://github.com/SEED-platform/seed/pull/1034

**Comment by tallus** [comment]
Pull request against release 1.5.0: https://github.com/SEED-platform/seed/issues/1041

**Comment by RDmitchell** [comment]
closing this issue as V 1.5 errors are no longer relevant
