### ISSUE TITLE
Failed to load resource: api/v2/projects/count/?organization_id

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1096]
Can someone fix this error, please?

https://seedv2.lbl.gov/api/v2/projects/count/?organization_id=49 
Failed to load resource: the server responded with a status of 404 (Not Found)

![image](https://cloud.githubusercontent.com/assets/6314950/19319339/610ee6c0-9061-11e6-9f39-d388602e8e43.png)

**Comment by Myoldmopar** [comment]
I'll work on it if no one else is ( @axelstudios @nllong ).  Today I'm packed with meetings, but I should be able to get it done today or tomorrow.

**Comment by RDmitchell** [comment]
There is not a super rush on this. It would just be nice to not see the error -- every time I see it I have to remember that it's not something I need to worry about. So when you have time, it would be great to fix it. Thanks.

**Comment by Myoldmopar** [comment]
OK, so the problem is that the url path was changed, but it seems the front end was not fully updated for this.  The url should be `/projects-count` per [these lines](https://github.com/SEED-platform/seed/blob/26759267fa3b25529a0a3f445e12bafd4e0f4aff/api/urls.py#L29-L33).  The site is trying to load `/projects/count`, which tries to lookup a project with the name/slug of "count" and fails, so it throws a 404.  If you actually click on the link in the inspector, it _should_ bring up a small json blob saying it can't find it.  But if you change the slash to a dash, it should load a successful response.  I'll find where in the code that is being called and change it.

**Comment by Myoldmopar** [comment]
Fixing with #1115

**Comment by RDmitchell** [comment]
fixed.
