### ISSUE TITLE
Delete Cycle

### ISSUE THREAD

**Issue by ghost** [SEED-platform/seed#1113]
Hi all,

I have recently started to write a new standard API test that would work with the new data model. The test is supposed to automatically go through all the API requests that a typical user would use and finish by resetting the entire account to a clean slate. This means deleting all buildings records, datasets, projects, labels and cycles that have been created during the test.

The issue I have is that I can't find a way to delete the cycle -if there is any- in the user interface. Whether the features doesn't exist or it exists but there is no button to call it, I believe that it is an important features to have for any users that would want to undo a cycle creation.

Thank you,
Baptiste

**Comment by macintoshpie** [comment]
@adrian-lara @RDmitchell Could you comment with your thoughts and opinions on the design options 1 or 2 below? Adrian one additional question for you: users cannot link properties/taxlots (link in the sense of match_merge_link), or create TaxLotProperties across cycles right?

---

## Research Notes
There is already an endpoint for deleting cycles, and has been around since 42727700ebd92ddcff2d6bd4f0f746b6caa75e64 (about 4 years ago, 2016). This endpoint is not accessible from the frontend.

Cycles are used by the PropertyView, TaxLotView, TaxLotProperty, and AnalysisPropertyView models. The former two use a ForeignKey reference with `on_delete=models.PROTECT`, while the latter two cascade.
This means that if you try to delete a cycle with linked properties or taxlots using the current API, you get an error:
```json
{
  "status": "error",
  "message": "Cannot delete protected objects while related objects still exist"
}
```

The potential consequences for deleting a cycle and all of its *Views are pretty low. TLDR; we've been batch deleting *Views for years, which are really the only things that point to Cycles, so it's safe to delete Cycles.
More specifically, since 42727700ebd92ddcff2d6bd4f0f746b6caa75e64 (the same commit as above) the `state` for *Views has been `on_delete=CASCADE`. And since ae934b80d5934dc4a6cf8b0449f1c289ee9f1228 we've allowed batch deletion of States as an endpoint (not sure when this was added to frontend, but pretty sure it was from the same commit). This means we've been batch deleting *Views for a long time (the main pointers to Cycles).

We have two ways to implement the deletion on the backend. Also see the Design Options section below for frontend choices (maybe do that first...)
1. update the *View models to delete on cascade (convenient but potentially dangerous from the perspective of an API user, ie a non-frontend user)
2. implement logic in endpoint to delete connected *Views before deleting the Cycle (convenient, just as dangerous to API user)
3. require that all *Views are deleted before you can delete a cycle (less convenient, not dangerous)

## Design
We will add a "trash" icon next to the "edit" button for every cycle shown from the organization cycles page.
<img width="1386" alt="Screen Shot 2021-02-01 at 1 47 17 PM" src="https://user-images.githubusercontent.com/18518728/106519521-a4f10e80-6498-11eb-9f93-b93a0ebaaedf.png">

### Design options
#### Option 1
This option assumes we want to give users the option to automatically delete properties/taxlots associated with a cycle.

When a user clicks on the trash icon, it opens a modal.
It will have the title "Confirm Deletion". The body will report:
```
Are you sure you want to delete the cycle <cycle name here>? This action cannot be undone.
If deleted, the cycle data for <number of property views in cycle> Properties and <number of tax lot views in cycle> Tax Lots will be removed permanently.

If you haven't already, please review these inventory before continuing
Properties: <insert link to inventory list view showing properties filtered by cycle>
Tax Lots: <insert link to inventory list view showing taxlots filtered by cycle>
```
Clicking on the link to view properties/taxlots for the cycle will open in a new tab (if possible).

There will be two buttons: "Cancel" and "Confirm Deletion".

If user clicks on cancel button or away from modal the modal disappears.
If the user clicks confirm deletion, the cycle, as well as any linked property/tax lot data, is immediately deleted, and a success message or error message is shown when done.

For this option, we might want to even have a textbox that requires users to type in the cycle name before the "Confirm Deletion" button is enabled like GitHub does for repositories:
![image](https://user-images.githubusercontent.com/18518728/106520613-488eee80-649a-11eb-8464-e244e7148f13.png)



#### Option 2
This option requires a cycle is "empty" (ie no properties/taxlots) before it can be deleted. Users cannot batch delete properties/taxlots within a cycle from this modal.

When a user clicks on the trash icon for a cycle, it opens up a modal like in Option 1. But if there are any linked taxlots or properties, it reports this and tells users to go delete them themselves before deleting the cycle:
```
Unable to delete cycle <cycle name here>. You must delete all existing properties and taxlots in <cycle name here> before you can delete this cycle.
Properties: <insert link to inventory list view showing properties filtered by cycle>
Tax Lots: <insert link to inventory list view showing properties/taxlots filtered by cycle>
```
There is only a dismiss button. Ie users cannot batch delete cycles and taxlots from this modal.

If there are no taxlots/properties linked to the cycle, it has the following message:
```
Are you sure you want to delete cycle <cycle name here>?
```
With a confirmation or cancel button.


### Design thoughts
I think option 2 here is the simplest. Users will use existing APIs/UI interfaces for deleting properties and taxlots, so they're familiar with it and it's less for us to test. Users can already batch delete inventory from these views. Option 2 is also "safer", reducing the chance (hopefully) for users doing something Bad.
Option 1 is convenient , but the costs are:
1. updating our *View models to cascade delete, or manually deleting these linked inventories
2. increasing number of entrypoints to deleting *Views, making things a bit more complex.

**Comment by RDmitchell** [comment]
I would say go with Option 2.

Generally I think this is for the case where you made a Cycle and for whatever reason you don't need it anymore, ever really used it, etc. So empty is good, and enforcing empty is fine.

**Comment by adrian-lara** [comment]
No strong opinion between the two options from me.

> users cannot link properties/taxlots (link in the sense of match_merge_link), or create TaxLotProperties across cycles right?

I'm not 100% certain on how to read this question, but I'll mention the following. Of course, let me know if I can give more info.

Users can manually `pair` properties with tax lots (which I believe happens using TaxLotProperties). `Pair`ing doesn't happen across Cycles. 

Properties don't `link` with tax lots at all. Users can't manually force a `link` to happen - they can't choose to multiple records across and directly `link` them. User can trigger the match_merge_link logic for a record - which will find matches and merge + link automatically.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9475793de
Org: LBNL Test 200

This works really nicely !! Very user friendly and all the steps make sense to me as a user

Here is how it works
* I try to delete a cycle that has records attached to it and get these messages
![image](https://user-images.githubusercontent.com/6314950/109046257-63174a80-7689-11eb-82a8-58669ba606ab.png)
![image](https://user-images.githubusercontent.com/6314950/109046275-690d2b80-7689-11eb-8e5b-99ddf8ec5ee7.png)
* I click on the "View Properties in this cycle" button, which takes me to the Inventory / Property view, where I delete both the properties and Tax Lots from this cycle
* I then come back to Cycles, and can now delete the cycle
![image](https://user-images.githubusercontent.com/6314950/109046396-893cea80-7689-11eb-9874-258854a1f180.png)
![image](https://user-images.githubusercontent.com/6314950/109046412-8fcb6200-7689-11eb-8ba8-69218c3cbc4c.png)
