### ISSUE TITLE
Return display names from the backend

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1191]
The conversion of database fields to user displays exists in several places in the code base. Need to standardize on one solution and implement in the backend.

This will most likely result in adding a display name field to the columns table in the database.

**Comment by RDmitchell** [comment]
Yes, it seems like adding a display name to the columns table makes sense. 

How does this interact with what the user sees in the Mapping pulldown list? Can the display name and the pulldown list name be the same? I guess this gives the option of not having them same when needed, but the default would be that they would be the same.

**Comment by nllong** [comment]
yeah that would be the best approach... users would map to display names, not database field names.

**Comment by RDmitchell** [comment]
Yup -- mapping and display names are one and the same. That should be what we do ... but what does that mean for 2.0 vs 2.1? We don't want to have to do remapping of data (if we can help it) after 2.0 (although maybe it's unavoidable given our time constraints).

**Comment by RDmitchell** [comment]
@nllong -- the one field that is really weird in mapping is when you have a Tax Lot ID in a property file, and you want to set it to be a matching field in the Tax Lot table (ie, matching it to Jurisdiction Tax Lot ID), you map the field to "Lot Number", and I think apply it to the Property table (would have to I think). 

Seems like this field name (at least the display name / mapping name?) should be "Jurisdiction Tax Lot ID", but the program knows it is in the Property table and thus it will match on it. 

We don't have to do this now, I guess, because it would probably mean changing the matching code, and we don't have time to do that. And maybe it doesn't matter from the BE, because the field name would continue to be "Lot number", only the FE mapping name would change to "Jurisdiction Tax Lot ID". 

Anyway, something to ponder for the future I guess.

**Comment by nllong** [comment]
#1230

**Comment by RDmitchell** [comment]
Comment from #1151 which I have closed
*****
SHA: 3e9c017
instance: seeddemostaging
browser: chrome, incognito
file: covered-buildings-sample-small.csv, from #1126
https://drive.google.com/open?id=0B3fTKpZ9Dx7LMHgwYTloc0lGOTQ

Looking at the pm-mapping.json file, seems like the display names are not getting picked up for some reason.

![image](https://cloud.githubusercontent.com/assets/6314950/21337120/56995862-c61f-11e6-98d3-b09782df93fc.png)

![image](https://cloud.githubusercontent.com/assets/6314950/21337141/8a261d14-c61f-11e6-946d-2e9ce4e60b2b.png)

**Comment by RDmitchell** [comment]
It also picked up the capitalization of Site EUI when I mapped it as all upper case EUI.
![image](https://user-images.githubusercontent.com/6314950/40567238-671f2054-6029-11e8-83b5-aeb051e1b395.png)

**Comment by RDmitchell** [comment]
testing done on

Instance: dev1
SHA: 90e4a7d
Org: LBNL 20
Cycle: Test 1588

Closing
