### ISSUE TITLE
Admin Function for Deleting Parent and Sub-Orgs

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#13]
Need an admin function (for Superusers) to delete Parent and Sub orgs. And possibly that same functionality for the owner of a Parent Org to delete Sub-Orgs. Right now it is not possible to delete either, even as a superuser. This needs some thought, because you don't want orphaned building records, so probably the records associated with those orgs would be deleted. Or possibly they could be move to another org before deleting their own org. Needs design before implementing.

**Comment by RDmitchell** [comment]
The first step is to understand how the orgs and sub orgs work, document it, and then write a spec for deleting them.

**Comment by StephenCzarnecki** [comment]
@RDmitchell   This isn't so much a spec as notes and questions that arise as I try to follow the role that the organizations play.  I've been looking at various bits of the app and have a couple questions so far.

The first major question I've run across is what should happen to users without any organizations?  Most things in the app aside from users seem directly tied to a particular organization.  So for these things the action when deleting an org seems pretty clear:  They get deleted too (see the end of this post for a question about what "deleted" means here).  But users seem like they can span organizations.  And there are various things in the app that seem to expect that a user has at least one organization..

I have looked at a few things so far that seem to break without an organization (building list, is_authorized).  The authorization check in particular is interesting in that it doesn't actually do anything with the user's organization, it just throws an error if it is missing.  Also the clients for is_authorized are all in the javascript side of things.  The python is_authorized seems to map to the js auth_services.is_authorized function in static/seed/js//services/auth_services.js and is used in 12 places in static/seed/js/seed.js  

So it appears when the user tries to do something that the javascript thinks requires authorization (like data mapping) the javascript fiorst checks if_authorized.  Since this is the case maybe we can change is_authorized to react a bit better when a user has no orgs.  Maybe just return False if the action is something like requires_member or requires_owner and maybe something else for other actions?

In general I can currently think of four options to the general problem of "Pieces of the code assume that a user has at least one organization."  Maybe someone else has a better one?
1:  Decide to just delete any users that end up without an organization.  
2:  Find everywhere that assumes one or more organizations and change them to work when there is none.
3:  Use some sort of special "deleted" organization for users with no organization.  May require still doing option 2 in spots depending on what the desired behavior is.
4:  Put in some mechanism to re-direct any users without an org to create an org.

Next I started looking at which seed models have a relation to Organization.  Here is a list so far:
* Project
* StatusLabel
* CustomBuildingHeaders
* Column
* ColumnMapping
* Schema
* BuildingSnapshot

Do any of those need to be kept when an organization is deleted?

Finally when things are deleted using this new feature are they really removed from the database or is it like the current behavior for deleting a building?  When you delete a building through the app it isn't really deleted, a flag is just set.  Rather like how deleting files on most hard drives works.

**Comment by RDmitchell** [comment]
@StephenCzarnecki 

1 - I believe that all users should be tied to an organization. If there are users without an organization I would consider that a situation caused by a bug in the program. We should go through the code and do some testing to make sure that it is not possible to create a user without also creating an organization. At some point we should look at the production server and find the orphaned user accounts and figure out what to do about them. Presumably they are not working properly.

3 - I can't really assess the SEED models related to an organization, but I would assume that all the ones you listed should have data deleted from them. I think that all records tied to Organization would be deleted when an organization is deleted. 

2 - If an organization is deleted, I would say it is REALLY deleted. I don't see any reason to keep anything about it in the database. In the near future we need to write code to "export" a complete organization so that everything can be moved to another instance of SEED (or to archive it), but for this exercise, let's assume we don't have to worry about that, and do a complete deletion.

**Comment by StephenCzarnecki** [comment]
After talking briefly with Robin:  If a user only belongs to one organization and that organization is deleted the user should also be deleted.

**Comment by nicholasserra** [comment]
Was any design done for this yet? I don't think the backend work will be a big deal, probably a day. I can just mimic the delete buildings admin function for the frontend. Do we want to see a big list of orgs and sub orgs, with delete buttons? @RDmitchell

**Comment by RDmitchell** [comment]
No UI design. 

Right now when I log in as superuser, and go to the Admin page, I see this
![image](https://cloud.githubusercontent.com/assets/6314950/13756872/3174539c-e9df-11e5-8dc4-e6caf7942828.png)

Seems like we could add a section below the Add/Remove a user called Remove Organization
![image](https://cloud.githubusercontent.com/assets/6314950/13757189/897001bc-e9e0-11e5-8008-914e73370445.png)

**Comment by nicholasserra** [comment]
Looking at the UI again, another clean option could be to add a "Remove organization" button right next to the existing "remove buildings". 

Both options should have a prompt to confirm.

**Comment by RDmitchell** [comment]
I thought about that but also thought it would be weird because you would click the button and the line would disappear.

Also, I don't want to mix up deleting an organization and deleting buildings. Accidentally clicking the org button instead of the buildings button would be a drag, even if the program prompts you 

I think they need to be separated.

**Comment by nicholasserra** [comment]
So I plan on sort of piggybacking this off the existing functionality of "remove buildings", as there's a lot of similar stuff. But in looking at how delete buildings was implemented, I think it could be done a lot cleaner and faster, maybe even without a celery task involved. It's sort of a hunch.

@RDmitchell should I go with existing code and try to get this working as is, or should I take a little time and try to clean up / speed up the underlying delete buildings functionality right now?

**Comment by RDmitchell** [comment]
If you can improve the Remove Building functionality, which is quite slow right now, do that, and then use that for the delete organizations feature.

**Comment by RDmitchell** [comment]
what level of effort will each of those pieces be?

**Comment by nicholasserra** [comment]
Unfortunately i'm not sure. I'll cap myself at a couple of hours on my hunch. Does that sound okay?

**Comment by RDmitchell** [comment]
sure

On Mon, Mar 14, 2016 at 5:19 PM, Nicholas Serra <notifications@github.com>
wrote:

> Unfortunately i'm not sure. I'll cap myself at a couple of hours on my
> hunch. Does that sound okay?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/SEED-platform/seed/issues/13#issuecomment-196583656
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by nicholasserra** [comment]
@RDmitchell this action is going to require a progress bar, as it's going to take longer than it would just to remove all buildings from an org. As I go the route you suggested with the UI, where do you see a progress bar shown? I'm trying to reuse as many components as possible, so I don't eat up a ton of time writing this stuff from scratch.

**Comment by RDmitchell** [comment]
Since this is a superuser admin function, you should definitely reuse code and it doesn't have to be beautiful, as only a few people are going to use this functionality (us, other web hosting providers, IT depts if they stand up their own instance, etc.). 

You could just take over the whole screen while you are doing it with a progress bar, and then I guess nothing else can happen until it finishes. 

The other thing would be to emulate the red progress bar for the Remove Buildings -- right now when you click that red Remove Buildings button it turns into a progress bar and then displays success when it is finished. Don't know if this makes sense or not, because the organization will not exist at the end when the bar says success (?).

But yes, spend as little time on it in terms of making it nice. Functional is good, beautiful is not required !

**Comment by nicholasserra** [comment]
The simplest route is to emulate that little red progress bar like "remove buildings" does. But you had concerns about placing a second button next to that, which I put more thought into.

The issue is that all the remove building stuff that i'd like to use is really geared towards how that "remove building" button works, and i'd like to reuse it. So I was thinking it might be safe and user friendly if we implement the button with some new colors, side by side, with a warning icon, and also, for this action, we do a _double_ warning confirmation modal, one after another.

![screen shot 2016-03-15 at 5 32 17 pm](https://cloud.githubusercontent.com/assets/512288/13794782/0e4df0b2-ead4-11e5-9519-fbdb8af61494.png)

**Comment by nicholasserra** [comment]
Also I planned on doing a full page refresh after the org is deleted, as there are many things tied to the org list that need to be updated.

**Comment by RDmitchell** [comment]
Sure, I think just changing the color scheme would probably eliminate my concerns. And maybe making a bit of space between the two buttons so that your mouse can't accidentally hit one because it wasn't inside the border of the other (?)

**Comment by nicholasserra** [comment]
Sounds good to me

**Comment by RDmitchell** [comment]
My only Feedback (!)

**Title of section on page**
* Rename "Remove all buildings from an organization" to something like "Remove buildings and organizaions" (?)

![image](https://cloud.githubusercontent.com/assets/6314950/13894833/8d357e20-ed29-11e5-8200-9472ca2c081d.png)

Seems to be working well -- I am going to start cleaning up seedtest.

Anything you can think of that I should test ? I guess at the very least, trying to log in as a user that I just deleted the organization for.

**Comment by RDmitchell** [comment]
one more comment is that it seems to sometimes take a while for the browser to refresh after deleting an organization, so that the org appears to be there, although if you force a refresh they are no longer there. But it didn't happen all the time, just every once in a while.

**Comment by RDmitchell** [comment]
Maybe the refresh takes longer when there are more records to delete and the entire process takes longer -- for the cases where the deletion happened quickly, it seemed like the browser refresh also happened quickly.

**Comment by RDmitchell** [comment]
on the other hand, because this is a superuser feature, it's not the end of the world if the superuser has to refresh the browser by hand.

**Comment by RDmitchell** [comment]
@nicholasserra -- what happens if I refresh the browser in the middle of a deletion? I thought it was finished, I refreshed the browser, the org was still there, I clicked delete again, and now it seems stuck -- the progress bar is empty and not moving, but no errors appear. I will let it sit for a while and see if it eventually finished.

**Comment by RDmitchell** [comment]
but then when I log out, and log back in, the org is gone. So it's probably ok. If I can figure out a way to reliably reproduce this case, I will make another issue. I am going to close this issue.

**Comment by RDmitchell** [comment]
am reopening for myself to continue doing some tests before declaring it's ready for production

**Comment by nicholasserra** [comment]
It should only refresh the page if you delete your current active org. Otherwise it should update everything in place.

via Hiptop

**Comment by RDmitchell** [comment]
What do you mean by "current active org" ?

**Comment by nicholasserra** [comment]
The organization you currently have selected in the organization drop down menu top right. 

via Hiptop

**Comment by RDmitchell** [comment]
@nicholasserra -- I am having trouble deleting one of the test orgs on seedtest (although all the others have delete fine !?!) Here is a link to a video
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LY0xiTy1iTzhKd2M/view?usp=sharing

**Comment by RDmitchell** [comment]
hmmmm, I'm not sure that pulldown in the upper right should even come into play in the superuser admin screen ... I never pay any attention to it. We might need to rethink how that works in this screen.

**Comment by RDmitchell** [comment]
and, by the way, per the video, the org that I couldn't get rid of (in the video) is now finally gone, after having logged out for about a half hour and then logged back in.

**Comment by nicholasserra** [comment]
It only comes into play because it's basically global to the application. It's not really affecting anything. The org that was hanging might have had a ton of data, glad it finally was removed. Let me know if you see any other specific issues with this whole process.

**Comment by nicholasserra** [comment]
@RDmitchell do we have any concrete issues with this? Thinking we should close this main ticket either way.

**Comment by RDmitchell** [comment]
Yes I will close this issue.
