### ISSUE TITLE
DQ Check - Allow sorting by column in DQ results modal

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1362]
instance: dev1
SHA: 3750bb2
Org: LBNL Test 200
Cycle: DQ Test

It would be nice to be able to sort by any of the columns in the DQ results modal -- I would like, for example to wort by Field or Error message to make sure that all the DQ checks were performed. 

I guess this would mess up the row color coding that is now showing the grouping by PM Property ID but maybe something else could be done about that. 

![image](https://cloud.githubusercontent.com/assets/6314950/26467352/1c426ffc-4147-11e7-8b34-db5a17097822.png)

**Comment by axelstudios** [comment]
This is by design because right now errors are grouped by the record they correspond to - e.g. in the screenshot below, each record has 2 errors.  The only way we would be able to sort by field/error message would be to break apart this grouping

![image](https://user-images.githubusercontent.com/411466/37117037-3aa3629c-220d-11e8-900f-cb3901f5f0f2.png)

**Comment by RDmitchell** [comment]
Ok, thanks
