### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1503]
Quickly fix the password reset issue.

**Comment by RDmitchell** [comment]
@nllong -- you might have closed this prematurely. The email I get when asking for a new password is this

![image](https://user-images.githubusercontent.com/6314950/32757460-75f283fa-c894-11e7-885e-c81a068bebc4.png)
which points to

https://example.com/accounts/password/reset/confirm/Mzc3/4r4-8b87b3dde50a99968076/

so that when I click on it, I get this
![image](https://user-images.githubusercontent.com/6314950/32757478-8b778bda-c894-11e7-8f31-61365bcbe72a.png)

**Comment by nllong** [comment]
Hmm. I’ll check this tomorrow. Thanks.

**Comment by nllong** [comment]
test again.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 63efa9d
tested several times, seems to be working now
