### ISSUE TITLE
Mapped fields with underscore are transformed to a field name without underscore

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1509]
instance: seeddemostaging
SHA: 2c52627
Org: LBNL 22

See this folder
https://drive.google.com/open?id=1PjJ6Tk6aGYRIZyaXoC65LfyNxwLEzFT6

Mapped fields with underscore 
![image](https://user-images.githubusercontent.com/6314950/33100341-ddd0c5b0-cec8-11e7-8358-06fdef3fa615.png)

Gets transformed into
![image](https://user-images.githubusercontent.com/6314950/33100389-09f25d84-cec9-11e7-98a8-141a0b7d8e56.png)

The desired behavior is that the program keeps the mapped fields exactly as they are specified on the mapping screen

**Comment by RDmitchell** [comment]
I verified this behavior on dev 1, SHA: 63efa9d

**Comment by nllong** [comment]
unfortunately, this is by design since the display names of the columns are dynamically generated. The logic for the display name is to title case the backend names, and the backend names are snake_case (with underscores). So if a user creates a name with an underscore, it is going to convert it to a nice display name. The backend does store the column with the underscore, so once we support #1191 we will be able to show it correctly.

**Comment by RDmitchell** [comment]
OK, I will add this the user documentation. Thanks
