### ISSUE TITLE
Data Analysis: Ability to define new calculated fields based on existing data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1642]
### Expected Behavior
New feature which would allow users to define new fields in SEED (after data has been imported), based on other fields in data that has already been imported, including the ability to define calculations based on existing data (fields). 

* This is a bit of a follow-on to #1640 -- it would be useful in defining DQ rules (as illustrated in the 2nd example in 1640) but would be useful in general for data analysis. 

* And it is also a follow-on to #1641 -- maybe that issue is really this issue, and it's not a formal report, but the user is able to define that new field and how the program would calculate it. 
 * For example, in 1641, the user could define those new % fuel type fields as desired, selecting the fields from the data that has been imported
   * % Electricity Mix = [Electricity Use - Grid Purchase (kWh)] / [Site Energy Use (kBtu)]
   * % Natural Gas Mix = [Natural Gas Use (therms)] / [Site Energy Use (kBtu)]
 * Then maybe in a user defined reporting function, the fields could be defined to be part of the report (#1641 )
### Actual Behavior 
Program currently doesn't have this functionality
### Steps to Reproduce
Program currently doesn't have this functionality
### Instance Information
instance: LBNL staging/ production
SHA: 36cc59d

**Comment by macintoshpie** [comment]
@RDmitchell @nllong @adrian-lara 
Here's a wireframe of what I'm imagining this feature basically looks like to get things rolling. I'll get a time setup for all of us to align our ideas and discuss what's needed/possible.

Here are some questions we'll need to consider, no need to answer these right now, just something to start thinking about.
- what are the operations a user can use in the expression?
  - `-, +, /, *`
- should we only allow arithmetic, or also allow string operations?
  - maybe just arithmetic for now to keep things simple?
- who can create derived columns?
  - org admins?
- where do you create derived columns?
  - in org dashboard
- when are derived values updated? Is it applied to all properties/taxlots?
  - when derived column is created?
  - do you automatically apply all derived columns to new properties in imported data?
  - if updating existing properties on import, do you recalculate derived columns?
  - after manually editing/updating referenced field for a property?
- are derived columns cycle-specific? (if a user has cycle A and cycle B, imports to cycle B with new cols,
  do we add those cols to properties in cycle A?)
- can derived columns reference derived columns?
- can you edit derived columns after they're created?
  - implication is creating cyclical dependencies
- when importing, can a user use a derived column name as the column name for an import field?
- how do we handle properties that are missing one or more values for a referenced field?
  - set derived column to null?
- does adding/recalculating this field result in a new property state in audit log? what if multiple referenced columns are updated, does each derived column update result in new state?
- what happens on merge? unmerge?
- when should SEED not treat a derived column like a non-derived column?
  - editing (should not be allowed to edit derived value)
  - ??
 
Technical Questions:
- can we just store derived results in extra data? obviously still need additional models/fields for defining how they're derived etc

<img width="1066" alt="Screen Shot 2021-04-07 at 11 31 43 AM" src="https://user-images.githubusercontent.com/18518728/113909707-392b6a80-9795-11eb-8d24-3f755da03fd5.png">

**Comment by adrian-lara** [comment]
Looking forward to the brainstorming call happening for this. Just wanted to leave some initial thoughts on how we might be able to handle the corresponding record values from these derived fields:

- It would be nice to avoid pre-save hooks on models with so many records. I wonder if we could calculate values on-the-fly. I'm not 100% sure this is a reasonable approach for the following reasons.
--
In the case of seeing values in the inventory page, I can't imagine it would take long (because of pagination?) to insert the calculated values after page load (and it could be promise-based). Notably, that would likely be done in the frontend. So for integration with DQ checks, calculations would need to happen in the backend. We'd have to find a way to perform the same calculation in both the frontend and backend. 
- I'm wondering if we can persist the values and keep them aligned as expected without pre-save hooks. 
--
I'm not sure if this is a reasonable expectation of users, but I'm imagining that they could run these calculations manually whenever they needed to populate or update the values. (They do this for DQ checks, so maybe it's not too much to ask.) If we did this, we could largely manage the data just like any other extra-data fields. A small caveat might just be that we'll purposely leave these fields blank on the resulting records of a merge and unmerge. And if records are being imported with these fields pre-filled, we could just ignore them to avoid the complication of import merges that may happen.

**Comment by macintoshpie** [comment]
Updated design lives here: https://docs.google.com/presentation/d/1sJauilNj2xdqYSqOL4OHECqFJ9hK1RkKAeBTszKUxh8/edit?usp=sharing

**Comment by macintoshpie** [comment]
Some high level design notes:

- what are the operators a user can use in the expression?
    - `-, +, *, /, %`
    - grouping, `( )`
    - STRETCH GOAL: simple functions `min()` and `max()`
    - integer/float constants, e.g. `3.14159`
- how do we handle unitted columns?
    - Just warn the user they are using a unitted column
- what if an inventory is missing one of the source columns or it's value isn't valid (e.g. string instead of number)
    - set the derived column value for that inventory to `NULL`
    - FUTURE GOAL: allow some sort of fault tolerance or default value
- you can delete derived columns. you can edit derived columns (display name, calculation -- cannot edit inventory type)
- derived columns can source values from the "core" seed columns and extra data. you CANNOT source data from another derived column
- derived columns cannot be used for matching
- derived columns are applied across all cycles to all inventory
- when do you update a derived column value?
    - when the column is created
    - when a source column is updated (manually edited, updated property ie merge, ...)
    - when a new property is created
- calculation of derived columns should be very error conscious
    - avoid race conditions with user editing data while things are being calculated
    - handle cases where a calculation unexpectedly fails (ie the value should eventually be correct in a reasonable amount of time)
- derived columns can be used in data quality checks
- derived columns are displayed like regular columns in inventory list

**Comment by RDmitchell** [comment]
@macintoshpie -- how are units defined for the final derived field? It looks like there is not a way to specify the units. And it doesn't seem that the program determines the units automatically from the fields being used in the derived fields. 

Is this a future feature?

**Comment by RDmitchell** [comment]
Another issue for future improvements #2760

**Comment by macintoshpie** [comment]
@RDmitchell in response to

> how are units defined for the final derived field? It looks like there is not a way to specify the units. And it doesn't seem that the program determines the units automatically from the fields being used in the derived fields.

Units are not handled at all currently -- we just grab the value out of the database and use it. We originally planned on adding a warning if a user was including a unit-aware field, but ran out of time. Thanks for adding it to the feature list though, we need to get this fixed up.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 4d08f5057
Org: LBNL test 200
Cycle: Derived Column Testing

I would say this is done to first order. We can make new issues for whatever we find as we do more testing and as users start to use it.
