### ISSUE TITLE
Importing Data with the Same Address on Multiple Rows do not track lot_numbers

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1649]
The other issue that is happening in this case is that the pairing between the Tax Lot and Address only happens with the one finally merged record.

Use the file from #1639 and follow the mapping steps from that issue (ie, map Address line 1: Property and JurisdictionTaxLotID:TaxLot) so that all the records are merged into one Property record.

From @nllong (slack thread 5/23/2018)

* When importing the data, the idea of the row disappears, that is, knowing that the address is associated with the tax lot, disappears when all the addresses get merged down to a single address. So when we try to pair, the knowledge that all of the individual addresses were once assication with n jurisdiction tax lots, is lost, so on pairing, the system just pairs the one the matches the jurisdiction taxlot id is the same... all the others are orphaned.
* fixing options 
    * magically concatenate jurisdiction_tax_lot_ids when merging (similar to 123;456;789; in a single row). 
    * save a new custom ID that persists a row ID, so upon merging down the row ids will persist.
Here is what the pairing screen looks like for this case

![image](https://user-images.githubusercontent.com/1907354/40453333-1c9f3f92-5ea2-11e8-8108-64e011435fdc.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 90e4a7d
Org: LBNL 20
Cycle: Test Unmerge Fix 1639

This is now working -- a bit of an odd example, because all the records that have the same address have been unmerged from each other, but I think the program is doing what it is supposed to be doing. 
![image](https://user-images.githubusercontent.com/6314950/40560934-53974a16-6010-11e8-903f-a17cd0bf8581.png)
![image](https://user-images.githubusercontent.com/6314950/40561011-82c5e860-6010-11e8-8810-ea885e2f3a3c.png)

**Comment by RDmitchell** [comment]
instance: LBNL staging
SHA: 9e003b3
Org: LBNL 551
Cycle: Test 1639

working properly
