### ISSUE TITLE
Deleting all records for an org doesn't delete values in column settings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1718]
### Expected Behavior
I am not sure what the right behavior is, but it seems if you delete all the data (via the Inventory Property and Tax Lots) for all cycles, there would not be any values to display in the Column Settings view.
### Actual Behavior 
After deleting all the data in all cycles from an Org, the Column Settings view still shows the original fields that were imported that now longer exist.
### Steps to Reproduce
Delete all the data in an org
Go to the Column Settings
I believe you will see the columns that used to exist for the data that has now been deleted. 
### Instance Information
Instance: seeddemostaging
SHA: f7984a7

**Comment by nllong** [comment]
Best approach is probably to add another button to delete all column settings (next to the delete inventory button). This will let the user decide what to do instead of us assuming what the user wants to do.

**Comment by axelstudios** [comment]
@RDmitchell I need a little more clarification on this one - do you mean *Column Settings* (like the data type associated with extra_data columns and merge protection settings for all columns including the default), or *Column Mappings* that include only column names from imported files and the fields they mapped to?

Currently there isn't even an option for admins to delete Column Settings, since that has all sorts of implications about checking that there are definitely no records that still use a column that you might be trying to delete, but it's easy to delete Column Mappings that have been associated in the past.

**Comment by RDmitchell** [comment]
OK, I think we can just close this issue. I might document this behavior (or not, as it probably won't happen very often to real users).
