### ISSUE TITLE
Investigate why matching a 2nd PM file without PM Property ID set fails

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#176]
I will write this up in more detail soon.

**Comment by RDmitchell** [comment]
Do this test with the files in Issue 65 -- each of the files have 10 records that should match on Address. Use 2012 and 2013 PM files (2011 has one record with a different address so you don't need to both using it)

1 -- Import covered buildings. Only change the following mapping: UBI = Tax Lot ID, Address = Address Line 1
2 -- save mapping, you should get 10 building records
3 -- import 2012 PM file. Only change the following mapping: Address 1 = Address Line 1
4 -- save mapping, you should still get 10 buildings, and if you look at the building detail you will see that covered building list and 2012 PM files are both merged into the master building record
5 -- import 2013 PM file. Only change the following mapping: Address 1 = Address Line 1
6 -- save mapping. You should now get 20 buildings, because the program doesn't find a match on address in the 2013 PM file against the master building record.

To make the 3rd file work, if you add a 2nd mapping of Property ID = PM Property ID (in addition to changing to Address Line 1) then the 3rd PM file will match to the Master Building record. 

I can make a video of the problem if that helps, just let me know.

**Comment by RDmitchell** [comment]
Link to test files for this issue (basically the issue 65 directory)
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LTmlyM2w0MHRKeVE&usp=sharing

**Comment by spencerdutton** [comment]
Using the API script provided by Claudine I was able to reproduce the issue. I removed the new changes to the matching code, and replaced the fuzzy logic matching. The issue appeared to still be present. Firstly, if we are 100% sure the script works correctly and is replicating the behaviour described above by the user, then we need to move to identifying a version of the code base where this issue does not exist. Then (perhaps a binary search, rather than sequentially going though each change), we need to find which change broke it.  

Spencer
