### ISSUE TITLE
403 error when trying to add existing user to existing organization

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1808]
### Expected Behavior
should be able to add an existing user to an existing organization (as a superuser)
### Actual Behavior 
sometimes (possibly if the user or org has just been created), program throws a 403 error when trying to add an existing user to an existing organization
### Steps to Reproduce
See doc in the issue folder
https://drive.google.com/open?id=1khOxc6vLxelvdXsDa-HYwXSzlUIoAVhu
### Instance Information
Instance: seeddemostaging (LBNL)
SHA: 214f0f5d

**Comment by RDmitchell** [comment]
instance: staging (LBNL)
SHA: 4c791c17

I have two users, A (RM 20) and B (RM 333)
I have two orgs, X (LBL 20) and Y (LBL 333)

I added user B (RM333) to Org X (LBL 20)

When I log into Org X (LBL 20), I don't see user B (RM 333)
When I log into Org Y (LBL 333), I see Org X (LBL 20).

This seems backwards to me. 

Seems like if I log into Org X (LBL 20) I should see user B (RM 333), but I don't. 

I am very confused (!)

**Comment by RDmitchell** [comment]
@nllong -- see screenshot of email that SEED sent when adding user RM 333 to Org LBL 20, in the issue folder. That email indicates what I thought would have happened, but I think the reverse happened, as indicated by my previous comment. 

https://drive.google.com/open?id=1khOxc6vLxelvdXsDa-HYwXSzlUIoAVhu

**Comment by RDmitchell** [comment]
@nllong -- this happened again today. 

Trying to add an email in "Add user to organization" pulldown to an existing organization, got 403 error

Here are the details
https://docs.google.com/document/d/1wCP0u05hr50jduvPjNgbPYIYYgbZnTEqsV7wnSzZekc/edit?usp=sharing

**Comment by adrian-lara** [comment]
Having tried to add/remove existing users from existing orgs multiple times, I'm having a hard time replicating this. 

Looking at:
1. https://drive.google.com/open?id=1khOxc6vLxelvdXsDa-HYwXSzlUIoAVhu
2. https://docs.google.com/document/d/1wCP0u05hr50jduvPjNgbPYIYYgbZnTEqsV7wnSzZekc/edit?usp=sharing

The error messages provided would hint that when this error occurs, you've been logged out of your current session. Being logged out can and should happen due to inactivity and logging out within another browser window.

Unless the frequency of this increases, I would say no additional action is needed.

**Comment by RDmitchell** [comment]
@adrian-lara -- I agree -- I haven't seen this happen recently and I just tested it and it seems to work. It could very well be on my side in terms of network connection, etc. 

Closing -- will make another issue if I run into this again
