### ISSUE TITLE
Problem importing PM file for Issue 25

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#186]
I (and others) can't upload the test file used in Issue 25 to test the matching rework:

it is in 
Google Drive\SEED Shared Folder\Software Development\Issues\Issue 25
Called
PM File.csv

I have been uploading it by clicking on the "Upload Portfolio Manager data" button. You could also try uploading it using the "Upload a Spreadsheet" button and see if there is a different in behavior.

When I try to upload this file into seedtest, the program hangs at 45%.

**Comment by spencerdutton** [comment]
Ok Im on that.

On Tue, Apr 7, 2015 at 10:45 AM, RDmitchell <notifications@github.com>
wrote:

> Assigned #186 <https://github.com/SEED-platform/seed/issues/186> to
> @spencerdutton <https://github.com/spencerdutton>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/186#event-275507572>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by spencerdutton** [comment]
using the development code, using the old matching method I tested that the PM File.csv loads(using either the special PM data button or the excel button) and it is mapped in the mapping each time I set the address line to be "address line 1". I then loaded the same file again and confirmed that the mapped and matched  all 12 buildings.  OK so far.

I then repeated the process with the new matching method, each time I set the address line to be "address line 1". I then loaded the same file again and confirmed that the mapped and matched  all 12 buildings with 100% confidence. 

I repeated this process, but this time, not mapping to address line 1. The files loaded, and mapped, but the message "matching already completed" was shown when matching was attempted. This I think is because we don't have any IDs or address to match on.

**Comment by RDmitchell** [comment]
When testing on seedtest I don't even get to the point of being able to map the PM file. It hangs on 45%. Maybe it has to do with other changes made to the code that have gotten merged into seedtest. At this point I can't really test that Issue 25 is fixed, because I can't load the files used to show the problem.

**Comment by spencerdutton** [comment]
So I guess one question is whats different between my development code and
the code you are testing. Matching doesn't happen on loading the file, so
it makes sense we don't see a difference. I pulled my code on Thursday of
last week. I bet there is a way to find the exact version, anyone?

Spencer

On Tue, Apr 7, 2015 at 1:24 PM, RDmitchell <notifications@github.com> wrote:

> When testing on seedtest I don't even get to the point of being able to
> map the PM file. It hangs on 45%. Maybe it has to do with other changes
> made to the code that have gotten merged into seedtest. At this point I
> can't really test that Issue 25 is fixed, because I can't load the files
> used to show the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/186#issuecomment-90720534>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by RDmitchell** [comment]
This is what Stephen is trying to figure out for the other matching issue. So we should let him figure that out first and then tackle this one.

**Comment by RDmitchell** [comment]
I have moved this to Stephen's queue so I am closing it here
