### ISSUE TITLE
Wide left column in matching

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#188]
The behavior of the far left column in the matching report can make it difficult to quickly compare columns. It seems like it is set to fill as much available space as possible but this can create a large visual separation between source and matched buildings if the window at a full screen size.

**Comment by RDmitchell** [comment]
Julie -- I finally figured out an example of the wide left margin on matching. In this case, I am only displaying one field, and it is a small field, ie, Tax Lot ID, but the program makes the left column very wide. What I would like it to do is to just make it the width necessary to show the data, which would make it much narrower and would make it much easier for me to go down the list and compare the two Tax Lot ID fields side by side "by hand" by just looking at the data. 

I reduced the size of my browser window to force the columns to be as close together as possible, but because the left hand side seems to be fixed at some width, this is as close together as I can get them under this circumstance -- if I make the browser window any narrower, it starts to cut off the data on the right hand side. 

Here is a link to the sample data files which I used in the example below
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LTkFac2VzVlFtZFk&usp=sharing

Let me know if you have trouble reproducing this or have other questions.

![image](https://cloud.githubusercontent.com/assets/6314950/7243424/c50d485e-e781-11e4-81b0-20de94726626.png)

**Comment by juliecov** [comment]
The problem here is that the dark grey bar on the left, with the "File Source" dropdown and matched/unmatched radio buttons, is configured to span all columns related to the source file.  When the user chooses to display just one skinny column (or even just a couple), the content inside the grey bar causes the column to stretch out wider than the data in the column. 

The two grey bars seem important for indicating which columns come from the source file, and which are the matches – but there should be a good way to still display this information, just not linked to the table as it currently is.  One option is to separate out the file source label and dropdown and matched/unmatched radio buttons and show them above the table, then come up with a different (shorter?) header to put in the grey bar.  Design isn’t my strongest area; is there someone who could put together a quick mockup, then I could build it out?  Or, if you prefer I could take a first pass at it to see what you think.

This will continue to be a problem even if the user can resize the columns, so if this is annoying users I do think it would be good to address it.

**Comment by RDmitchell** [comment]
This should be solved when we move to the new column sizing implementation in Issue # 71, so I am closing this issue
