### ISSUE TITLE
User control over where export file is saved

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#19]
User should be able to control where the export files are saved, i.e., a browse option to select the folder. Right now the files are always saved in the Downloads folder. Should also allow overwriting of existing file, with the standard warning.

**Comment by philngo** [comment]
Presumably for security reasons, browsers won't let javascript change the download location, or even allow overriding user browser settings to show a browse to download location prompt.

Even though we won't be able to do it on our end, most browsers do allow users to set this option in their preferences. With that in mind, we shouldn't be too worried that omitting this feature will degrade user experience; in fact, quite the opposite, since we won't be overriding their preferences.

The existing implementation, which allows users to choose a file name and type, is likely as good as it's going to get, since it already provides as much data to the browser as possible.

**Comment by RDmitchell** [comment]
Thanks Phil for the investigation. 

I will close this issue.
