### ISSUE TITLE
Update BuildingSync to BuildingSync 2.0-pr1

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1929]
Support BSync Version 2.0-pr1

**Comment by RDmitchell** [comment]
instance: dev1
SHA: e120119f
Org: LBNL 200
Cycle: 2019 Compliance

I was able to import the test file called
* buildingsync_v2_0_bricr_workflow.xml
into this org

It's a bit of an odd workflow, because I can't see any way to associate this XML file with an existing building record. But then again I didn't really study the XML input -- so maybe by setting a Custom ID or Address or some other field properly it would have matched.

But in any case, the file imported without issue, made a new record in the Inventory Property tab, and displays the measures, etc. 

![image](https://user-images.githubusercontent.com/6314950/61572081-a93c0f00-aa4d-11e9-8383-9cdbefc2c89f.png)

@nllong -- I am closing this but if other people need to test, it can be reopened.
