### ISSUE TITLE
Allow user to specify which fields are to be used for geocoding

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1963]
Currently SEED uses predefined database fields to geocode (e.g., address_line_1, city, state, postal_code), however, not all users are storing their address data in these fields.

This enhancement would allow the user to set up the address fields in the column settings page to be used for geocoding (properties and taxlots).

**Comment by adrian-lara** [comment]
@nllong Should extra_data columns be eligible to be used for geocoding? 

Also, I'm thinking users should be able to specify the order in which their chosen fields are concatenated in order to build the "full address" that'll be geocoded. I'm not sure how this'll be implemented just yet, but I think this is necessary. Let me know your initial reaction, if any.

**Comment by nllong** [comment]
Yes, extra_data should be eligible. Concatenation sounds right.

Nick

**Comment by adrian-lara** [comment]
@nllong or @RDmitchell
I'm wondering how users that don't use SEEDs provided address fields (address_line_1, city, state, etc) store their address data. Is it ever the case that they are using just one field with a "full address"? Or are they still storing address information in multiple fields?

I'm asking because of the following: 
For geocoding, there are cases where MapQuest API gives SEED valid and specific-enough geocoding locations that are potentially "incorrect". For example, something like `100 Market Street` can exist in many cities. MapQuest API can provide one of several valid and specific-enough geolocations that SEED would accept.

In the initial setup of geocoding in SEED, I avoided this by requiring that at least 3 address components were provided before attempting to geocode. With the default geocoding columns being:
- address_line_1
- address_line_2
- city
- state
- postal_code
Requiring 3 of those ensured that at least one of city, state, or postal_code would be used in a valid geocoding result. (Having the 3 be exactly city, state, and postal_code wouldn't return a geolocation with a high enough specificity rating for SEED to accept.)

I wouldn't expect to handle every possible case, so if all remains the same, at the very least, I'll be adding text in the column settings page mentioning this requirement of 3 fields. But if there are common cases that should be addressed (like one would that would prevent geocoding entirely by storing everything in one field), I'm wondering if we need to reconsider how SEED is set up to prevent accepting valid but potentially "incorrect" geolocations.

**Comment by adrian-lara** [comment]
Capturing conversation: There are current cases where users store complete, geocode-able addresses in one field. Requiring 3 or more fields be used for geocoding can't be enforced. A different approach must be taken to address the case of valid but ambiguous cases.

@nllong I'm thinking/planning that SEED won't geocode a record if the address ever returns multiple valid geolocations. This would require logic be run on the resulting MapQuest API return values, but likely won't be enough to greatly increase geocoding times.

Let me know if you think of any reason not to take this approach.

**Comment by RDmitchell** [comment]
@adrian-lara -- I am trying to test this. 
Can the geocoding world handle zip+4 (which I have in one test file) or should I just stick to the standard 5 digit zip code?

**Comment by adrian-lara** [comment]
@RDmitchell It should be able to handle zip+4. SEED essentially just passes on the address details on to MapQuest, and from what I recall, they do accept that zip format. 

Definitely let me know if that isn't the case though! 😄

**Comment by RDmitchell** [comment]
So with both the Geocoding settings and the Matching fields, the user has to import the file before SEED knows what the fields are. 

That seems like a bit of a problem, which maybe we can address sometime later this year, ie, maybe the program allows the user to import a file in the Column Settings world (?) just to get the fields, which the user can then set up with matching, geocoding, etc.

**Comment by RDmitchell** [comment]
I can't finish testing this until #2052 is fixed

**Comment by nllong** [comment]
@RDmitchell #2052 is now on dev1.

**Comment by RDmitchell** [comment]
I did a lot of testing of this with various extra data fields, and it seems to be working well. 

See this folder which contains an input file and a doc explaining the tests.
https://drive.google.com/drive/folders/19pfTX1ssz2WdyyvKf-_4yy1b49lpn8Fs?usp=sharing
