### ISSUE TITLE
Cycle Date changes ?

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1969]
### Actual Behavior 
From Andrew Held, DC

Was there a recent change to how cycle dates are determined in SEED? We have our cycles defined as being the 1st of January to the 31st of December (see screenshot below). However I was just running some API tests and notice that the cycle dates seem to be offset by a date (see output here). This seems like a bug but I’m not sure.

Also just confirm – I was trying to call the label list (for https://seedv2.lbl.gov/api/v2/labels/filter/?inventory_type=property_view&organization_id=303) and my code broke. Are the tax lot and property tables officially called “Taxlot_view” and “Property_view”? When I was calling the label list my code broke since I realized I only had them “Property” and “Taxlot”.
### Instance Information

Instance; LBNL Production
SHA: f6087ac1

**Comment by adrian-lara** [comment]
@RDmitchell @nllong Regarding the Cycle date shift, would it be possible to get the screenshots mentioned? I'm wondering how big of a shift it was.

Regarding the label list API, the shift from using "property" and "taxlot" to "property_view" and "taxlot_view" is expected. We recently moved label associations from the Property and TaxLot models to the PropertyView and TaxLotView models in preparation for linking.
You can see our FE using these new terms here:
https://github.com/SEED-platform/seed/blob/f6087ac11b78fded73ea4c725525ccc740b7ec8e/seed/static/seed/js/services/label_service.js#L68
 
To answer Andrew's question of: 
> Are the tax lot and property tables officially called “Taxlot_view” and “Property_view”?

These -View models are a piece of what's used to store and render what users see as a "property record" or "tax lot record". Under the hood, the PropertyState/TaxLotState models (which actually hold actual record information such as address, site_eui, etc.), and Property/TaxLot models (which will eventually help associate records across Cycles) are referenced by the PropertyView/TaxLotView which is used as an access point to the -State data and also has recently been updated to associate labels to a record.

**Comment by adrian-lara** [comment]
I'm closing this issue. We addressed these issues separately and I recapped our findings in 2 separate emails. 
Here are the relevant excerpts from each email:

> Email 1
1. We were able to explain the difference in the Cycle start dates between the API and what's shown in the actual web app. On the backend, SEED stores Cycle start and end in Pacific Time. Using the API directly to get these times will return the times as unlocalized strings. When viewing these times on the actual web app, the actual times are parsed into local time. The Cycles were saved with times of midnight, which caused the dates to be different (00:00:00 Eastern is 21:00:00 Pacific the day before). This is how the app is expected to function, so Andrew is planning to update his processes to account for this. For now, we're not sure why this is all of a sudden an issue when it wasn't in the past, but I plan on following up after looking through our recent changes again.
2. Regarding the recent changes to the labels list endpoint, Andrew correctly altered his request url to reference the -View models, and I was able to confirm that. Along with this, I'll be following up to distinguish whether the label attribute of 'is_applied' has been changed by any of our recent changes. Specifically, Andrew has understood the 'is_applied' values to be populated by -View IDs, and I'll be following up on whether this is still the case.

> Email 2 - follow up
1. Within the last 2 months, we updated the tool that we use to serialize data being returned in JSON responses. Among one of the updates made to this tool was a bug fix where timezones were being ignored https://www.django-rest-framework.org/community/release-notes/#370 (3rd bullet). Before this update, start times were always converted to UTC which would've pushed your times forward several hours but keeping you in the same day for each entry. I suspect that if you go back to your previous worksheets where you used the Cycle starts, you'd see that times are not 00:00:00, but something more like 05-06:00:00Z. I'd be curious if that's the case but it wouldn't necessarily need to be researched anymore if not.
2. Regarding the 'is_applied' field on labels, your version of SEED does consider the values in that field to be -View IDs. Unfortunately, it's highly likely that this wasn't the case before. Before we moved labels from "canonical" Property/TaxLot (and you used 'property'/'taxlot' in your label API call), you were actually referring to canonical IDs in the "is_applied" as if they were View IDs. It was likely a non-issue for you since as I mentioned in the call, these were typically aligned. Anyway, they are definitely View IDs now and knowing about the old/incorrect set up is probably only useful if you need to troubleshoot past data.

**Comment by RDmitchell** [comment]
@adrian-lara -- thanks for following up with Andrew !
