### ISSUE TITLE
Display geojson map

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#1982]
This ticket is a reminder to enable the display geojson mapping functionality

**Comment by RDmitchell** [comment]
@adrian-lara -- What is this supposed to do? Is it the feature where you click on the WKT field and it shows the footprint (which works)? 

Need to know what to test.

**Comment by adrian-lara** [comment]
This just reveals the map tab for the property inventory. You should be able to click on it and view the map with any geocoded properties pinned.

**Comment by RDmitchell** [comment]
@adrian-lara -- I didn't even notice the Map link at the top (!!)

What does the "Hexagonal bins" represent on the map? 

Also I guess there is no equivalent option on the Tax Lot Inventory List, which I think is fine for now. We can get feedback from users to see if that would be interesting to them, but the ULID checkboxes are on the Property map so that is probably good enough (unless the user has only imported tax lot data for whatever reason). 

This seems to be working, but I am putting a few suggestions into another issue (#2051) for later refinement (not for Dec 2019). 

I will close this
