### ISSUE TITLE
Unable to build docker image - Could not find library geos_c

### ISSUE THREAD

**Issue by paddatrapper** [SEED-platform/seed#2005]
I am currently unable to build a docker image using `docker-compose build`

## Expected Behaviour
The docker image is build successfully

### Actual Behaviour
```
Collecting shapely
  Downloading https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz (225kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-axjb0s1k/shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-instal
l-axjb0s1k/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __
file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-axjb0s1k/shapely/pip-egg-info
         cwd: /tmp/pip-install-axjb0s1k/shapely/
    Complete output (12 lines):
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module> 
      File "/tmp/pip-install-axjb0s1k/shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-install-axjb0s1k/shapely/shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "/tmp/pip-install-axjb0s1k/shapely/shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r requirements/aws.txt' returned a non-zero code: 1
```

### Steps to Reproduce
Run:

```bash
git clone https://github.com/SEED-platform/seed
cd seed
docker-compose build
```

**Comment by nllong** [comment]
Looking into this.




Da: Kyle Robbertze <notifications@github.com>
Risposta: SEED-platform/seed <reply@reply.github.com>
Data: mercoledì novembre 6 2019 03:15
A: SEED-platform/seed <seed@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [SEED-platform/seed] Unable to build docker image - Could not find library geos_c (#2005)


I am currently unable to build a docker image using docker-compose build

Expected Behaviour

The docker image is build successfully

Actual Behaviour

Collecting shapely

  Downloading https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz (225kB)

    ERROR: Command errored out with exit status 1:

     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-axjb0s1k/shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-instal

l-axjb0s1k/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __

file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-axjb0s1k/shapely/pip-egg-info

         cwd: /tmp/pip-install-axjb0s1k/shapely/

    Complete output (12 lines):

    Failed `CDLL(libgeos_c.so.1)`

    Failed `CDLL(libgeos_c.so.1)`

    Failed `CDLL(libgeos_c.so)`

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-install-axjb0s1k/shapely/setup.py", line 80, in <module>

        from shapely._buildcfg import geos_version_string, geos_version, \

      File "/tmp/pip-install-axjb0s1k/shapely/shapely/_buildcfg.py", line 167, in <module>

        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])

      File "/tmp/pip-install-axjb0s1k/shapely/shapely/_buildcfg.py", line 161, in load_dll

        libname, fallbacks or []))

    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r requirements/aws.txt' returned a non-zero code: 1

Steps to Reproduce

Run:

git clone https://github.com/SEED-platform/seed/

cd seed

docker-compose build

**Comment by nllong** [comment]
@paddatrapper can you test the latest on develop?

**Comment by paddatrapper** [comment]
I'll let it build overnight and get back to you. It should be fixed in the next release of Alpine Linux, if my understanding of their release structure is correct. Geos is [currently](https://pkgs.alpinelinux.org/packages?name=*geos*&branch=edge) in the edge repo. Once this is included in a release, it should be able to be included in the `RUN apk` call and have it install correctly.

**Comment by nllong** [comment]
Thanks. Yeah, geos seems to always be in the edge repo for some reason. They'll catch up eventually.

**Comment by paddatrapper** [comment]
Built successfully :tada: thanks
