### ISSUE TITLE
Geocoding confidence values have changed between versions

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2019]
### Expected Behavior
I would have expected the Geocoding Confidence values to be the same between 2.6.0 (on the production server) and 2.6.2 (on the dev1 server)

Maybe something about how those values are created has been updated, but I wanted to record the difference while I am noticing it, and then we can figure out if this is an issue or not. 
### Actual Behavior 
The geocoding confidence for the same data is different between the two releases.

**2.6.2** 
The Geocoding Confidence value is "**Low - check address (Ambiguous)**"
![image](https://user-images.githubusercontent.com/6314950/69592328-74ffce80-0faa-11ea-8db4-92b1e30193ac.png)

**2.6.0**
The Geocoding Confidence value for the same imported file is "**Missing address components (N/A)"
![image](https://user-images.githubusercontent.com/6314950/69592597-3e768380-0fab-11ea-8013-be671fb56f86.png)

### Steps to Reproduce
Import the file 1 - example-data-ESPM.xlsx into each version of the program (see #2018 for that file)
### Instance Information
Instance: dev1
SHA: 6dad9f7

Instance: seedv2 (production)
SHA: df21680
Org: LBNL Test 200

**Comment by adrian-lara** [comment]
I wouldn't consider this an issue - just a difference in versions.

To clarify, the two messages represent two different cases. 

"Low - check address (Ambiguous)" refers to an attempted at geocoding by sending address components to MapQuest. The term "Ambiguous" hints that MapQuest found multiple "valid" addresses/geolocations and SEED couldn't determine which of those were the one you wanted. Although 2264 has fake data, this can happen is a user only provided something that was too vague like "100 Market Street California", which can exist in multiple different cities.

"Missing address components (N/A)" refers to the case where no attempt was even made to send the address components to MapQuest. 
- In 2.6.0, this case happens when there are **less than 3 address components populated**. For the 2264 record, it seems only have 1 component, city, is populated. 
- In 2.6.2, since we enabled custom geocoding columns here, this case happens when there are **no address components populated** (to accommodate for any users using only 1 column to contain a full/geocode-able  address).

**Comment by adrian-lara** [comment]
@RDmitchell Wanted to confirm with you before closing this - do you think the above information is enough to consider this a non-issue?

**Comment by RDmitchell** [comment]
@adrian-lara -- yes this is fine. I am going to assign it to myself and tag it as "documentation"

**Comment by adrian-lara** [comment]
@RDmitchell is this OK to close?

**Comment by RDmitchell** [comment]
sure, closing
