### ISSUE TITLE
Gateway timeout (504) importing a file with 120,000+ records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2079]
### Expected Behavior
Would like to be able to import large files
### Actual Behavior
Large file (122,000+ records, 4 fields) on the staging server got through the import and mapping review, but then timed out in the "Finding inventory matches" section. 
### Steps to Reproduce
See the doc in this folder, along with a file that shows the problem
https://drive.google.com/drive/folders/1rH8tmoVjA09GaSjLu2-k4Z-DBqbGk25m?usp=sharing
### Instance Information
Instance: LBNL staging
SHA: 395db33d

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 58adbb1d2
Org: LBNL Test 200
Cycle: Import Large File

Get a 520 error when trying to get to the Mapping page with the file
![image](https://user-images.githubusercontent.com/6314950/102675952-3ce8a200-4150-11eb-9e3b-8cd78821cb7c.png)

@adrian-lara -- maybe this is an issue with the dev1 setup, and might not be a problem on staging?

**Comment by macintoshpie** [comment]
Thanks Robin, this is technically a slightly different issue than the original issue mentioned here (happening at a different step in the import process). Maybe we could move this conversation to #2515  or #2516 ?

But to answer your question, I don't believe this would be an issue specific to dev1.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong / @macintoshpie -- I guess I don't know how I am supposed to test this since I get a 520 error during the Mapping step, before the program gets to the Mapping Review screen.

**Comment by macintoshpie** [comment]
@RDmitchell are you starting from the beginning (ie uploading the file) rather than trying to remap the file? If you are trying to "remap" the file, then you will probably run into 520's since we currently do something slow on the backend before returning a response (which is why you would see the 520).

I'm attempting to reupload and map the original file myself and will report my results. We will definitely need to fix the `/map/` endpoint soon though to fix this problem.

**Comment by RDmitchell** [comment]
@macintoshpie 

I started over importing the file from scratch. I did it twice with different results. In both cases the import eventually failed, but in different ways.

See this doc
https://docs.google.com/document/d/1NDuoPVlckv5FF1hjCyIBFJrnVzw9wm49XeAVTePj_qM/edit?usp=sharing

**Comment by macintoshpie** [comment]
Hmm this is a bit complicated. It looks like after I uploaded the large file it crashed the database, and it had to reset which messed up your import. This is apparently due to another issue we're running into when importing large files, so maybe we should hold off on testing/closing this issue until we can identify and breakdown the specific issues going on here.

**Comment by RDmitchell** [comment]
@macintoshpie -- maybe move this issue to the next release ?

**Comment by macintoshpie** [comment]
Comment for myself: need to retry this flow and see what happens. I think there have been some changes to the cdn as well as the celery tasks.

**Comment by nllong** [comment]
Merged into the other issue. If this is needed, then create a specific ticket on what needs to be fixed. All "large file" import issues should be tracked in #1498.

**Comment by nllong** [comment]
Merged into the other issue. If this is needed, then create a specific ticket on what needs to be fixed. All "large file" import issues should be tracked in #1498.
