### ISSUE TITLE
Bricr-dev testing for potential merge into develop

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2131]
### Steps to Reproduce
Using the files contained here: https://drive.google.com/drive/folders/1w9d1mX6MxMaZi0fsTP3HX_WItP2G6WCk

- Upload "Monthly Metrics_Sample Data Request Response - 4 Properties" the "Upload a Spreadsheet" button.On the mapping page, use the "Copy Data File Headers..." button but change the first column mapping to "PM Property ID". 
- Upload the "example-pm-monthly-meter-usage.xlsx" using the "Upload Portfolio Manager Meter Usage" button.
- Upload the "buildingsync_v2_0_bricr_workflow.xml" file using "Upload BuildingSync Data" button on the datasets page
- Visit one of the inventory detail pages of the "4 properties" and upload the same BuildingSync file using "Actions" -> "Update with BuildingSync".

Also, after merging PM and BS records both having meters (via inventory list page, check/choose records, "Actions" -> "Merge selected", there may also be issues with how Meters and Meter Readings are being merged.

### Branch Information
`chore/merge-bricr-dev` - `bricr-dev` that's had `develop` merged into it

**Comment by macintoshpie** [comment]
I was able to replicate the bug. In the process I've discovered there are two issues with some of our BuildingSync code:
1. If you only upload the `buildingsync_v2_0_bricr_workflow.xml` file and go to the meters page, you'll see two meters in the table, but 6 meters listed in the filter tab. The issue is due to how we "export" meter usage here: https://github.com/SEED-platform/seed/blob/b80d9a5011fb7f547d8466873d0dd05ea9c0c8f6/seed/utils/meters.py#L105
The `field_names` are not unique for the different meters of the file, as it seems we assume ResourceUse ID to be a unique identifier within the scope of a property.

2. After uploading the `Monthly Metrics_Sample Data Request Response - 4 Properties` and `example-pm-monthly-meter-usage.xlsx`, then uploading the BuildingSync file as a new property. On the properties page, then select one of the properties with meter reading with the buildingsync property. It will fail (currently) b/c buildingsync meter readings don't have the field `conversion_factor` set. If this is changed to default to 1 when importing the file, it you should be able to merge the properties.
But then you'll see that the previously 6 meters for the buildingsync file are reduced to 2 during the merge. This is because the meters are not unique in the way we are selecting them: https://github.com/SEED-platform/seed/blob/b80d9a5011fb7f547d8466873d0dd05ea9c0c8f6/seed/models/properties.py#L107


### Next steps
Figure out if ResourceUse ID is supposed to be unique.
If ResourceUse ID is not guaranteed to be unique, we need to refactor this code.
