### ISSUE TITLE
Update label get_is_applied to support OEP

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#2164]
This method fails at the moment and is needed. Also, write a test!

https://github.com/SEED-platform/seed/blob/34fca03ccbed74f9b17641705c209422f2fa0b68/seed/serializers/labels.py#L50-L56

**Comment by nllong** [comment]
I confirmed that the code is okay, the only issue is lack of test.

**Comment by adrian-lara** [comment]
@nllong Agree with the test being needed. Also, I think it might make sense to not even have an `is_applied` key if the `self.inventory` is falsy  

In these cases, filtering isn't desired, so it's misleading to see `{... is_applied: []}` - seemingly displaying that no record IDs are returned.

I'll write the test and remove the `is_applied` key entirely when filtering isn't resulted then tag you in the PR since I don't expect it would be difficult to implement.

**Comment by adrian-lara** [comment]
@RDmitchell Can you verify that applying and filtering labels on the inventory list page still works for properties and tax lots? I did some manual testing myself when I initially submitted this #2299 and this other PR, #2291 , but it's definitely worth your second pass.

**Comment by RDmitchell** [comment]
@adrian-lara -- this is on dev1, which is the release from yesterday?

**Comment by RDmitchell** [comment]
@adrian-lara -- just doing a few quick tests on dev1, seems like labels and filters are both working on both tax lot and property tabs in the Inventory List view.
