### ISSUE TITLE
Minimum value box not populated if data type is not defined by DATA_TYPES in data quality model

### ISSUE THREAD

**Issue by lainsworth8801** [SEED-platform/seed#2206]
### Expected Behavior
Min box to be populated for user input.

### Actual Behavior
It is not.

### Steps to Reproduce
Create a new rule, select any field ('created', 'updated', 'footprint', 'campus', ...)that has a data type that is NOT defined ('geometry', 'boolean', 'datetime', 'nteger', ...) by DATA_TYPES in models.data_quality.

### Instance Information
<img width="1186" alt="Screen Shot 2020-05-08 at 11 40 55 AM" src="https://user-images.githubusercontent.com/49968203/81433252-80425300-9121-11ea-93f6-1bbba70961f4.png">

Server Instance: `dev1, dev2, production, staging, etc`
Server SHA: `abcd123`

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200

Not sure I understand what this issue is about or how to test it. 

I set this up, ie, Condition = Range, Field = Created, didn't set Data Type, didn't enter Min/Max, and the program allowed me to save that rule.

Should it have? 

![image](https://user-images.githubusercontent.com/6314950/94736629-651aee80-0321-11eb-8f9a-2575f47b0b6b.png)

**Comment by lainsworth8801** [comment]
@RDmitchell Prior to fix, under "minimum" column there wasn't a box for input values (just blank) even with a set condition. The end goal for this test can just be making sure that there is always a box for minimum value for "range" condition.

**Comment by RDmitchell** [comment]
OK, so I guess I will close it ...
