### ISSUE TITLE
API V3 - Measures, building file, and upload

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2253]
Build out the following v2 endpoints into v3, update fields shown in Swagger, and also make changes as listed:

Measures:
- [x] **/api/v2/measures/ - get**: move
- [x] **/api/v2/measures/{id}/ - get**: move
- [x] **/api/v2/measures/reset/ - post**: move

Building File:
- [x] **/api/v2/building_file/ - get**: ~~investigate - search FE - likely deprecate~~ move to /building_files/ (with an "s")
- [x] **/api/v2/building_file/ - post**: move to /building_files/ (with an "s")
- [x] **/api/v2/building_file/{id}/ - get**: ~~investigate - search FE - likely deprecate~~ move to /building_files/ (with an "s")

Upload:
- [x] **/api/v2/upload/ - post**: move
- [x] **/api/v2/upload/create_from_pm_import/ - post**: move

Additionally, review the following:
- [x] use of DRF ViewSets.
- [x] use of decorators is reasonable/
- [x] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by macintoshpie** [comment]
After chatting with Austin, I've decided that we can deprecate `POST /building_file/`. It was previously the entry for uploading a new property from a buildingsync file, but we now use the `POST /upload/` endpoint like all of the other files.

I'm not sure where to note this, but when we come back to make the changes on the front end, we should remove the default buildingsync uploader since it's not used (see here https://github.com/SEED-platform/seed/blob/9e23e67342cf33c156dfe7b8b4983c4b4919b022/seed/static/seed/js/directives/sdUploader.js#L164)
