### ISSUE TITLE
500 error if units are not defined in mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2368]
### Expected Behavior
I thought I could leave the units pulldown blank in mapping for the fields that have that pulldown
### Actual Behavior
Leaving the units blank caused a 500 error
### Steps to Reproduce
* Import a file, in this case an ESPM file called 2 - example-data-ESPM-Alerts-UBID.xlsx
* Set the preset to the "2020-07-26 org-wide mapping snapshot"
![image](https://user-images.githubusercontent.com/6314950/89950865-4cbf0b00-dbdf-11ea-971e-2414ad3e591e.png)
* Two of the fields have a "units" pulldown. They are both blank, and I do not change them
![image](https://user-images.githubusercontent.com/6314950/89951253-ef778980-dbdf-11ea-8db7-09b3b8205367.png)
* This triggers a Sentry error and a 500 error
* However, now, trying to reproduce that error, I can't. The program now goes to the Mapping Review screen without issue.
### Instance Information
instance: seeddemostaging
SHA: 62ee5c4a6
Org: LBNL 200
Cycle: 2020 Compliance Cycle

**Comment by RDmitchell** [comment]
See imported file plus PDF of the Sentry error in this folder
G:\My Drive\SEED Shared Folder\Software Development\Issues\Issue 2368

Direct link to Sentry error PDF
https://drive.google.com/file/d/1N3yTjs0ztm_fYliOWkRly29-IxJcjNKe/view?usp=sharing

**Comment by adrian-lara** [comment]
Thanks for catching this. This was addressed with [this change](https://github.com/SEED-platform/seed/pull/2355/files#r465285014).

For more background, this error happened because there's logic on the backend to deduplicate components of column mappings whenever a field is being mapped to columns with the same name. In most cases, we didn't expect this to happen since once a user maps to a column of name "Gross Floor Area", we won't create a new mapping, we'll just use an old mapping. But since, units were completely dropped from this mapping, SEED didn't recognize the old mapping and tried to create another. After a few steps including deleting the duplicate column mappings components, SEED tries to create a new column mapping and the error-causing code is hit. When you came back to the page and tried mapping again, the duplicates have been deleted at that point so SEED goes down a different logical flow, avoiding that bug.

**Comment by adrian-lara** [comment]
Worth also discussing - I'm not sure that this necessarily has anything to do with leaving empty units. Though I'd vote to disable the "Map Your Data" button when units are empty.

**Comment by adrian-lara** [comment]
This is an edge case where rerunning the same operation after the error results in successful operation. We won't be patching this.

We'll go ahead and disable the button when units are empty as a less urgent fix.
