### ISSUE TITLE
Admin feature to set Time Zone for Time Stamps

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#241]
Currently the software time stamp (such as in Log and Notes) appears to be based on the time zone of the server (?? -- the LBL instance is running on servers in the Pacific time zone, and that is what the time stamp appears to use, no matter where the user is).

Add an Admin function to set the Time Zone for all timestamps, and then the program needs to make that translation when generating the time stamps.

**Comment by nllong** [comment]
Time zone is set in the settings file. The timezone is the same for all data in the database. If there are data spanning multiple time zones in the same organization, then this would start to creep its head as a problem.

**Comment by RDmitchell** [comment]
When you say "timezone is the same for all data in the database" does that mean by organization? 

On the LBNL instance, there are orgs that span multiple time zones. So does each org have the same timezone? In which case, that doesn't really work. So Philadelphia and San Francisco would be set to the same timezone?

**Comment by nllong** [comment]
The data that PA imports is in their local time zone, likewise SF has data in their local timezone. Both of these time-based data are converted to the database's timezone. But the data in each of these organizations have no relative difference.

The issue is when a single organization has data across multiple timezones. In the PA / SF case, if they are in the same org, then viewing time specific queries (which are few), then there is a relative time error.
