### ISSUE TITLE
User can create and kick off an Analysis for an individual property

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2499]
**Is your feature request related to a problem? Please describe.**
This is a new feature.

**Describe the solution you'd like**
As a logged in organization user, 

- when I visit a property detail page and click `Actions` > `Run Analysis`, I see a modal pop up.
- If this property has appropriate meter data, I can create a BSyncr Analysis by filling in information.
    - The record must have 12 months of electricity meter readings data as well as latitude and longitude values. 
- After creating the analysis, I'm redirected to the Analyses page for this individual record.
- On that page, I can click a button that allows me to kick off an analysis.
- Alternatively, I can click a button the on Organization Analyses page to kick off the analsis.

Separately,

- when I visit the Analyses page for an individual property, I see the New Analysis button which can also be used to create a new analysis.
 
**Additional context**

![Screen Shot 2020-12-17 at 10 36 56 AM](https://user-images.githubusercontent.com/30608004/102523238-7cca5f00-4054-11eb-8913-5f9309a13937.png)
![Screen Shot 2020-12-17 at 10 41 45 AM](https://user-images.githubusercontent.com/30608004/102523251-7fc54f80-4054-11eb-8900-a761f772ba9c.png)

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- I have an example file that has both ESPM and GB meter data, but I still get an error when trying to run a BSyncr analysis. 

However, I do see the main options for running an analysis, ie, from the Action menu on the Property Detail screen, or directly from the Analyses menu link on Property Detail, so if that's what this issue is about, then those things are there and seem to be working. 

So maybe this issue can be closed? not sure.

Instance: dev1
SHA: 7c199463a
Org: LBNL Test 200
Cycle: Meter Import Testing

**Comment by RDmitchell** [comment]
Instance: dev1
SHA:
Org: LBNL Test 200

Started an analysis using the Action menu in the Property Detail screen
![image](https://user-images.githubusercontent.com/6314950/105130564-2198eb80-5a9c-11eb-8e0e-48c2da21de19.png)

Can see that analysis listed in the Property Detail Analyses list
![image](https://user-images.githubusercontent.com/6314950/105130648-4725f500-5a9c-11eb-98ca-0533e6fc5ac5.png)
