### ISSUE TITLE
User can view a list of all analyses created for an individual property

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2500]
**Is your feature request related to a problem? Please describe.**

This is a new feature

**Describe the solution you'd like**

As a logged in organization user,

- when I visit a property detail page and click the `Analyses` tab, I see all the analyses run for this property and a few details about each.
- For each analysis entry, I can see the start button if the analysis is ready to be run
- For each analysis entry, the start button is disabled if the analysis is not ready to be run. (Note: for this story, no other buttons need to be visible.)
- For each analysis entry, I see an ID that is a clickable link.
- For each analysis entry, the name is a clickable link.

**Additional context**

- Original mock up:
 <img width="1055" alt="Screen Shot 2020-12-17 at 12 44 10 PM" src="https://user-images.githubusercontent.com/30608004/102535640-b6f02c80-4065-11eb-9b3e-c135f750a8f7.png">

- Latest WIP (maintain the styling implemented here):
<img width="936" alt="Screen Shot 2020-12-17 at 12 44 23 PM" src="https://user-images.githubusercontent.com/30608004/102535725-d9824580-4065-11eb-8b7a-079a41fd4d62.png">

**Comment by macintoshpie** [comment]
Testing the current develop head, c78231761a8a4d303aaa6c53bac73343564cae2f, all requirements are satisfied.

**Comment by RDmitchell** [comment]
@nllong / @adrian-lara -- I have performed a (failed) analysis for a sample record, and can see that in the Analyses screen in the Property Detail screen. So I guess showing the list of analyses is working
![image](https://user-images.githubusercontent.com/6314950/104392428-e5431980-54f6-11eb-9766-8fe25eefbf30.png)

If I click on the Analysis Name, which is a link, I get put into the Organizations / Analyses page, but I can't really tell that because the Analyses link isn't grayed out like it is for the other pages in Organizations when you have landed on them.

![image](https://user-images.githubusercontent.com/6314950/104392620-4ec32800-54f7-11eb-8bd3-b7e6ff3aa386.png)

I guess it only shows the analysis ID that you just came from, but it's a big confusing, because I don't see the other analysis that I did in another cycle. 

Since the analyses list is at the org level, shouldn't it show all the analyses records across the cycles? I did another analyses (failed), Run ID 3, but that doesn't show up in the Org level analyses list.

![image](https://user-images.githubusercontent.com/6314950/104392790-b24d5580-54f7-11eb-925f-7dab40410dad.png)

However, when I click on the Analyses link at the top of the organizations page, then I do see both the runs. 
The UI seems confusing as I can't really tell where I am or the context of where I am

![image](https://user-images.githubusercontent.com/6314950/104392987-2f78ca80-54f8-11eb-93b4-b25463b737dc.png)

But again, I guess the basic functionality of this issue is there, so maybe it can be closed? Not sure.

Instance: dev1
SHA: 7c19946
Org: LBNL Test 200
Cycles: 
* Meter Import Testing 
* 2018 Compliance Cycle

**Comment by RDmitchell** [comment]
instance; dev1
SHA:
Org: LBNL Test 200

Seems to be working
![image](https://user-images.githubusercontent.com/6314950/105130857-a257e780-5a9c-11eb-928f-e13e208517f3.png)
![image](https://user-images.githubusercontent.com/6314950/105130884-b00d6d00-5a9c-11eb-9a0f-417c87a99ce2.png)
