### ISSUE TITLE
Inventory List: Add a column for colors (used to prioritize or otherwise characterize a record)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2513]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
Add a column for colors that could be based on some criteria such as a label, or could be set by hand. 
This would be a good visual way to see the status of a record
Similar to the conditional formatting in Excel, except there would be a separate column (with other icons such as Notes) that could have a color
Add this as an option to set in the DQ check, ie, set the color for cases with errors or without errors, etc. 
You would probably also want to then sort/group/filter by the colors, so that if you had set "red" to "problem" you could see all the records that had this column set to red.

**Describe alternatives you've considered**
n/a

**Additional context**
San Jose has requested this as an easy way to quickly see which are the problem records, particularly because there is no visual way to see the labels without actually doing a filter.

San Jose did a mockup and I will try to get a copy of it to add to this issue. 

As someone who is very visual, I agree that this would be a nice feature.

**Comment by adrian-lara** [comment]
@RDmitchell Following up here. Were you able to track down that mock up?

**Comment by nllong** [comment]
> @RDmitchell Following up here. Were you able to track down that mock up?

@RDmitchell -- were you able to track this down?

**Comment by RDmitchell** [comment]
@nllong -- here is the screenshot from San Jose -- not great resolution but hopefully you will get the drift of what she is thinking about. 

![image](https://user-images.githubusercontent.com/6314950/104370540-e151d000-54d3-11eb-8cfe-d9b38bb30eab.png)

**Comment by Ryoken** [comment]
Suggestion:

* Add a small column to the properties list that displays a color
* Clicking on this cell pulls up a list of discrete colors to chose from
  - a color picker would provide too many options
  -  red, orange, yellow, green, blue, none
* Property list can be sorted and/or filtered based on this color

I recommend utilizing labels for this feature:

* save the color via a formatted label, such as "Color: red"  or "Color: blue"
* labels are already implemented and used to filter
* more labels could be created easily using the same format of "Color: "

**Comment by macintoshpie** [comment]
> San Jose has requested this as an easy way to quickly see which are the problem records, particularly because there is no visual way to see the labels without actually doing a filter.

The problem seems like they want to easily identify properties that have some label, and they don’t want to have to apply a label filter to see that label?

I think using a separate label for "property color", e.g.  "Color: red" ,  is a good idea. But this does add an extra step if they already have meaningful labels (ie filter by existing label, select all, apply new label), and how would we prevent users from applying multiple color labels?

Another approach might be to allow color assignments _to_ labels. Then add some column to the list view which shows all of the labels. The background color of the label "button" thing would be the color they chose. This would look pretty much like GitHub's Issues labels:
<img width="289" alt="Screen Shot 2021-02-03 at 4 28 11 PM" src="https://user-images.githubusercontent.com/18518728/106822712-d1de2680-663c-11eb-91fb-aa9c14e75536.png">

The column would have some fixed width, they would stack up vertically as needed. Or maybe it's only a circle for each label, which expands to display the label name on hover or something to take up less space.

It might even be helpful if you could click on these labels to apply that filter like GH does.

**Comment by adrian-lara** [comment]
It sounds like the most useful and easiest path forward is to expand or modify the current label feature. The most obvious improvement that's already been mentioned would be to somehow display labels as another column in the table.

DQ checks can already auto-apply labels. Labels already have a color associated to them, and those colors can be edited already. (I may be misunderstanding one of the proposed ideas, but I don't know if adding another color dimension there is needed.) If the labels could also appear in the table (in a compact and easy-to-digest way), I think that may set users up to accomplish what they want.

**Comment by Ryoken** [comment]
It would be pretty trivial to make a row or a cell colored based on it's labels as well, with some sort of priority in the instance there are multiple color labels.

**Comment by RDmitchell** [comment]
I think the idea is that something would be added to the DQ settings so that you could set a color for "pass" and another color for "fail", ie, red for fail and green for pass. 

It seems like we need to think about this a bit more before embarking on doing it. 

I should touch base with the user whose idea it was. 

@nllong / @adrian-lara / @axelstudios -- This would be similar to the Pass/Fail that Veronique at Clearly Energy has implemented, so I wonder if we should wait until we get that code merged in to the public SEED repo, and not implement something separately. 

Here is a screen shot from Veronique's presentation this week on the Data Tools call
![image](https://user-images.githubusercontent.com/6314950/106976270-f73a6580-670c-11eb-87b2-413a4eace92e.png)
