### ISSUE TITLE
Progress bar sits on 33% for a very long time so that users think the program has crashed

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2515]
**Describe the bug**
When importing a file, the program's progress bar sits on 33% for a very long time (when mapping the data, which I think is when it is doing matching), to the point that users (including me) think the program has crashed, and they/I cancel the mapping. I think this then potentially causes a 504 error when that import is attempted again (?)

**Expected Behavior**
A progress bar that nicely continued to slowly increment as the mapping / matching is working, so that the user knows that the program is still running

**Actual Behavior**
See describe the bug

**Steps to Reproduce**
Import a file with approx 2000 records into an org that has at least 2 cycles.

**Instance Information**
Instance; LBNL production
SHA: e8d5cde48

**Additional Context**
Several cities have reported this, and I have also experienced this doing testing. 

I think it should have a relatively high priority in the new year

**Comment by adrian-lara** [comment]
### To add more details:
From the UI/UX perspective, the main problem point is when the user clicks `Save Mappings` and hits the `start_system_matching_and_geocoding` endpoint while importing a non-BuildingSync file. Currently, we base the progress bar percentage on the fact that we have 3 main tasks - geocoding, matching-merging-linking, pairing. (We denote 4, but it's really 3.) The 2nd tasks, typically called "matching", can take significantly long.
<img width="658" alt="Screen Shot 2021-01-04 at 6 44 09 PM" src="https://user-images.githubusercontent.com/30608004/103591082-1e5b0880-4ebd-11eb-86c0-0be91ef9920a.png">
<img width="658" alt="Screen Shot 2021-01-04 at 6 44 46 PM" src="https://user-images.githubusercontent.com/30608004/103591087-20bd6280-4ebd-11eb-9ed0-c8eb1306526c.png">
<img width="658" alt="Screen Shot 2021-01-04 at 6 45 06 PM" src="https://user-images.githubusercontent.com/30608004/103591093-231fbc80-4ebd-11eb-8dba-6c985cf7505d.png">

**Comment by adrian-lara** [comment]
### Solution Option
@nllong @axelstudios @macintoshpie @Ryoken Let me know what you all think about the following. TL;DR: We keep 3 main steps, but we share more granular steps during the longest step, matching, where it looks like things are stuck at 33%.

From an implementation perspective, providing a truly accurate status based on records processed isn't as straightforward because the records are "processed" 3 times. In that sense, our current progress updating is technically accurate. A possible solution approach could be to refactor the matching task to provide more granular increments just within that longest step, matching. 

I'm envisioning that we'd see a large step for geocoding just as before (maybe smaller than 33%? maybe 0% to 20-25%?), then we'd see the bar slowly increase all the way up to the last large step, pairing which would be another larger step (80% to 100%?). 

More research would need to be done exactly how we'd want to implement this, but we could potentially base those more granular increments mostly on the 3rd _sub-step_ in matching called `states_to_views`, as that goes an iterative logic on each incoming record.

**Comment by macintoshpie** [comment]
I agree it looks like we need to update the progress data inside of `match_and_link_incoming_properties_and_taxlots`. Ideally we could update progress data inside of all of the subtasks in that function (granularity of the update is also up for decision), but would need to do some research to determine feasibility.

An alternative option is to trick the user into thinking its still updating when really it's not. Essentially we could progress the rendered progress bar (ie only on the frontend) on some interval by some percent (probably non-linear up to some expected percent where it would actually stop and wait for it to actually reach or pass that point). I don't know much about this type of UI, but I think it would fall under "optimistic UI/UX".

**Comment by RDmitchell** [comment]
@macintoshpie / @adrian-lara -- 2.9.1 still takes a long time to import files, but the progress bar (even if it is faking the user out) does make progress in intervals. 

So should this be closed?

**Comment by nllong** [comment]
I think we need to still have better communication with the user about the status of the background tasks. I suggest we leave this open unless there is another ticket that discusses updating the progress bar.

**Comment by macintoshpie** [comment]
I agree, I would like to add more granularity to the progress bar. #2560 is helpful, but isn't a perfect solution

**Comment by RDmitchell** [comment]
Instance; Dev 1
SHA: 

The program is now showing 2 progress bars, which seems better. 
![image](https://user-images.githubusercontent.com/6314950/153965452-778fc824-3cd8-4fa8-8230-b0c57e5743b1.png)
