### ISSUE TITLE
Indication of unmatched records in Building List

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#27]
Users wants some indicator in Buildings List and Building Detail page for which data is still not matched to PM (or other) data. Should go the other way too. Automated assignment of labels indicating that PM records have not been matched.

**Comment by RDmitchell** [comment]
Come up with simple UI ideas that indicate backend implications that need to be investigated.

**Comment by danielmcquillen** [comment]
So there are probably two issues here:

1. Update the dynamic text in the filter to make sense given the current state of the filter
2. Add dynamic text on number of current buildings to the right of filter selector

For 1, currently the footer shows unmatched in parenthesis, regardless of the state of the filter, e.g. "Showing 1 to 5 of 5 buildings (7 unmatched)," which is slightly confusing. 

![image](https://cloud.githubusercontent.com/assets/119496/8399105/d2af29f6-1e49-11e5-84cf-c31369dffb77.png)

Perhaps this footer label should be updated in the following way...

When "Show All" is selected, no change to the current footer:
**Showing [x] to [y] of [total] buildings (z unmatched)**
example: *Showing 1 to 10 of 12 buildings (7 unmatched)*

When "Show Unmatched" is selected:
**Showing [x] to [y] of [total_unmatched] unmatched buildings**
example: *Showing 1 to 5 of 5 unmatched buildings*

When "Show Matched" is selected:
**Showing [x] to [y] of [total_matched] matched buildings** 
example: *Showing 1 to 7 of 7 matched buildings*

For those last two we could also try including something to indicate total buildings available in the db:
example: *Showing 1 to 7 of 7 matched buildings (15 total in the database)*

But that last one might be overkill since 1) we'd need extra text like "in the database" to make things clear and 2) a user who just selected the filter knows what they did so perhaps they don't need to be reminded they're only viewing a subset.

However we want to handle the bottom text will influence what to do in the header. Perhaps you no longer think anything is necessary given the above suggestions. But if you do, we could do something simple like just report the number shown and total, given the filter...

![image](https://cloud.githubusercontent.com/assets/119496/8399070/213034b8-1e49-11e5-89af-bc89728fbbb6.png)

These changes should be relatively simple since I think the different quantity values for matched and unmatched are already available locally via the controller, so once we decide on it I can make the update pretty quickly.

**Comment by RDmitchell** [comment]
May want to do this through adding multiple labels to a building record, so that unmatched records could be "labeled" automatically by the program, or manually by the user, in the Building List.

**Comment by RDmitchell** [comment]
@danielmcquillen -- we may not need this since @nicholasserra is adding the matched / unmatched functionality to the Building List. Should I shelve this issue for now (or just close it) ?

**Comment by RDmitchell** [comment]
I am closing this since we now have matched and unmatched records pulldown in the building list.
