### ISSUE TITLE
Update fields that are saved into PropertyState from BETTER analysis building results

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2778]
First decide what these fields are.

**Comment by macintoshpie** [comment]
@nllong could you take a look at the choices above and let me know what you think? PR #2775 pulls out "Potential Cost Savings" and "Potential Energy Savings".

**Comment by nllong** [comment]
Trying to figure out the best way to mark this up:

https://gist.github.com/nllong/880ee0af2aea3e0e5f355d12f3a7e53d#file-better-json-L21-L35 -- We will eventually want these to be measures that are part of the property, however, that would mean that a property could now have multiple sets of Measures, which is definitely not the case at the moment or we would have to warn the user that assigned measures will be overwritten. We would also need to map from these to BSync measures. 

Add https://gist.github.com/nllong/880ee0af2aea3e0e5f355d12f3a7e53d#file-better-json-L113

Maybe want [this](https://gist.github.com/nllong/880ee0af2aea3e0e5f355d12f3a7e53d#file-better-json-L4) in order to assess how good the model is. It seems like this is the worst model, right?
