### ISSUE TITLE
Bug: check meters tab on spreadsheet is broken

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2810]
## context
We added a function to check if there's a meters tab after a file is imported to prompt a user to import the meters as well.

## bug
It doesn't work. E.g. I upload a BSync file and it asks if I want to import meters

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 405

I have seen inconsistent results for this for ESPM XLSX files with meter tabs; probably to do with how the spreadsheet it set up. 

Sometimes SEED figures out there is meter data and asks if you want to import it, but sometimes it doesn't. 

I think I will move this to the 12/31/2021 project, and assign it to me, so that I can try to figure out when it works and when it doesn't.

**Comment by macintoshpie** [comment]
@RDmitchell thanks, sounds like we do have some tweaking to do. I agree that moving it to the new project board is best. I'll also tag myself on this to make sure it doesn't slip through the cracks.

**Comment by RDmitchell** [comment]
@macintoshpie -- I observed this today, ie, I waited a few seconds and then the "Import Meters" option appeared when importing an ESPM file that had meters in it. 

I have recorded a video that shows this -- you can see the behavior at 3:47 minutes in.
Issue 2913.wmv: https://drive.google.com/drive/folders/1N2e7I2hm487hqnA6kTOgcPMbCPmwue8b?usp=sharing

**Comment by macintoshpie** [comment]
I think I'm going to close this ticket if that's ok with you @RDmitchell , the original bug has been fixed.
I created this ticket to track the bad UX for a button showing up late: #2978

**Comment by RDmitchell** [comment]
@macintoshpie -- sure that's fine !!
