### ISSUE TITLE
Can't make project 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#282]
On the production server, can't make a project from the building list. I get this error.

XMLHttpRequest cannot load javascript:void(0);. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.send @ jquery.min.js:2

Claudine, can you verify this problem, and add any knowledge to you gain to this issue?

**Comment by RDmitchell** [comment]
Trying again, and it seems to be working now, but it is VERY slow. Maybe I just didn't wait long enough, and the error above isn't related to the issue. 

Claudine, if you could still do some testing on making projects that would be useful.

**Comment by cycustodio** [comment]
I can't recreate the issue in any version of seed. 

I looked up the error message and it happens when a page / file (in this case "javascript:void();") can't be found in the webserver. I'm guessing there was an action that tried to load another page which didn't exist yet. 

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void

**Comment by RDmitchell** [comment]
I will close this since we can't reproduce it. But it is troublesome to have this happen.
