### ISSUE TITLE
Add Navigation tools (first, next, previous, last) to Building Detail view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#29]
In the Building List Detail screen, it would be nice to have the standard set of record  navigation tools, such as first record, next record, previous record and last record.

**Comment by RDmitchell** [comment]
Add these navigation buttons (currently on the Building List view)
![image](https://cloud.githubusercontent.com/assets/6314950/11833390/fed6d01c-a376-11e5-87c0-dec3a8a25cca.png)
to the Building Detail View
![image](https://cloud.githubusercontent.com/assets/6314950/11833401/1996a8aa-a377-11e5-856a-c41cdd3fd7bd.png)

**Comment by adrian-lara** [comment]
After discussions, since there does not exist an underlying, static order between inventory records, there isn't viable path to implementing this. Otherwise said, though you can temporarily sort records on the inventory list pages, there isn't any actual way to be able to decide what record should be "next" when on any particular record detail page.

**Comment by RDmitchell** [comment]
@adrian-lara -- I understand the problem, but it's too bad !! Oh well, thanks for looking into it !!
