### ISSUE TITLE
Add server-side filtering for derived columns

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3043]
TODO: decide if we want to do this (probably not)

**Comment by macintoshpie** [comment]
If we do decide we need to be able to do this, here are some thoughts:
- derived column values are not stored - they are dynamically calculated, which means they'd need to evaluated on _all_ properties that make it through the other filters (i.e. after applying non-derived column filters) during the request. This would probably blow away any benefits of pagination
- we might be able to improve performance by caching the result in Redis, The key would probably be `<derived column expression>:<property state hash/SHA>`, and the value would be the result of the calculation

**Comment by nllong** [comment]
@perryr16  / @Ryoken  -- has this been resolved already?

**Comment by perryr16** [comment]
No, this has not been resolved. Ted's first point is still relevant as derived columns are dynamically calculated and not stored making the filtering process time consuming

**Comment by haneslinger** [comment]
It's worth noting that derived columns can't be returned through property state api because of how they are seralized. [this line](https://github.com/SEED-platform/seed/blob/fb1396c338b6c3e0debe82e78635dd29b80ee6a1/seed/models/tax_lot_properties.py#L84) which iterates over columns to be returned doesn't included derived columns. We could rewrite it to, and include derived column evaluatation in that function, but it would be slow without optimization.

**Comment by haneslinger** [comment]
duped [here](https://github.com/SEED-platform/seed/issues/3438) with more info

**Comment by RDmitchell** [comment]
@isalanglois -- I don't think this issue should be closed. I guess #3438 needs to be fixed before this will be possible, but we should leave this issue open so we can come back to it when 3438 is implemented. 

Derived fields are key to the BPS implementation we are recommending to users, so they need to be able filter and sort on derived fields.
