### ISSUE TITLE
Add canonical GHG fields

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3174]
For BPS we need to promote GHG fields to canonical fields in the SEED database.

Add the following:
```
Total GHG Emissions (MtCO2e/year)
Total Marginal GHG Emissions (MtCO2e/year)
Total GHG Emissions Intensity (kgCO2e/ft2/year and kgCO2e/m2/year)
Total Marginal GHG Emissions Intensity (kgCO2e/ft2/year and kgCO2e/m2/year)
```

We should make these Pint/Unit aware.

Second step will be to update the carbon analysis to save the results into the correct fields (see #3175).

**Comment by RDmitchell** [comment]
@nllong -- here is what we now have -- 3 different CO2 emissions from 3 different sources (not sure what the source would be for the new canonical fields -- presumably the CO2 calculation?)

This seems very confusing to me, and potentially to the users. Seems like we need a way to distinguish between them with a slightly different naming convention. Should the new fields be called "SEED calculated Total GHG ..." or something like that, so that someone wouldn't populate those fields with ESPM fields for the same data, for example? 

![image](https://user-images.githubusercontent.com/6314950/171737010-4397b2fc-43da-41af-b527-446dec46cf6a.png)

**Comment by RDmitchell** [comment]
@nllong -- for the new canonical fields, where are the units defined / displayed? We don't have a place for them in Column Settings, although that does seem like the right place to define them
![image](https://user-images.githubusercontent.com/6314950/171737945-fbafa699-5774-4c17-90e9-243532f2246e.png)

**Comment by RDmitchell** [comment]
Units are displayed in the Analysis section
![image](https://user-images.githubusercontent.com/6314950/171738716-eec642e0-f481-4b35-9c55-1db5b5d2987c.png)

But not for the fields in Property List View
![image](https://user-images.githubusercontent.com/6314950/171739108-7fced353-d1a0-4431-8379-a4a2aa8d6e1d.png)

In the Property Detail view, there are no units displayed and the values for the same thing, ie, Total GHG Emissions, are in different units within the same page display
![image](https://user-images.githubusercontent.com/6314950/171739739-34072992-d223-4b81-bee5-168aec25fcd7.png)

**Comment by RDmitchell** [comment]
@nllong -- I think this needs more work

**Comment by Ryoken** [comment]
I'll do my best to address every question!

Column List Profile
- The red columns are added to the property state, can come from any source and have dynamic units.
- I am not sure where the green ones are coming from as I do not have them on my own server, my guess is they were created on importing ESPM data as you suggested.  If distinction is required, should that happen at import when the user is naming the columns?
- The blue columns come from BETTER with hard-coded units, and as such are labeled on both fronts

Column Settings
- The units indeed are not showing up here, as they are PINT unit aware.  The units are defined/interpreted when the property is uploaded and when the data is requested.  The other columns show units because they are hard coded by hand.  I made a ticket to discuss/change this: https://github.com/SEED-platform/seed/issues/3301

Analysis Results
- The result "Average Annual CO2 (kgCO2e)" is hard coded, so the value is always in kgCO2e
- The intensity is being saved to the property state, so it should probably be added to the analysis results as well.  New ticket created: https://github.com/SEED-platform/seed/issues/3300

Analysis Highlight Card
- This value is pulled from the Analysis Results "Average Annual CO2 (kgCO2e)", which has hard coded units, so it will always be kgCO2e

Property List and Details
- I think units should show up somewhere.  Created ticket: https://github.com/SEED-platform/seed/issues/3299

**Comment by RDmitchell** [comment]
@Ryoken -- thanks !!

**Comment by nllong** [comment]
I think that we still need to do a bit more work on getting the units working right on BETTER and GHG fields. Can we close this and reference (or create) new tickets? @RDmitchell

**Comment by RDmitchell** [comment]
Sure -- I will close the issue
