### ISSUE TITLE
ESPM Data Import Path

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3199]
ESPM provides two ways to generate buidling data:

**Download My Portfolio**
- currently imports via "Upload a Spreadsheet" with no issues
- works if the program participants “share their property” with you in ESPM

**Data Request**
- imports via "Upload a Spreadsheet" with "Import Meter from the Same File" resulting in anonymous errors
- some file manipulation allows importing meters, but data is restricted based on meter types and does funny stuff (see request below)
- imports via "Import Portfolio Manager Data" result in no meters or errors.

Users would like to be able to import properties and meters using the "Data Request" path.  These changes are requested:
- provide a more detailed error when importing meters so users know what to do
- "This is where I’m not sure if we can upload a file that has more than just the Elec and Gas meter – and we would like to be able to upload multiple meters, including district heating energy, propane, etc."
- "Also, if we are just uploading Elec and Nat Gas, the elec meter gets named “Electric – Unknown – PM – Unknown” and gas gets named “Natural Gas – PM – Unknown”.

Contact: Open Tech

**Comment by Ryoken** [comment]
After some initiial work and investigation, here is the work committed to in this ticket:

 - We currently only look for the key strings "gas use" and "electricity use" when trying to detect the headers... make this more robust and support importing more energy types, such as Oil and Deisel
- Once imported, meter readings are labeled as such: "Meter type - Meter Source - Meter Source ID"... clarify what this is doing both by changing the text and by adding a small info note on this page to describe what's happening.
- Some values being imported are being displayed as none instead of 0.  Display none if no values are present, otherwise 0 is a provided value and should be displayed.

**Comment by RDmitchell** [comment]
@Ryoken / @nllong -- how should I test this in the UI?

**Comment by Ryoken** [comment]
@RDmitchell There are some testing instructions and a test file in the ticket here: https://github.com/SEED-platform/seed/pull/3240

**Comment by nllong** [comment]
this is working as expected. Merging now. @RDmitchell  -- feel free to reopen or create derivative tickets as needed.
