### ISSUE TITLE
Unable to create labels in suborg

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3289]
Create a sub org and try to create a label using the UI.

**Comment by nllong** [comment]
Marking as p-1 to keep it from becoming stable.

**Comment by RDmitchell** [comment]
I will test on the latest dev solution

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: f9558b8bb
Org LBNL 101 SubOrg2
RM+20

It is possible to add labels to data in a sub org, but the labels are not showing up in the List View, at least for the Tax Lot tab
Jurisdiction Tax lot ID: 10102/5B193 has a label, as seen in the detail view (added in List view)
![image](https://user-images.githubusercontent.com/6314950/197083517-ea97672f-4d14-4766-b23d-c425f9bb8a4a.png)
But in the list view, you can't display the labels
![image](https://user-images.githubusercontent.com/6314950/197083681-790d6bc2-1f5f-4283-ab85-7a072f8e148c.png)

The same is true for the Property Tab List View
This record has a label
![image](https://user-images.githubusercontent.com/6314950/197084032-634d7c18-800d-47e8-8693-2bf4fd75bfc4.png)

But it doesn't appear in the List View
![image](https://user-images.githubusercontent.com/6314950/197084172-f1984f89-208d-4dcd-8a63-4deb31629164.png)

**Comment by RDmitchell** [comment]
The reason why the labels aren't showing up in the List View is because I didn't specify "Show in List", which is set in Org/Labels.
![image](https://user-images.githubusercontent.com/6314950/197255167-4f474339-408b-4d7d-bf25-f35a8f7fc6d8.png)

When I go to the Org/Labels view for the suborg (LBNL 101 SubOrg 2) I don't see any labels. 
![image](https://user-images.githubusercontent.com/6314950/197255114-c5e4f0ef-7c4e-44ad-a0f5-7f84d65ad0b4.png)

But in the Property List View for that Suborg, I am able to add labels "on the fly"
![image](https://user-images.githubusercontent.com/6314950/197255719-048ae46f-6459-4d0b-a72e-0d3490fcdeb8.png)
![image](https://user-images.githubusercontent.com/6314950/197255617-b09a6d56-4739-405b-b802-128aaa24e5fd.png)

**Comment by RDmitchell** [comment]
When I try to create a label "on the fly" from the Property List, when I click the Done button, I get a 500 error
![image](https://user-images.githubusercontent.com/6314950/197262254-083de29a-4954-4dca-8011-cfd032bb464d.png)

**Comment by anchapin** [comment]
I'm seeing the issue on my end also where you can't create a new label from the suborg, however, I did notice that when I assign a label to a suborg property that was set as "Show in List" in the parent org, then I can see it in the Inventory List.

The question I have then is whether we want users of the suborg to be able to create and edit labels? Additionally, would we want the labels and the label settings, such as "Show in List" toggle, to sync between the org and suborg or be unique? This type of situation will need to get vetted prior to or during the upcoming account hierarchy tasks.

**Comment by nllong** [comment]
@anchapin  that is exactly the right question. I suggest we add this discussion to the accountability hierarchy discussion, that is, where do labels live within a hierarchy? How does that impact hierarchical aggregations? Adding in @haneslinger too.

**Comment by RDmitchell** [comment]
@haneslinger -- I think your proposal makes sense. I don't think anyone is using sub-orgs, and as you say, we will be completely refactoring that functionality for the accountability heirarchy.

So I do think it makes sense to close this issue. I will do that.
