### ISSUE TITLE
New PM to SEED Mapping file 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#329]
SEED currently uses a BEDES mapping file to fill in the mapped fields for Portfolio Manager files. The BEDES mapping file is really something that should be used on the back end to make a "BEDES compliant" export file, a functionality which we current don't have but might in the future. 

The behavior we want in the Mapping screen for Portfolio Manager fields is to use most of the actual Portfolio Manager field names as SEED field names, with a few exceptions. The exceptions are to name the fields such that the data for those fields will get stored in a real field in the BuildingSnapshot table rather than in the extra_data JSON field in that same table.

I have generated a list of the SEED mapping to a Portfolio Manager file, which has those very few specific mappings. The rest of the fields will be the actual PM field names. 

Here is a link to that spreadsheet:
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LdDRJVzdQeHBVN2s/view?usp=sharing

* Column A is the new SEED mapping list
* Column B is the Portfolio Manager field name
* Column C is the BEDES mapping to the PM file, which we will keep around for future use, but not use now.

![image](https://cloud.githubusercontent.com/assets/6314950/9343956/2049a618-45ba-11e5-8af0-ba478b600bd4.png)

Also, for this iteration (the August release) we will not deal with migrating data that is already in the database with the old BEDES mapping. We will tackle that in Sept or later, as there are not many cities that have data in the LBL instance and they may not need to be migrated anyway. We will come up with a robust migration scheme, that might be implemented as a backend utility, as this will be somewhat of a one-time migration that isn't needed into the future. Stephen can add his thoughts about how to do a robust migration after this first functionality is implemented.

**Comment by StephenCzarnecki** [comment]
Pull request here: https://github.com/SEED-platform/seed/pull/338

**Comment by RDmitchell** [comment]
I don't quite understand how the program is doing the mapping. This PM file is odd because it has underscores where spaces would normally be in the PM field names. For most of the cases, the program is substituting a space for the underscore but not everywhere. Here is an screen shot showing what the program is doing. 

![image](https://cloud.githubusercontent.com/assets/6314950/9420687/34f663f2-481d-11e5-81c6-964186f3a4a6.png)

The SEED fields with the underscores are in the PM SEED mapping file
![image](https://cloud.githubusercontent.com/assets/6314950/9420695/5a9af622-481d-11e5-96f1-1cd5111292d3.png)

![image](https://cloud.githubusercontent.com/assets/6314950/9420702/76c80434-481d-11e5-8982-c82c2cbf0723.png)

![image](https://cloud.githubusercontent.com/assets/6314950/9420711/977034f4-481d-11e5-9858-6b2141ecc2b1.png)

**Comment by RDmitchell** [comment]
The file that you can use to see this is in 
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LOU9UOFJsLXBxTVU&usp=sharing

**Comment by StephenCzarnecki** [comment]
When I try that file on my development machine I do not get the underscores:

![image](https://cloud.githubusercontent.com/assets/7605407/9450706/0c442e14-4a5f-11e5-8948-fb5767a8b5b8.png)


I'll around a bit more and see why you might be seeing them.

**Comment by RDmitchell** [comment]
interesting. I wonder if the program was remembering earlier mapping that I was doing. I will test with a completely virgin account, ie, no history of previous mappings.

**Comment by StephenCzarnecki** [comment]
Here’s what I think is going on.

The suggested mappings are based on a call to get_column_matching_suggestions.  This returns three things:

A suggested_mappings dictionary that looks like

"suggested_mappings"	 
	u'Address_1' (139636723948736)	<type 'tuple'>: (u'Address Line 1', 100)	
	u'Address_2' (139636723929856)	<type 'tuple'>: (u'Address Line 2', 100)	
	u'Adult_Education_-_Gross_Floor_Area_(ft2)' (139636723877136)	<type 'tuple'>: (u'Adult_Education_-_Gross_Floor_Area_(ft2)', 0)	
etc…

A building_columns list that looks like
"building_columns"	 (pending)	
	000	str: address_line_1	
	001	str: address_line_2	
	002	str: block_number	
etc..

And a building_column_types dict that looks like 
"column_types"	 (pending)	
	'address_line_1' (139636767795440)	dict: {'unit_type': 'string', 'schema': 'BEDES'}	
	'address_line_2' (139636767393080)	dict: {'unit_type': 'string', 'schema': 'BEDES'}	
	'block_number' (139636767392744)	dict: {'unit_type': 'string', 'schema': 'BEDES'}	
etc…

The building_columns is the key it seems.  It is a combination of records in the “Column” table in the database and the fields returned from the get_mappable_types function(just the fields of interest in the BuildingSnapshot table).  The saved field names in the columns table seems to be the issue but in order to see why I need to jump to the javascript code.

In mapping_controller.js there is a bit of code that responds to the result of the call to get_column_matching_suggestions on the server.  It first takes the building_columns list from above and uses that for the typeahead columns.  Then it iterates through the list of suggested mappings and if it is **not** in the typeahead column list (building_columns from the server) then it does the bit to remove underscores and change the capitalization to title case.  However, in the case you are seeing I would bet there is a value with the underscores in the Column table from a previous mapping and that is being used.

For example, when I started with a clean database I saw no underscores.  But if I import the file as a csv and change the mapping on a field (I chose Parent Property Name) to have the underscores then save the mapping the next time I import as a PM file it suggests the underscore version:

![image](https://cloud.githubusercontent.com/assets/7605407/9456127/8a12ea1e-4a88-11e5-833d-d862b6cd0bd2.png)


I’m not 100% on the above so if anything doesn’t sound quite right let me know about it or if you have any other questions.

**Comment by RDmitchell** [comment]
After mapping a file (the test file for this issue, uploaded as a Portfolio Manager file), saving the mapping, and then going back to look at the mapping (click the Data Mapping button), only the fields that have a direct mapping in the new PM file show up in the SEED Header column. 

Here is the mapping before it is saved.
![image](https://cloud.githubusercontent.com/assets/6314950/9476562/2b04011c-4b22-11e5-9b5c-254d0b932b3a.png)

Save the mapping, then go to the Data Files and click on the Data Mapping button
![image](https://cloud.githubusercontent.com/assets/6314950/9476602/5cb2a39e-4b22-11e5-859f-1eb6f06811dd.png)

This is what is displayed -- it should be displaying all the mapped values on the left hand side.
![image](https://cloud.githubusercontent.com/assets/6314950/9476490/d4fa1fae-4b21-11e5-8646-28c709eb8dcd.png)

**Comment by RDmitchell** [comment]
See issue # 170 also in your queue. Presumably the same issue?

**Comment by StephenCzarnecki** [comment]
OK looking into it.

**Comment by StephenCzarnecki** [comment]
Still looking into it but think I found the reason it is different from the initial mapping screen.  In mapping_controller.js there is some bit that has a comment saying "if mapping is finished, don't show suggestions" with a bit of code that says

if ($scope.import_file.matching_done && that.confidence < 100) {
                      that.suggestion = "";
 }

Which is saying if the matching is done and the confidence is less than 100 then the suggestion should be blank.  

Then in another piece of mapping_controller there is a bit that sets a flag saying if it is a mapped row or not by checking to see if the suggestion is blank.  This flag is then used in the table layout to determine if it is enabled or not.  The reason why it is blank is that is that it is using this same "suggestion" field to populate the text of the input field and since the suggestion is blank so is the text.

To test I changed the server code for the PM files to always report a 100% match and that seems to get the review mapping screen back to normal:

![image](https://cloud.githubusercontent.com/assets/7605407/9482949/cc012fa0-4b4e-11e5-9795-801fcd28dba1.png)


This is not a fix but at least I think I've narrowed down the places to look.  I'll try to get a real fix tomorrow.  But just to confirm:  The "MAP" and "SEED HEADER" fields seem like they should be disabled for already-matched buildings.  So the things that need to be fixed are A:  The lack of text in the SEED HEADER textbox and B:  the grey color of the text.

**Comment by RDmitchell** [comment]
I think this goes back to the issue that the program uses fuzzy logic (?) to match field names in the mapping step, hence the confidence criteria. I think we decided a while ago that the fuzzy logic for mapping makes no sense by we may not want to make that change at this late date when getting ready to put this into the next release. 

And yes, at this point, the fields are disabled after mapping is saved (which means matching is also done), ie, the user can't change the mapping after the records have been matched. 

And yes, we need to do your A and B in your last sentence. If there is a way to do it with a bit of a hack now (ie set confidence to 100% which I believe is what Dan Gunter did back when he was working on this).

Then in the refactoring phase (Oct/Nov) I think we should disable the fuzzy logic in the field matching suggestions in mapping. Maybe there aren't any suggestions in the SEED field when the Mapping screen first opens. A workflow / design issue to ponder.

**Comment by StephenCzarnecki** [comment]
Pull request here:  https://github.com/SEED-platform/seed/pull/347

**Comment by RDmitchell** [comment]
This looks good. The underscores are gone from the problem fields, and when I go back to look at the saved mappings, I see all the fields, with the appropriate checkmarks. I am closing this issue.

Thanks Stephen
