### ISSUE TITLE
fix of duplicate BETTER GHG Fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3325]
**Describe the bug**

For orgs that did BETTER analysis before a certain time, extra data fields were created for the GHG data. We then added those fields as canonical fields, so now it is possible to get duplicate fields, which causes the org to be inaccessible. 

Need to identify the orgs that this is an issue for, and delete the extra data fields (on the server, not through the UI)

Orgs that I know about: JCC, LBNL 405

If possible, it would be good to make a list of orgs to clean up, as not all orgs using BETTER need this to happen (if they just started doing BETTER analysis, for example)

here are the duplicate fields
![image](https://user-images.githubusercontent.com/6314950/175103358-dce99f0e-1ea3-41a7-b684-5863f810319c.png)

**Instance Information**

Instance: production
SHA: 6ffea0837

**Comment by nllong** [comment]
Here are my notes to fix this on dev for the `SEED (Demo)` org.

![image](https://user-images.githubusercontent.com/1907354/175406101-cd558c04-3e59-4ceb-adc7-d9f749c88745.png)

With error:
```
web File "/seed/./seed/models/columns.py", line 1444, in retrieve_all
web raise Exception("Duplicate name '{}' found in columns".format(c['name']))
web Exception: Duplicate name 'better_ghg_reductions_combined_79925' found in columns
```

```
select organization_id, orgs_organization.name, column_name, seed_column.id, is_extra_data, seed_column.created from seed_column
inner join orgs_organization on seed_column.organization_id = orgs_organization.id
where seed_column.column_name LIKE '%better_ghg%'
order by organization_id, created
```

Look for duplicates. If there are duplicates in the column_name, then find the column_descriptions that have kgCO2e (these are the old units), then get the column_id (my computer uses the period as the 1000 separator), so in the case below, 79925, 79932, 79933.

![image](https://user-images.githubusercontent.com/1907354/175406152-fb699446-60df-46b9-93d3-bff4b2336034.png)

![image](https://user-images.githubusercontent.com/1907354/175406172-edecafdf-f4f1-4bbc-aad9-52c38d46677b.png)

If the delete errs due to column profiles, then grab and delete those records as well.

![image](https://user-images.githubusercontent.com/1907354/175406197-e133d156-f8a5-403d-a06f-254222a24eb0.png)

Also look for total_ghg_* items. They may be shown as extra_data fields and exist in the column_mapped table, and will need to be removed too.

```
select organization_id, orgs_organization.name, column_name, seed_column.column_description, seed_column.id, is_extra_data, seed_column.created from seed_column
inner join orgs_organization on seed_column.organization_id = orgs_organization.id
where seed_column.column_name LIKE '%total_ghg%' and is_extra_data 
order by organization_id, created
```

**Comment by RDmitchell** [comment]
@nllong -- so is the plan to delete these fields manually? 

Let me know when that happens, and I will do more testing on the JCC org. 

Thx !!

**Comment by nllong** [comment]
@RDmitchell  - can you confirm the server instances and the orgs that are seeing this issue? I see LBNL 405 on dev1. Not sure where JCC is... thanks!

**Comment by nllong** [comment]
No easy way to test the problem org until it is deployed. Closing as it fixed dev1 and we can reopen if needed.
