### ISSUE TITLE
Cloudflare error when loading Sensor data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3327]
**Describe the bug**

When loading some sensor data into SEED, the program produces a CloudFlare error. It is not possible to recover from that -- the Sensor page can no longer be displayed and the inventory record must be deleted (and then potentially you have to start over trying to load sensor data).

**Expected Behavior**

Should be able to load sensor data without a CloudFlare happening, and most of the time it seems to work properly.

**Actual Behavior**
![image](https://user-images.githubusercontent.com/6314950/175423435-a44fe439-eb00-4484-83c8-d177964ec826.png)

**Steps to Reproduce**

I will try to come up with a reproducible set of steps to see this error. Not sure if I will succeed

**Instance Information**

Instance: Dev1
SHA: 5f181142b

**Comment by RDmitchell** [comment]
I think this might have to do with how much data has been loaded into the Sensor tables, because it doesn't seem to be tied to a particular sensor data file.

**Comment by RDmitchell** [comment]
Here is a link to a movie showing the problem. It happens on import of the 3rd set of data
https://drive.google.com/file/d/1JnPV9N9MhKuKvrccjO5xqyInIv3E25gG/view?usp=sharing

**Comment by RDmitchell** [comment]
This folder has all the files needed to work on this issue
https://drive.google.com/drive/folders/1JkMP-dlXG_vy7Sx58e8BU7C9RjSl5y2O?usp=sharing

**Comment by axelstudios** [comment]
@RDmitchell @haneslinger 
The issue is that once you have a certain number of sensor readings uploaded, the  `/api/v3/properties/3211746/sensor_usage/` endpoint can take longer than 60 seconds to return, and CloudFlare immediately terminates the request if it takes longer than that.  We need to decide if we actually want to show all data at once on that page, or if we want to take an approach similar to the Inventory List Beta page with pagination to reduce the amount of data being transferred:

### After uploading Grade 2 (125,789 readings):
The `sensor_usage` endpoint takes 35 seconds, and transfers 34MB of uncompressed data

### After subsequently uploading Grade 1 (68,026 readings):
The `sensor_usage` endpoint takes 57 seconds, and transfers 52MB of uncompressed data

### After subsequently uploading Grade 3 (67,425 readings):
_**The `sensor_usage` endpoint takes at least 60 seconds before CloudFlare terminates the request, making the page permanently broken until the property itself is deleted**_

## Additional bugs
- The Cycle name is not properly shown when uploading sensor readings
![2022-06-24_093520](https://user-images.githubusercontent.com/411466/175576312-96403925-8df3-4c75-913e-e6a201cc66c2.png)
- A spinner needs to be shown until all background requests have finished (like when you dismiss a dialog and it reloads the data).  Currently when you refresh the page it appears blank for 35-57 seconds until the data has finished loading
- Adding a data logger causes the page to do a full refresh, it should ideally only query the updated data loggers
- Form validation has bugs:
![image](https://user-images.githubusercontent.com/411466/175577135-71391324-d0b1-41c3-a1d7-e42fd0e36d6c.png)

**Comment by RDmitchell** [comment]
@axelstudios / @haneslinger -- I don't think we need to show all the actual meter data at once, particularly in it's current form, where the columns become so small that you can't even read the header names.

**Comment by RDmitchell** [comment]
I guess for the demo / final report, I will try importing just the smaller files. It would be nice to figure out a solution for this soon. 

Thanks

**Comment by RDmitchell** [comment]
@axelstudios / @haneslinger -- just wondering if there has been any progress on this. The BIE project is fine for now, but it would be good to address this issue at some rate. 

Thanks!

**Comment by RDmitchell** [comment]
@haneslinger -- great ! Thx !!

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 449f54dcf

This appears to be fixed. I was able to upload all 11 sensor data files for BIE. Thx !!
