### ISSUE TITLE
Average Annual CO2 display name has extra characters

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#3452]
**Describe the bug**
After running a CO2 analysis an `analysis_co2` extra data column is generated. The created display name is: `('Average Annual CO2 (kgCO2e)',)`

**Expected Behavior**

the display name should be `Average Annual CO2 (kgCO2e)`

**Steps to Reproduce**
1. import property spreadsheet with meters (ex:  ESPM_JCC_Custom_Download_BETTERTest.xlsx)
2. update eGRID Subregion Code (ex: "AZNM"
3. run a CO2 analysis 
4. go to Column List Profiles and check "Average Annual CO2"

<img width="737" alt="Screen Shot 2022-08-11 at 12 31 48 PM" src="https://user-images.githubusercontent.com/58446472/184213498-814d8602-8b94-44aa-bef4-4879dedbb7ef.png">

**Comment by RDmitchell** [comment]
I would think this issue still needs to be fixed.

**Comment by RDmitchell** [comment]
I will test this to see if it is still an issue, but if no one has worked on it I suspect it is.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 4b8753257

This is still an issue

![Image](https://user-images.githubusercontent.com/6314950/207770581-8cd8f62a-327e-4143-afee-b49e2d9c0a01.png)

**Comment by RDmitchell** [comment]
@isalanglois -- because this is still a problem, I moved it into the In Progress column but feel free to put it somewhere else as appropriate. Thx

**Comment by isalanglois** [comment]
@RDmitchell Are you working on this ticket or does it need to be reassigned?

**Comment by RDmitchell** [comment]
I verified it is still happening, so I guess it needs to be assigned to someone to work on.

**Comment by isalanglois** [comment]
@RDmitchell  any updates on this ticket?

**Comment by RDmitchell** [comment]
It doesn't seem like anyone has worked on it, so I don't see why it would be fixed. 

Do you need me to test it again? I'll put it in the test column, but if it is still a problem I will put it back in the To Do column

**Comment by RDmitchell** [comment]
Not sure why it was in the "in Progress" column, since I don't think anyone was working on it.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 

This is still an issue -- no one has worked on it.
![image](https://user-images.githubusercontent.com/6314950/230681080-d047e18d-4422-4e75-9b7b-365a5ba95b73.png)

Am moving it to To Do

**Comment by RDmitchell** [comment]
@kflemin -- The results are being generated, but I can't seem to select these values from the Property List view to display them.
![image](https://github.com/SEED-platform/seed/assets/6314950/a6dc1e18-e6ae-442b-acdf-851afae12a0a)

**Comment by perryr16** [comment]
I am only able to recreate this issue on dev-1, not locally

localhost
![Screenshot 2024-01-03 at 3 08 21 PM](https://github.com/SEED-platform/seed/assets/58446472/b480afc4-086b-4250-9e64-2c7ffab866d0)

dev1
![Screenshot 2024-01-03 at 3 10 07 PM](https://github.com/SEED-platform/seed/assets/58446472/31a6e9b0-fe2e-40bd-a87c-fc4297ad5124)

**Comment by haneslinger** [comment]
Elizabeth fixed this [here](https://github.com/SEED-platform/seed/pull/4410). However her fix will only apply to column creation going forward, is doesn't go back and correct columns. I can exec into the dbs and fix column name if you want. I just need the instance, org, and column names.

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- should @haneslinger fix existing data on the LBNL production instance? Not sure very many orgs (besides my test orgs) have this problem, so it might not be worth the effort.

**Comment by RDmitchell** [comment]
@haneslinger / @nllong / @axelstudios -- could we not set issues to done until they have been deployed to a dev server and tested by me? 

I am going to change the status from Done to Test.

**Comment by RDmitchell** [comment]
But I need to know whether the fix has been deployed, etc.

**Comment by RDmitchell** [comment]
@perryr16 -- I assume this has been deployed to dev1, since it is in test. 

Instance: dev1
SHA: 
Org: LBNL 200
Cycle: CO2 Analysis Testing

None of the data in that cycle had meter data, which is needed for the CO2 analysis. 

So I imported meter data for 2 of the records
![image](https://github.com/SEED-platform/seed/assets/6314950/e904aced-d1b0-4c1e-a74a-592fb3507d95)

I then did a CO2 analysis on those 2 records, which was successful for both records
![image](https://github.com/SEED-platform/seed/assets/6314950/dfda05d6-0870-4675-a907-e7aa0a1b4217)
![image](https://github.com/SEED-platform/seed/assets/6314950/cc3db827-febb-4098-bf5f-fc47dd6d284c)

And the results appear in the Detail view for those properties
![image](https://github.com/SEED-platform/seed/assets/6314950/75783b93-a5cb-4b0f-8852-3757fe75d9cd)

However, the newly fixed "Average Annual CO2 (kgCO2e)" field doesn't exist in the fields for that record, and only the old field "(;Average Annual CO2 (kgCO2e)',)" exists
![image](https://github.com/SEED-platform/seed/assets/6314950/b4d62478-e81a-4148-bfec-1c6755bdf9c0)
![image](https://github.com/SEED-platform/seed/assets/6314950/aa99be4f-d245-4f84-a91c-845b4d31d500)

I thought maybe I needed to delete the old field before redoing the analysis, and I thought I could do it in Column Settings, which should show all the fields, but the Average CO2 field isn't there. 
![image](https://github.com/SEED-platform/seed/assets/6314950/79e57945-eda0-4832-b1c5-e406f8bc2b02)

Maybe I am doing something wrong, but I can't figure out how to get the newly fixed field to appear and be filled with the appropriate data. 

Also, it seems like we might want to do some sort of data migration on existing data to fix the old field name?

**Comment by RDmitchell** [comment]
@perryr16 / @haneslinger -- has this fix been deployed to dev1 for testing?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: d5d60eaac
Org: LBNL 245

Instance: dev2
SHA: d30082bbc
Org: LBNL 245

The labels are now correct
![Image](https://github.com/SEED-platform/seed/assets/6314950/926f2147-bf1f-40ad-a221-3d4f9e5eb8d1)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL 245

I am confused about what is being calculated and displayed from the CO2 analysis

Here is a result from an analysis -- it displays results for "Average Annual CO2 (kfCO2e): 30075"
![image](https://github.com/SEED-platform/seed/assets/6314950/1417902e-4e86-478c-8ce0-b3a157eb9ca3)

When I click on the Property link (which is the internal DB ID, which it shouldn't be, since the user doesn't know what that means) I see these results
* The "card" shows the same results as the Analyses screen, ie, 30,075 kgC02e for Average Annual CO2
* But the data in the list of fields has "Total GHG Emissions" set to "30.07" without any units. This looks suspiciously like the value for Average Annual C02 with different units, but I don't know if it is (I think it shouldn't be?)
* Annual Annual CO2 value is still missing
![image](https://github.com/SEED-platform/seed/assets/6314950/e2b1b85b-aef1-4fc2-a48b-2bdcbe6bf464)

**Comment by RDmitchell** [comment]
@kflemin -- I assigned this to myself to test, and it looks like it is still broken. 

I am adding a "testing question" label to it, but I think it should probably go back to the "To Do" pile. But you should probably do that, rather than me.

**Comment by RDmitchell** [comment]
Here is another example in that same org showing the same thing
![Image](https://github.com/SEED-platform/seed/assets/6314950/ab2203ce-df2f-4a29-b040-a1676addf3fc)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 3.0.0-beta.0.d60822140
Org: LBNL Test 200
Cycle: CO2 Analysis Testing
Column List Profile: CO2 testing

In this org, with an old analysis, I am still seeing the old (wrong) field name -- does there need to be a migration or something to change this old field name to the correct field name? 
![Image](https://github.com/SEED-platform/seed/assets/6314950/4f411b60-ad84-4ab0-90e2-a60cb5ddc94f)

**Comment by RDmitchell** [comment]
And it shows up in the list view also
![Image](https://github.com/SEED-platform/seed/assets/6314950/3236439b-48cc-414d-a09a-1cea18afba25)

**Comment by RDmitchell** [comment]
See also #3707

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 77b9e4afa
Org: BPS - DC
Cycle: 2023

This appears to be fixed when you do a new CO2 calculation -- in this case, a CO2 calculation had not been performed on any records in this org, as far as I can tell 

The fields are properly formed in both the Column List Profile and the Inventory List
![Image](https://github.com/SEED-platform/seed/assets/6314950/8b426131-ef6d-4b89-8955-cddb2e591ed5)
![Image](https://github.com/SEED-platform/seed/assets/6314950/92d640d7-9b92-4df3-8104-e4c43b2321e8)

There might be issues with records that had previously done a CO2 analysis and have these fields already in their "world", but I will look into that and make another issue if that is the case. So I am closing this one.
