### ISSUE TITLE
Enable filtering of columns that appear in both inventory types

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3499]
For example, the "Address Line 1" column for Properties can't be filtered in the Tax Lot version of Inventory List.

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/3515

**Comment by RDmitchell** [comment]
Issue #3426 is also about cross Inventory Filtering / Sorting.

**Comment by RDmitchell** [comment]
instance: staging
SHA: bb2fdd425
Org: LBNL Test 200

Was able to filter on an Tax Lot field in the Property List tab.

However, when I tried to add a label to those filtered records, I got several 500 errors
![image](https://user-images.githubusercontent.com/6314950/205788241-7b4b8e07-8740-4a50-89e6-1aadce533d12.png)

**Comment by RDmitchell** [comment]
the filter worked using text, ie, filtering on Parcel Owner == Lucky University
![image](https://user-images.githubusercontent.com/6314950/205789067-cd9574d6-c480-4bd1-a0f0-f17e0caf8abe.png)

However, it didn't seem to work when I filtered on the Jurisdiction Tax Lot ID for the case where there were multiple tax lot IDs associated with a record
![image](https://user-images.githubusercontent.com/6314950/205789471-4333bd91-aa48-42b4-9d38-70d6223e02f3.png)
But it doesn't seem to work even if there is only one Tax Lot ID associated with a record
![image](https://user-images.githubusercontent.com/6314950/205789751-d5a0da3a-a632-422a-9808-879da4cbcc86.png)
But it did work filtering with a number on the address field
![image](https://user-images.githubusercontent.com/6314950/205789968-b1573fbc-bfe4-44a6-aac1-c849ddff5563.png)

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: 294626cbd
Org: LBNL Test 200
Cycle: 2020 Compliance Cycle

**Filtering for blank values in a Tax Lot field -- Does not work**
In this example, there are 14 records in the cycle. 
2 of them do not have a value in the Jurisdiction Tax Lot ID column
![image](https://user-images.githubusercontent.com/6314950/211952520-db80cab4-09bf-489c-9d37-265a55dad853.png)

If I filter for the records with the Tax Lot field blank, ie, enter "" in the filter field, no records are returned. But the two records with that field blank should be returned
![image](https://user-images.githubusercontent.com/6314950/211952817-09f89838-dc0a-422b-9505-98ca89e0f5c3.png)

This same style of filter, ie, "" to show blanks, works for Property fields
![image](https://user-images.githubusercontent.com/6314950/211953167-fb3bb110-fff8-4ba9-be67-3824920a89cd.png)

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: https://github.com/SEED-platform/seed/commit/294626cbdbdd7c89dd14f2f85f17e633ed8e4367
Org: LBNL Test 200
Cycle: 2020 Compliance Cycle

**Can't filter on ; in Tax Lot field in Property Tab**
in the Legacy Property List, if you filter on ; for Jurisdiction Tax Lot ID, it returns the 5 records that have a semicolon
![image](https://user-images.githubusercontent.com/6314950/211955013-c4dec06d-75de-41fb-9c7b-0deb49c25579.png)

In the new Property List, doing that same filter results in 0 records
![image](https://user-images.githubusercontent.com/6314950/211955242-80fe1b95-0630-4303-a4a5-186ad309a1b7.png)

**Comment by RDmitchell** [comment]
@anchapin / @haneslinger -- I think it might be good to write several tests for this type of filtering. 

Here is what the SEED Getting Started guide says about what can be filtered
![image](https://user-images.githubusercontent.com/6314950/211955843-df9cf239-36da-4d33-9b98-b6cb5557fd7a.png)

Seems like there should be a standard set of tests that do all these filters to make sure we have this functionality on fields from the same tab (ie, Property or Tax Lot) for fields on the opposite tab (ie, Tax Lot field in the Property tab and vice versa).

**Comment by RDmitchell** [comment]
Filtering on Tax Lot columns that appear in the Property Tab still needs a lot of work. 

I am putting this back in the "In Progress" column, as it is not completely fixed.

**Comment by haneslinger** [comment]
Filtering on "" was broken for all columns. [Reported here](https://github.com/SEED-platform/seed/issues/3600). [Fixed here](https://github.com/SEED-platform/seed/pull/3733). Not yet released. Moving this to "Ready to deploy

**Comment by RDmitchell** [comment]
@haneslinger -- great, thanks !!

**Comment by RDmitchell** [comment]
@haneslinger -- what about filtering on semicolon, ;

That also seems broken

**Comment by RDmitchell** [comment]
and possibly other punctuation?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 26aac34d8
Org: LBNL Test 200
Cycle: 2018 Compliance

@anchapin -- should I put filtering in specific instances that aren't working in a separate issue? 

For example, here is a field from Tax Lot, in the Property List view
![Image](https://user-images.githubusercontent.com/6314950/216732454-83162607-f02a-40c6-8b0e-59361544842e.png)

There are 7 records without a value in that field
![Image](https://user-images.githubusercontent.com/6314950/216732544-b3fc4811-653c-4190-aa08-4fefedd58510.png)

If I filter using "" to see the blank records, the program returns one record that is not blank instead of 7 records that are blank.
![Image](https://user-images.githubusercontent.com/6314950/216732644-a2807655-09f3-460a-9b70-bbc1c90d5588.png)

**Comment by haneslinger** [comment]
I was trying to recreate locally. 

At first I was able to recreate. After some investigation I realized it wasn't working because there was no `PropertyTaxLot`s linking the properties and taxlots - which is crucial to this functionality. I was shocked because I didn't realize you _could_ have related properties and taxlots without `ProperyTaxLot`s.

I cleared the db and tried to figure out how I got it in that state to begin with, but I couldn't manage to import related properties and taxlots with the codebase also creating `PropertyTaxlot`s, and consequently, the bug disappearing.  

@nllong- Can properties somehow have a taxlot column without a related `PropertyTaxlot` or taxlot? Do we have any reason to believethis orgs property/taxlot/PropertyTaxlot relationships are atypical?

**Comment by RDmitchell** [comment]
Instance: staging
SHA: 666c8f302
Org: LBNL Test 200
Cycle: 2018 Compliance Cycle

* Property tab: 
  * Can filter on a tax lot field, ie, Address, and then add labels to those records without errors
  * Can filter on  Jurisdiction Tax Lot for a value that has multiple instances within a record without errors
  * Filtering on Jurisdiction Tax Lot ID for "" (blank) or !"" (not blank) fields **DOES NOT WORK** -- will make a new issue
  * Filtering on PM Property ID (property field) for for "" (blank) or !"" (not blank) fields does work
  * Filtering on ; (semicolon) in Jurisdiction Tax Lot ID (to see records with multiple tax lots) returns no records, when it should return 3 
  * Filtering on Tax Lot field Parcel Owner Telephone for "" results in 0 records instead of 4
  *

**Comment by RDmitchell** [comment]
@isalanglois / @nllong -- should I make a new issues for 2023 with the things that still aren't working for this feature, add it to the Q3 project, then close this one (and I could reference it from the new one)?

**Comment by RDmitchell** [comment]
I have moved the "DOES NOT WORK" issues from the end of this issue into a new issue for the Q3 project #3986
