### ISSUE TITLE
[9/26/22] Create Presentation for Harry on SEED Visualizations

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3517]

**Comment by RDmitchell** [comment]
Will this presentation be made at one of the SEED group meetings? If possible, I would be interested in seeing the presentation, particularly since I've been out (and am technically still out until at least the end of Sept), and haven't kept up as well as I would like one this aspect of SEED. Thanks!

**Comment by isalanglois** [comment]
@RDmitchell This presentation will not be at one of the regular SEED meetings, but we will be having a demo of new features (some of the work you may have missed while recovering) at our iteration meeting this week. Clearly Energy will also be present for this Thursday's iteration meeting.
