### ISSUE TITLE
Revise the error checks to ensure that the actual column is also selected if the target column is selected.

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3573]

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 294626cbd
Org: BPS Test

@anchapin -- when I tried to save a Program with only the Target field defined, I get an error message saying the actual energy or emissions columns must be include.

Does that mean this issue is fixed and can be closed? 

![image](https://user-images.githubusercontent.com/6314950/211436971-6503b978-959f-4d31-abd1-e1aa8cdbb446.png)

**Comment by anchapin** [comment]
@RDmitchell yes, that's the intended result for this issue.
