### ISSUE TITLE
Add ability to export column mapping profile to CSV

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3610]
**Is your feature request related to a problem? Please describe.**

The [py-seed project](https://github.com/SEED-platform/py-seed) has the ability to create a column mapping profile from a CSV file. Doing this by hand can be error-prone due to having to match the names as they are in SEED. The CSV file format should look like [this](https://github.com/SEED-platform/py-seed/blob/develop/tests/data/test-seed-data-mappings.csv).

**Describe the solution you'd like**

Add the ability to export the mapping profile to CSV. Eventually, it would be nice to be able to import a mapping profile from the same CSV... but that can be for another day.

**Comment by RDmitchell** [comment]
@nllong -- is this something that can be done through the UI? If yes, where?

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: City of San Francisco

I went to the Org/Column Mappings link and clicked the Export to CSV icon
https://docs.google.com/spreadsheets/d/1w8xUM6XF6qfz1o-ghH8D5u1MwjaD1mqO/edit?usp=share_link&ouid=103887815394604824348&rtpof=true&sd=true

The file was exported, but looking at it, not all the fields are included, probably because of limitations of Excel
The file stops on line 869 of the spreadsheet, with the field "Retail Store - Open of Closed Refrigeration ..."
![image](https://user-images.githubusercontent.com/6314950/207973937-8c1a5a7f-18a0-4740-ade7-9be061bef77e.png)

However, looking at the column mapping screen in SEED for that org, there are many more fields under Retail Store
![image](https://user-images.githubusercontent.com/6314950/207974270-242c4402-1807-40bc-a84d-8c23e13ff769.png)

And the fields end with Zoo
![image](https://user-images.githubusercontent.com/6314950/207974303-0b111fdf-599c-43a6-96e9-2ca260197c96.png)

Any user with ESPM data will likely have this many fields, as they are the standard "full" set of ESPM fields. 

So we need to figure out a way to accommodate them, either by making 2 files, etc.

**Comment by RDmitchell** [comment]
@isalanglois -- this needs to go back into "in progress" to deal with the problem I found. Thx

**Comment by isalanglois** [comment]
@RDmitchell  thanks for the update, tagging @nllong since it looks like he was working on it before

**Comment by nllong** [comment]
@RDmitchell  - the file linked above is to Potential TAC Partners.

**Comment by RDmitchell** [comment]
@nllong -- how bizarre -- I just deleted it !!

**Comment by nllong** [comment]
I think I just fixed this issue. All the data were there, just not sorted the same way as the UI. It will be on develop after we merge the PR.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 7a529191a
Release: 2.17.1

@nllong -- this seems like kind of an odd combination of a bunch of different views of the data that the user has. I think it needs some work -- I will open a new issue to refine it. 

It's a combo of Column Settings and Column Properties, but not quite all of each. 

![image](https://user-images.githubusercontent.com/6314950/215218316-f7f208f2-577c-4e0c-be7b-e8467a4fe3ba.png)
