### ISSUE TITLE
Add ability for create, update, and delete to meters

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3638]
Phase 1 -- move the `meters` endpoint as a nested route under properties.

**Comment by RDmitchell** [comment]
instance: staging
SHA: bb2fdd425
Org: LBNL Test 200
Cycle: Meter Import Testing

Under meters, the Filter Meters pulldown doesn't display the meters and no data is displayed for the meters that exist
![image](https://user-images.githubusercontent.com/6314950/205785060-2fef2c42-0515-4fea-820c-32dcabc74144.png)

on Production, before this update to delete meters, the Filter Meter pulldown is displayed, and there is data associated with the meters (same org and cycle in both cases).
![image](https://user-images.githubusercontent.com/6314950/205785253-5c10ba6f-3c0f-4d9d-923c-13cdaaea407b.png)

**Comment by RDmitchell** [comment]
I think the records are not displayed because I am clicking on the Filter Meters button and can't select anything, so maybe it defaults to no meters selected. 

If I come to the meter data for a record by clicking on the lightning bolt icon in the Inventory List view, then I see the data
![Image](https://user-images.githubusercontent.com/6314950/205785897-67ff9309-8b37-4b36-82a3-424c2e9d1c70.png)


If I then click twice on the Filter Meters button, the data for the meters disappears.
![Image](https://user-images.githubusercontent.com/6314950/205785958-0f299045-9a48-40d5-833c-fefb14342129.png)

**Comment by RDmitchell** [comment]
@nllong -- I think this needs to go back to "In Progress".
