### ISSUE TITLE
Fix issue when both energy and emission metrics are included with Program

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3697]
[traceback.txt](https://github.com/SEED-platform/seed/files/10228172/traceback.txt)

The issue appears to be with the property_response line of models/compliance_metrics.py. I was able to quickly get the Program Overview page to work by adding an if statement to check whether the metric has an actual_emission_column and adding ".id" to the end of the actual and target emission columns (which would only be included if emission column exists), but I couldn't get the Property Insights page to work.

Therefore, I'm creating this ticket hoping someone else can help me with this.

I've attached the traceback file from Chrome dev tools. It seems to be around line 1778 that it gets to the affected code sections.

**Comment by RDmitchell** [comment]
@anchapin -- should this be closed? 

I am going to reopen it and put it into the Q2 project as it has to do with BPS.

**Comment by RDmitchell** [comment]
Hmm. Looks like it was fixed, so I guess I will try testing ???

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 294626cbd

I could define both an energy and an emission metric in Programs. 
![image](https://user-images.githubusercontent.com/6314950/211125167-06c34073-1bd8-4e46-8fe1-a7cd153e8ce8.png)

Is that what this issue was about?

**Comment by RDmitchell** [comment]
I will look at the original issue to see how to test this.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: BPS Test

@anchapin -- I added GHG targets and a derived column for GHG Delta, and then defined both Energy and Emissions metrics in the Program Configuration.

![image](https://user-images.githubusercontent.com/6314950/211127274-a78cc243-2d38-41fd-921c-a06efececa91.png)

I only did this for cycle 2020

Looking at the data, none of the GHG emissions are less than the target, so none of them comply
![image](https://user-images.githubusercontent.com/6314950/211127318-e5d8c137-a760-4150-b7b6-9ad1a15f0259.png)

For the EUI data, most of them comply with only 2 not complying
![image](https://user-images.githubusercontent.com/6314950/211127355-63cd6003-4eb8-4d0a-b170-996cf19577ea.png)

When I go to the Insights / Program Overview page, this is what I see ... I guess I don't understand how to distinguish between the Emissions and GHG compliance in this view ... ?

I only defined both of them for 2020, so I guess that's why the graph is showing only 2020? But it seems like the graph should distinguish between energy and emissions? Maybe 2 different columns next to each other for each cycle? 

The program is showing that all 9 properties are not complying -- so that says to me that it is showing the GHG compliance but not the energy metric compliance. 

![image](https://user-images.githubusercontent.com/6314950/211127397-2a0ea36e-a0cb-4a75-9a49-401f90c6eca4.png)

Am I missing something in how I'm defining things?

**Comment by anchapin** [comment]
@RDmitchell the way programs are setup at the moment is that if you define both an energy and emissions metric for a program then a property is only compliant if it satisfies both targets. Therefore, in your example none of the properties comply with program compliance since they all have GHG actual greater than GHG target. This is how I understood that the process should work.

Although, now that you brought it up, it does seem like it would be helpful for the Program Overview to show you compliance by metric and overall compliance in the chart. I'm not sure what the best way would be to visualize all three things at once that is easy to follow though. Let me know what you think or what you were expecting.

**Comment by RDmitchell** [comment]
@anchapin -- I see. I guess it makes sense that both targets would have to be compliant. 

It might be helpful to see the breakdown, but I would say we should probably get user feedback about whether that is useful and if it is, how to show it. 

So for now, the current implementation makes sense. I just need to document it. 

I guess one thing to add is some sort of information about the fact that they both have to be in compliance, maybe on this page? 

I will do a bit more testing, but I suspect this is good to go and I can close it today. 

Thanks !!

**Comment by RDmitchell** [comment]
I have defined 3 different programs, and they all seem to be reporting correctly in the overview screen. I will set this to done
![image](https://user-images.githubusercontent.com/6314950/211406489-a3dc3d47-a97a-4ced-ae70-93730411d285.png)
