### ISSUE TITLE
Insights: Can we change Program Setup to Insights Setup?

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3753]
Instance: dev1
SHA: 92acc007d
Org: BPS Test

I think it's confusing that setting up the Insights world is done via Program Setup in Orgs

Can we change the name in Orgs to "Insight Setup" ?

**Comment by RDmitchell** [comment]
I'm trying to write up how Insights works, and it's confusing to say that Insights are set up in the Program Setup. 

Program to me means SEED, ie, SEED is the Program

**Comment by RDmitchell** [comment]
Also, the actual page to configure the Program says Configuration not Setup
![image](https://user-images.githubusercontent.com/6314950/213016131-0a51d979-a296-4d96-99bf-23e4df290665.png)

Seems like we should use the same nomenclature everywhere.

**Comment by anchapin** [comment]
@RDmitchell sorry for the delay. I'm open to changing the name of "Property Insights" but I think that the page in the organization settings section should stay "Program Setup" since that is where you setup or create your programs. Additionally, maybe it's less confusing if the "Property Insights" page configuration settings are located on a different page from the "Program Setup". I think we mostly put them together because they were being developed at the same time and we thought that the main use case for the "Property Insights" page would be for finding insights for your properties in the context of administering a Program.

I can change the "Program Setup" page to use Program Setup instead of Program Configuration.

**Comment by RDmitchell** [comment]
@anchapin -- probably before you make any changes we might want to have a design meeting about the Insights page and setting things up. Because there is also the "Data" link on the Inventory page. 

When I was trying to write all this up for the release notes, I found it very hard to articulate the relationship between all these options. 

I was thinking I might try to put together a workflow diagram and that might help me understand how things work and also might shed some light on how to make it easier for the user to understand what to do. 

So I would say hold off on making any changes at this point.

**Comment by anchapin** [comment]
Sounds good. I'll make a new issue for changing "Program Configuration" to "Program Setup" since that's an easy fix and makes sense to do. Then I'll hold off on the rest of it.

**Comment by RDmitchell** [comment]
sounds good, thanks

**Comment by RDmitchell** [comment]
Instance: seeddemostaging
SHA: 666c8f302

This is fixed ! THanks
