### ISSUE TITLE
Matching address with abbrev street type and direction

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#378]
This was discovered in issue (https://github.com/SEED-platform/seed/issues/315). The case is for ```Peach Ave. East``` and ```Peach Avenue E```, both should be normalized to ```peach avenue east``` so they match. 

![address_unmatched](https://cloud.githubusercontent.com/assets/8461331/9857811/b87dee7c-5ad1-11e5-979c-82f6e276a011.png)

**Comment by nicholasserra** [comment]
Reassigning to Piper so he can get acquainted with the BE

**Comment by pipermerriam** [comment]
This ticket says that the following should both map to `peach avenue east`

- `Peach Ave. East`
- `Peach Avenue E.`

The current address normalization behavior behaves as follows.

- Things like `Street, Avenue, Boulevard` are mapped to their shorthand versions, `st, ave, blvd`.
- Compass directions (`North, South, East West, North`) are mapped to their single letter shorthand, `N, S, E, W`.

Assuming we want to fix the issue in this ticket so that the two addresses above are normalized to the same value, as well as preserving the current behavior of the mapping, then I would like to suggest changing the acceptance criteria of this issue to the following.

The above addresses should both be mapped to `peach ave e` instead of `peach avenue east`.

@RDmitchell  Is this acceptable?

**Comment by nicholasserra** [comment]
That should be correct ^

**Comment by RDmitchell** [comment]
Yes that seems fine

**Comment by cycustodio** [comment]
Thanks for catching that Piper. Both should match, ```peach ave e```.

**Comment by pipermerriam** [comment]
The fix for this is ready for review in #380

**Comment by RDmitchell** [comment]
Claudine -- can you please test this -- the PR for it was merged yesterday. Thx

**Comment by cycustodio** [comment]
It's fixed. Thanks, @pipermerriam.
