### ISSUE TITLE
Add help text to the EUI Analysis Modal

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3826]
I am proposing a few tweaks to the Analysis / EUI calculation

**Naming convention**
It is named differently in different places, and seems like those names should be consistent.
* It seems like it is basically Site EUI because it is calculated from meter readings
* In the detail view of the analysis calculation, it is called "Fractional EUI"
![Image](https://user-images.githubusercontent.com/6314950/216726136-c58afc80-2348-4cb3-994d-aae3625fb88d.png)
* in the Inventory / Detail view, it is called "BPS EUI Based on Meters" -- why add the "BPS" at the beginning? Users may use it for other things besides BPS
![image](https://user-images.githubusercontent.com/6314950/216727163-9bf431a4-3084-4151-827e-3db15d6a9979.png)
* Could we call it something like
  * "Site EUI calculated from meters" ?? 
  * Or something shorter but still descriptive?

**Make the resulting EUI a field**
* Seems like it should be a field (presumably extra data? or maybe a canonical field with units?) -- I don't think it is currently stored as a field but correct me if I'm wrong. 
* this would allow users to see it in the Inventory List view, and perform all the normal functions of fields (derived columns, sorting, filtering, etc)
* We would need to make sure the field name does not conflict with the existing Site EUI field that is coming, generally, from Portfolio Manager.

**Comment by anchapin** [comment]
Regarding the naming convention, I believe that it is called "Fractional EUI" because it may not have been calculated with a full 365 days of meter data, hence why there is an "Annual Coverage %" also. However, in the case that "Annual Coverage %" is equal to 100% then "Fractional EUI" is just EUI.

Additionally, the name that shows up at the top of the analysis card ("BPS EUI Based on Meters" in your example) comes from the user when the EUI Analysis is created.

I wasn't around when this feature was created, but to me calling it "Calculated EUI" seems better since calling it "Fractional EUI" and also having "Annual Coverage %" seems slightly redundant. It is also shorter than "Site EUI calculated from meters".

The resulting EUI value is a field. Additionally, the annual coverage % is also a field. Refer to the image below for an example.

![image](https://user-images.githubusercontent.com/6326294/217073937-5e9cc042-2b95-4118-a691-a03e3cdb770f.png)

**Comment by RDmitchell** [comment]
@anchapin -- thanks for the explanation. So it does seems like "Calculated" might be better than "Fractional", but then it seems we should keep the "EUI Coverage" value also. 

I guess if the EUI Coverage is based on the number of days of meter data, could we somehow add that to the name? 

EUI Meter Data Coverage   ???

Or maybe add something in the parenthesis to explain that it is meter data that is being used for the calculation? 

As a user who didn't know what these fields meant, I'm just trying to make the fields meaningful for the uninitiated. 

But then again there is only so much we can do !!

**Comment by anchapin** [comment]
@RDmitchell, I just created a new ticket and linked it to this one. It handles changing from "Fractional EUI" to "Calculated EUI". I separated it out since it is a bigger effort. However, I will attempt to add help text to the EUI Analysis modal to address the other aspects of this issue.

**Comment by RDmitchell** [comment]
sounds good.

**Comment by anchapin** [comment]
I'm going to close this in lieu of #3839 since it seems like the main changes involve revising the column names that are generated.
