### ISSUE TITLE
Data Cleansing -- List of fields to check for missing values

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#385]
I have added a list of fields to the Data Cleansing spec (section 2) from the Building Snapshot table that should be checked for missing values
https://docs.google.com/a/lbl.gov/document/d/19zYiXdeVnk9eVhGcVhyfdr3CZnkYLfI558LEfOM8GL0/edit?usp=sharing

**Comment by RDmitchell** [comment]
Nick -- is this done? Can we close this issue?

**Comment by RDmitchell** [comment]
Please test this

**Comment by bravacheLBL** [comment]
I used Claudine's cleansing test sample to test this.

Cleansing work for the in-range test for fields with numeric values. It also works for the missing matching field test, although the error reported is "Value is missing", when the google doc example had "Building is missing matching field".

The cleansing didn't detect the following errors/warnings inserted in the dataset:
- Missing non-matching field
- Wrong data type (string instead of date in Year Ending); the string was filtered out during remapping.
- In-Range test for fields with date types, such as generation_date, recent_sale_date, year_ending, that had dates in the year 1889 and 2020.

Thanks

**Comment by bravacheLBL** [comment]
This test revealed another issue though: in her test sample, Claudine had put dates in the fields for Year Ending and Year Built (format 01/01/2000). For Year Built, those dates were stripped off the "/" to become big numeric (01012000), while for Year Ending, the dates were correctly remaped as dates.

The In-range test for Year Built actually worked, even though all buildings in the file had an error for that fields, since the year reported was always 8 digit long and way passed the year 2015.

Should the "Year Built" and "Year Ending" always be strictly taking the year in a form of a 4 digit number or should the year be taken out of a full date when a full date is in input?

**Comment by RDmitchell** [comment]
I have made a new issue # 506 with the comments above from @bravacheLBL about outstanding data cleansing issues. So I am closing this issue.
