### ISSUE TITLE
Report generation vs mapping -- need to understand how to map fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#408]
As we know, the reporting function depends on properly mapping the fields to those that the program recognizes for reporting. I am seeing some issues with how I have mapped my data, and need guidance about how the fields should be mapped in order for them to show up in the reports.

I think this is probably an issue for Stephen, as he knows the most about how the field mapping is set up. 

To see what I am seeing:

Load two files from Issue 65 (see Claudine's link in the first comment in this issue):

* covered-buildings-sample.csv (10 records)
* 2011-portfolio-manager-sample.csv

![image](https://cloud.githubusercontent.com/assets/6314950/10203289/e19d6324-6769-11e5-827f-eb1d04be3bea.png)

I imported the covered building file first, then the 2011 PM file.
Here are the mappings:

Covered Building data
![image](https://cloud.githubusercontent.com/assets/6314950/10203325/16bcc464-676a-11e5-82cf-cdb2b881cccd.png)

Building List
![image](https://cloud.githubusercontent.com/assets/6314950/10203358/45ec4d90-676a-11e5-9572-f26d0e810590.png)

Here is the data in the Building List view (year ending = 12/31/2011)
![image](https://cloud.githubusercontent.com/assets/6314950/10203536/5cb3b97c-676b-11e5-9a79-69e0110e9357.png)

When I go to reports, set the dates and set x to Site EUI and Y to Gross Floor area, I get the No Data message on both plots. And I think this is because I do not have Gross Floor Area mapped properly.

![image](https://cloud.githubusercontent.com/assets/6314950/10203575/a9386c48-676b-11e5-870c-0a7cea90ea13.png)

When I set x to Site EUI and Y to Year Built I get data. 

![image](https://cloud.githubusercontent.com/assets/6314950/10203659/2e86fff4-676c-11e5-8b2d-82417f6c1263.png)

So I need to understand how the fields need to be mapped in order for the program to recognize the fields and gather the data. I think this is an indication that the next feature we need to add to the reporting is for the user to be able to pick the x and y axis from the list of fields that they have in their data. 

But at least if the mapping is correct, the data seems to be being generated correcly !

**Comment by StephenCzarnecki** [comment]
There are two cases here, the covered building file and the pm file.

Covered building - You do have gross floor area mapped here but there is no year_ending so these records are skipped for lack of a year_ending property.

PM files:  You do not have gross floor area mapped.  There is a Property Area (Building and Parking) but that is not mapped to gross floor area.  And according to the rules a record needs both requested values in order to be returned.  Since the covered building files are not valid for the reports and the PM files have nothing mapped to gross floor area then there is no valid data for the reports.

You however do have site eui and year built mapped in the PM files.  You have highlighted site eui in the picture above and year built was just year built in the file.  Since the files have both requested values and meet the other conditions (have a year_ending field and a release_date field) these points are returned when asked for.

**Comment by RDmitchell** [comment]
I am closing this issue because we have changed how we are doing the graphing, ie, we are now using merged data, not unmerged data.
