### ISSUE TITLE
Change reporting to use merged (not unmerged) records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#414]
we were using unmerged records to generate the reports, need to change it to merged building snapshot records.

**Comment by StephenCzarnecki** [comment]
Made a pull request here:  https://github.com/SEED-platform/seed/pull/415

Previously only got data from unmerged building snapshot records.  Per Robin changing that to use only data from merged records (the current canonical building and previous canonical buildings).  

One consequence of this is that since there is no current way to null out a field once a building gets a value in a field it will always have that value.  So if there are files with later years uploaded and they do not have the value in them but an earlier file did the later years will report the value from the earlier year since it is perpetuated through the matching.

**Comment by RDmitchell** [comment]
Assigned to myself for testing.

**Comment by RDmitchell** [comment]
@danielmcquillen @StephenCzarnecki -- how can I test this?

**Comment by RDmitchell** [comment]
@danielmcquillen, @StephenCzarnecki  -- how do I test this? I was thinking that if I brought in data, plotted it, then edited the master record for one of the variables I was plotting, that I should see that change in the scatter plot. 

Does that make sense for a way to test? I am assuming that editing the master building is the equivalent of editing the merged, canonical building in the building snapshot table.

**Comment by RDmitchell** [comment]
can't test this until we fix the problem with edits to building data not being saved, #966

**Comment by RDmitchell** [comment]
This is fixed. I edited a record in Building Details and the updated information is showing up on the graphs, so the program is using the merged data (not the unmerged building snapshot records). Thanks @StephenCzarnecki and @danielmcquillen !!
