### ISSUE TITLE
Reports - error checking for user input

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#418]
I consistently put in the same date for start and end, and then click Update Charts and the program reports No Data. Seems like we should put in some error checking to make sure the dates are set in a logical way and let the user know? Not sure quite how to do this so it isn't too obnoxious to the user -- maybe when the Update Charts is clicked, the error is displayed ?

**Comment by danielmcquillen** [comment]
I can show a simple modal. I was experimenting with showing just an error state on the start date and a tooltip, but tooltips don't seem to be working right with our current Angular version + Angular UI.

So rather than solving that issue right now, I can implement a simple modal. However, rather than doing it just for this page, it's probably better to create a "simple modal" partial and service that can handle simple modals for the whole app. (Kind of following this idea:http://weblogs.asp.net/dwahlin/building-an-angularjs-modal-service)

Right now we have very specific modals, but nothing generic to handle a simple message or error state.

So I can following the pattern described by Dan Wahlin in the post linked above, unless anybody has concerns about creating a 'simple' modal service.

**Comment by RDmitchell** [comment]
It seems like a good idea to me to implement a general UI solution for handling messages or error states.

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user or it's higher priority
