### ISSUE TITLE
Remove users ability to remove matching criteria once properties are uploaded

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#4219]
### Current functionality
From the column settings screen a user has the ability to change the matching criteria after it has already been used to determine property matches. In the context of Accountability Hierarchy, this will cause matching issues if the criteria are changed.

column settings
<img width="1351" alt="Screenshot 2023-09-11 at 10 40 39 AM" src="https://github.com/SEED-platform/seed/assets/58446472/4a467bc5-0710-483e-b1b3-07b40e7e3c21">

### Desired Functionality 
If an org has no inventory a user may add or remove matching criteria. Once an org has imported inventory the user may only add matching criteria.

**Comment by RDmitchell** [comment]
I know you have already been working on this, but this is a bit problematic, given the way the program is set up. It means that the matching fields need to be set perfectly before ever importing any records. 

Right now the default is (I think) 4 matching fields, PM Property ID, Address line 1, UBID and ?? 

Generally users only want to map on either PM Property ID, or Custom ID 1, and if they forget to set those before their first import, then they can't ever get rid of the others that they don't want, right ??

Maybe we should change the default matching fields -- maybe we shouldn't have defaults, which would force the users to set them before doing data import?

And the real solution is for users to be able to define the matching fields at the time of import.

**Comment by RDmitchell** [comment]
@perryr16 / @nllong / @axelstudios -- this is actually kind of a big deal, because it means the user has to set up the matching fields in Column Settings before they import any data, which didn't used to be true. 

I just did a demo with Sacramento, and didn't bother to update the matching fields, even though we were just going to use PM Property ID. Then I had the user go to Column Settings with the idea that we would uncheck the other default matching fields, and they were greyed out, obviously because of this change. 

Because of this I am wondering if we should rethink how we do imports, ie, the user should be given the opportunity, or at least instructed somehow, as one of the import steps, to set up their matching field. 

And we probably then SHOULDN'T have the 4 default fields that we currently have.

**Comment by RDmitchell** [comment]
Instance: seedv2 production
SHA: 
Org: LBNL 200

This change seems to be working
In this case, the existing matching fields, PM Property ID and Custom ID 1 cannot be unchecked, ie, deleted as matching fields
![image](https://github.com/SEED-platform/seed/assets/6314950/99b1900b-2843-4b90-b36c-f5fa3c4b54dc)

But new fields can be added as matching fields, for example UBID
![image](https://github.com/SEED-platform/seed/assets/6314950/17d8f13b-2c91-4d6b-9011-87da0bfd7a27)
