### ISSUE TITLE
Speed up /analyses with outputfiles

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#4433]

**Comment by RDmitchell** [comment]
@haneslinger -- is this fixed? Should it be tested? Presumably this is deployed to dev1?

**Comment by RDmitchell** [comment]
The status is "Review" so maybe it hasn't been deployed to dev1 yet.

**Comment by haneslinger** [comment]
I think this should be on dev

**Comment by RDmitchell** [comment]
@haneslinger / @kflemin -- how should this be monkey tested, ie, is this something I can test through the UI?

**Comment by kflemin** [comment]
@RDmitchell, I think all you can do here is open up the developer tools in your browser and select the 'network' tab. then load the analyses page and ensure that it takes on the order of 5seconds (rather than > 10 seconds).  This can probably just get closed too.
![Screenshot 2024-02-14 at 3 25 08 PM](https://github.com/SEED-platform/seed/assets/2205659/733718ec-2f7c-4e6d-8e13-d56212d74755).

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d5d60eaac
Org: LBNL 245
Analysis loaded in < 5 seconds.
