### ISSUE TITLE
Normalize BE endpoint success responses

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#445]
On the BE, it seems that two styles for status are used:
- `status`: `success` or `error` or `warning`
- `success`: `True` or `False`

We should pick one and stick to it. I'd opt for the boolean `success`. When this is normalized, also update the logic in the `ajax_request` decorator, as it currently handles both cases.

**Comment by mmclark** [comment]
+1

**Comment by danielmcquillen** [comment]
I'm curious about how the BE methods should work in the context of internal errors due to incorrect data sent from the FE.

If the FE passes correctly formatted but invalid data, would the server return a 400 Bad Request response, or perhaps a 422 Unprocessable Entity response, or would it return a 200 with "status":"error" (or whatever we standardize this string to).

I guess I'm confused about the conditions that cause an error to be signaled with an "status":"error" on a regular response object, and when errors are signaled with error response types.

**Comment by nicholasserra** [comment]
I didn't get too crazy with response codes in the other PR. I just wanted to get success vs failure working. 

If there is an "error" condition, it will now respond with a 400. If there's no error, it's a 200. There is no longer a situation where you'll see a 'status':'error' and a 200.

**Comment by danielmcquillen** [comment]
Ok, thanks Nick.
