### ISSUE TITLE
Fix ALI levels table on inventory details page

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4488]
Ensure that the hierarchy levels are listed in order in the ALI table displayed on the inventory details page.  They are currently in random order. Example:

![Screen Shot 2024-01-17 at 10 59 25 AM](https://github.com/SEED-platform/seed/assets/2205659/3885671d-51da-4eed-a9d6-0c393a4851e8)

**Comment by RDmitchell** [comment]
Instance: dev2
SHA: a79e79785
Org: LBNL 406

This is my access level definition
![Image](https://github.com/SEED-platform/seed/assets/6314950/811fd3dc-9a08-4901-94e3-733b58728ecb)

Here is what I see in the Detail View, which I guess is correct
![Image](https://github.com/SEED-platform/seed/assets/6314950/55b31681-fe91-4f94-a1f7-49c568e15f7c)

I guess in the example in the definition of this issue, not sure how the level 1, which I guess is Root, has a different name, ie, Sector. 

But I will go ahead and close this issue, because it appears that the detail view is showing the Access Levels in the correct order.

**Comment by RDmitchell** [comment]
Instance: dev2
SHA: a79e79785
Org: LBNL 406

This is my access level definition
![Image](https://github.com/SEED-platform/seed/assets/6314950/811fd3dc-9a08-4901-94e3-733b58728ecb)

Here is what I see in the Detail View, which I guess is correct
![Image](https://github.com/SEED-platform/seed/assets/6314950/55b31681-fe91-4f94-a1f7-49c568e15f7c)

I guess in the example in the definition of this issue, not sure how the level 1, which I guess is Root, has a different name, ie, Sector. 

But I will go ahead and close this issue, because it appears that the detail view is showing the Access Levels in the correct order.
