### ISSUE TITLE
AH: Streamline setup and data import

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4498]
Instance: dev2
SHA: a79e79785
Org: LBNL 406

I don't know as much about all the use cases, and thus criteria, for the Accountability Hierarchy, and so the suggestions below may not make sense for more complicated situations, but it seems like there are more steps in setting up the AH and importing the data than may really be necessary, at least in the simple case that I am proposing below, which might be a somewhat common (?) case. 

Here are the steps that I finally understood were needed in order to set up the AH and import data according to that AH

1 - I created an example which was for a hierarchy of State, County, City
![image](https://github.com/SEED-platform/seed/assets/6314950/15e4e4c6-bf38-4071-ba81-d299be10e9b4)

2 - I created this file to set up the options for each level
![image](https://github.com/SEED-platform/seed/assets/6314950/0c8e52d1-c179-4e70-a992-69bb90dcd148)

3 - And then I updated the actual building file by copying the State, County and City fields already in the file, gave them the AH name (so that they didn't have the same names as existing fields), and then added the first column to represent the root.
![image](https://github.com/SEED-platform/seed/assets/6314950/6a81438a-54ec-406a-adbf-1cd61c9e461b)

Streamlining ideas:
* Step # 2 above -- I don't understand why it is necessary to import the file that has all the options defined. Can't SEED determine those levels from the entire building file, imported in #3, even if it takes a bit more time? Maybe set up something like what is done with properties with meters, ie, have 2 import steps, where first the program determines the hierarch definitions, displays them and has the user confirm them (like with meters), and then goes ahead and imports the meter data. 
* Step #3 above -- it is unclear to me why it is necessary to define a column with the root name, in this case LBNL 406, and then put "root" in every record. If it isn't there, can't SEED assume that all the records belong to the root?

**Comment by kflemin** [comment]
Hi @RDmitchell,  thanks for testing and for your comments!

The reasoning for step #2 above was to have the org owner explicitly define all of the levels for 2 main reasons: 1) This way we can avoid data quality issues such as misspellings which cause multiple access level instances to be defined (ex: you end up with a ALI called 'california' and one called 'Californai' misspelled, or something like that), and properties in both.  And 2) while only the org owner can setup the access level tree, other users (once they are added to the access level tree and given  a specific permission level) can upload properties to the levels that they have permission for. But we won't know permissions until they are added to the tree, so we need the tree first.

For your second point: The reason we have to have the root level in the data spreadsheets is to differentiate the case where you actually WANT to attach a property to the root of the tree and the one where you just forgot to tell us where you want to put the data in the tree. SEED doesn't want to guess where you want to put it in case we get it wrong. Since we allow properties to live in any level of the hierarchy, the user must specify explicitly if they want to put a property in the root node, and the only way to do that is to have it as a column in the import file.  I know it's a lot and it appears redundant...at least it only has to be done the first time that something is imported and that's it. Once we know where you want a property to live, we can guess correctly in the future.

**Comment by RDmitchell** [comment]
@kflemin -- I knew that you had good reasons for how things are structured!!

My only concern is the level of effort it will take users to create these files. 

But I guess we should wait and see how the current use cases work, and take it from there... i.e., get some user feedback with the current design.

**Comment by RDmitchell** [comment]
I will close this issue.
