### ISSUE TITLE
403 error posting to /data/upload/

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#450]
In the following commit:

https://github.com/SEED-platform/seed/commit/c014ef7efdbebc8fbe37dba15e055953ed184512

Attempting to upload a file through the browser UI triggers a call to /data/upload/, which is returning an HTTP 403.  The following URL is an example:

http://localhost:8000/data/upload/?csrf_token=undefined&csrf_name=csrfmiddlewaretoken&csrf_xname=X-CSRFToken&import_record=293&qqfilename=covered-buildings-sample.csv&source_type=Assessed+Raw&source_program=&source_program_version=undefined&qquuid=44e8d4ab-b2d5-4290-a74c-3c32ff30440d&qqfile=covered-buildings-sample.csv

Steps to reproduce:
- Run the above commit locally
- Click on the dataset icon in the left navbar to seed the list of datasets
- Choose a dataset and select "Add more data files"
- Click "Upload a spreadsheet"
- Choose covered-buildings-sample.csv
- View the network display in developer tools to see the error.

**Comment by danielmcquillen** [comment]
The issue was due to our upgrading to Angular 1.4. 

Our Angular setup code in seed.js was looking for properties -- like csrftoken -- directly on the $cookies object. Meanwhile, in Angular 1.4, you need to use the get() and put() methods to get and set cookies values.

I've fixed in branch: https://github.com/SEED-platform/seed/tree/FixAngularUpdateIssues

**Comment by axelstudios** [comment]
No longer an issue
