### ISSUE TITLE
Set Cursor focus on current dialog box (login, etc)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#46]
Put cursor focus on the first input box any time a new screen is displayed, such as the email address in the log in page. etc.

**Comment by danielmcquillen** [comment]
There is an "autofocus" attribute in html5 that makes it very easy to indicate which field should get initial focus. 

However, there are two issues with this approach:

1) It's not supported in IE 8 and 9. And I think I saw a note from Rich stating a good portion of users might be on older machines/browsers. So perhaps this is an issue.

2) In my tests within SEED, autofocus doesn't work for the input fields in modal windows. It only works on the main pages. I think when a modal is shown something is stealing the focus away or somehow not letting it be set, but I'm not sure. So this would take more investigation.

Alternatively, there is a way to use directives in Angular to do something similar, but I haven't gotten my intial experiment to work yet for this approach.

If we want this feature to work consistently on pages *and* modals, it would seem we need to use the Angular approach. (This also might help for the places we're using tabbed views, since we'll need a way of trigger autofocus on tab change, not just on page load.) 

However, if supporting this feature on IE 8 and 9 isn't necessary, and if there's a way to get the modal dialogs to work with "autofocus", and the tab views aren't critical, then the that certainly is the easier option.

Any thoughts on this issue?

**Comment by rebrownlbnl** [comment]
If you look at the browser compatibility chart that was posted in issue #12 the older browsers are a really tiny fraction of the browsers, so probably not worth supporting (even in government). So the html5 solution is probably fine. The login page is a modal, which is what started this issue, so give the Angular approach a try, but don't spend a lot of time on it.

**Comment by RDmitchell** [comment]
@adrian-lara -- I still think it would be nice if when you first log in to SEED, the first input box on the login page, ie, email address, had focus, so you don't have to click into it with your mouse. 

If this is hard, I guess we can close this issue, but lots of websites (like all my banking sites) do this, and I am always in favor of less mouse moving and more just typing. 

![image](https://user-images.githubusercontent.com/6314950/115793949-f2876400-a381-11eb-9601-0536cf2bf448.png)
