### ISSUE TITLE
Label feature database migration

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#500]
This issue is for migrating the current Project label structure into the new label structure

**Comment by StephenCzarnecki** [comment]
Checked in a branch with fixes here:  500_label_database_migrations  This is a branch from Daniel's 434-develop-labels branch.

Database migrations for labels feature. First records all project buildings that do not point to a canonical building snapshot. Then creates a many-to-many relationship between CanonicalBuilding and StatusLabel. Next adds existing labels to this relationship. Finally drops the status_label field from the ProjectBuilding model.

**Comment by RDmitchell** [comment]
This has been hard to test as I don't have any existing projects on seedtest with labels. I will make some projects on seed and add labels, and then when we put the Dec release onto seed, I can test the migration.

**Comment by RDmitchell** [comment]
on Robin LBL 3, made a project with 9 records, labeled with 3 different labels
![image](https://cloud.githubusercontent.com/assets/6314950/11888106/1999ef46-a4ef-11e5-8e1a-c048d5610ff4.png)

I also had a few other labels defined even though they weren't used for this project.
![image](https://cloud.githubusercontent.com/assets/6314950/11888115/2fcfd4ba-a4ef-11e5-978f-5c7d426d5f12.png)

Once the new code is on the production server, I will log into this account and see if these labels were migrated into the new label world.

**Comment by RDmitchell** [comment]
**Problem**
It seems that the program added the labels from the Project to the Building Records, but the new labels made in the Project were not added to the list of labels. Not sure there is anything to be done about this, because we would have to write something to make a pass through all the Canonical Buildings (?) and add any labels found associated with those records to the Label table (?)
@danielmcquillen -- do you want to take a look at this ? I can give you access to my seed account that shows this issue if that helps.

**Observed behavior**

Looking at the project that I made, that contained the 9 records,  
![image](https://cloud.githubusercontent.com/assets/6314950/11915494/ba77f2ae-a65d-11e5-8bdb-ebd3d0840696.png)

If I click on the "Institutional" record, it shows the correct label in the Building Detail view. This is true of all the building records in the Project. So the program kept the labels with the Building Records
![image](https://cloud.githubusercontent.com/assets/6314950/11915502/00a64118-a65e-11e5-83d6-716b4ed1c72c.png)

However, when I go to the Label link in the Building List, where I can see all the labels, the three new ones I made in the Project didn't get added to the big list. So Municipal, Insitutional and Commercial Buildings are not in the list

![image](https://cloud.githubusercontent.com/assets/6314950/11915520/afa70f30-a65e-11e5-9cb1-6e0d65820b57.png)

I could add the labels to the label list, but I am thinking the new labels would not be associated with the existing labels associated with the building records.

**Comment by danielmcquillen** [comment]
Just coming back to this issue now. @StephenCzarnecki do you think this could be because somehow Robin applied labels to non-canonical buildings in her project view (if that's even possible), and therefore the labels weren't transferred during a migration?

I think in your comments you mention that non-canonical project buildings won't have their labels passed forward during the migration (and that is evident in line #14 of the migration https://github.com/SEED-platform/seed/blob/5d55a4d9312818e3aa3ebe9a1b51f440cd3ae259/seed/migrations/0007_auto_20151201_1515.py#L14).

Otherwise, if she did apply labels to canonical buildings in her project buildings view, I don't see how they would not have been created, since I would imagine 1) the label should have been created in status_labels when first applied to the project building and 2) Django would have shift that relationship directly to the canonical building on line 15 of the migration https://github.com/SEED-platform/seed/blob/5d55a4d9312818e3aa3ebe9a1b51f440cd3ae259/seed/migrations/0007_auto_20151201_1515.py#L15)

**Comment by RDmitchell** [comment]
I am going to close this issue, because at this point everyone who has an active account has been migrated for better or for worse. So nothing really to do here.
