### ISSUE TITLE
Add Password Creation Guidance on login screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#504]
The password has a lot of criteria -- we should have a help icon or something like that to list all the rules.

**Comment by RDmitchell** [comment]
Could also do this for now on the seedinfo website -- knowledge base, or add to getting started guide

Am assigning to myself to write the content, then we can decide where to put it.

**Comment by RDmitchell** [comment]
Here is the text that appears when setting your password when you don't conform to the password rules

Invalid Length (Must be 8 characters or more)
Based on a common sequence of characters
Must be more complex (Must contain 1 or more uppercase characters)

Robin -- Make this into text that would go onto the login page

**Comment by RDmitchell** [comment]
Add this to the Create Your Account dialog box -- and make sure these are the only requirements, ie, does the password also have to contain a number? 

Note: Passwords must be 8 or more characters, and must contain 1 or more uppercase characters)

![image](https://cloud.githubusercontent.com/assets/6314950/12835223/266dbdde-cb63-11e5-82cc-a9b78d67ccdf.png)

@pipermerriam -- am assigning this to you if you have time -- it's priority = 3

**Comment by nicholasserra** [comment]
There are a few more requirements. I'll fix the text.

**Comment by RDmitchell** [comment]
great !

**Comment by nicholasserra** [comment]
Do we want this on login and create account?

Final text is:

Note: Passwords must be 8 or more characters, and must contain at least 1 uppercase character, 1 lowercase character, and 1 digit.

**Comment by RDmitchell** [comment]
Text looks great. I think we just need it on the create account page, when the user is setting their password.

**Comment by nicholasserra** [comment]
Cool. I was going to add it to all the password pages, specifically the password reset flow (where they enter in a new password), and also the login pages because the complexity might help people remember their passwords. I've had to reset my seedtest password a few times because I forget that it needs to have an uppercase character. 

I already have this done, but if you think it's overkill i'll pull it out.

![screen shot 2016-02-09 at 2 57 35 pm](https://cloud.githubusercontent.com/assets/512288/12928783/7da58c5c-cf3d-11e5-879d-6f69eaa2df77.png)

**Comment by RDmitchell** [comment]
What you have done is great. Leave it as is.  thx

**Comment by nicholasserra** [comment]
Reassigning for merge and testing

**Comment by RDmitchell** [comment]
thx
