### ISSUE TITLE
Implement FE for Label Feature

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#507]
Based on the spec in issue #434 implement the GUI/Front end of the label feature.

**Comment by danielmcquillen** [comment]
Migration should created an Initial set of "pre-populated" labels 
- EUI Blank
- Energy Score Blank
- Gross Floor Area Blank
(Robin may add more)

**Comment by RDmitchell** [comment]
I have started a document with suggestions by cities, that supercede my initial suggestions. Here is a link to that doc.
https://docs.google.com/a/lbl.gov/document/d/14tvpbVFQXDihItRvrC4WDCnNqiMRbFrOtNbpWIq_Vys/edit?usp=sharing

**Comment by pipermerriam** [comment]
@RDmitchell or @danielmcquillen 

My understanding was that labels are organization specific.  Does this imply that all of these labels need to be created for each organization?  That is fine, I just want to be sure I understand the requirement.

**Comment by RDmitchell** [comment]
Yes, the labels will be organization specific, so there needs to be a pointer/reference to the organization from the label table (or however you have this organized).

**Comment by RDmitchell** [comment]
Do we need to talk about how this would be configured? I don't know how the label table is currently set up or how the link to organizations would be made. Or possibly @pipermerriam, put together your proposal, unless it's already in the spec. THX!

**Comment by danielmcquillen** [comment]
As documented in spec, we're going to do a boolean AND on the label filter on the Building List for this first iteration. We did this because showing multiple labels within the grid is a tricky UI issue that needs more thought. So, by making the filter an AND, it by definition indicates that all visible buildings have the current labels shown in the filter input.

e.g. these two buildings have 'abc' and 'def' labels...

![image](https://cloud.githubusercontent.com/assets/119496/11577116/75b69246-9a6f-11e5-9052-c0d99d688c47.png)

**Comment by pipermerriam** [comment]
@danielmcquillen here is the PR that converts this to use the AND operator.

https://github.com/SEED-platform/seed/pull/511/files

**Comment by pipermerriam** [comment]
Default labels are now being populated once 5bf00f2 is merged in #517

**Comment by RDmitchell** [comment]
I am assigning this to me for testing once Piper gets the org issue squared away. thx !

**Comment by RDmitchell** [comment]
This is working for existing accounts but not for new ones (see #557 ), so I am closing this issue
