### ISSUE TITLE
Implement Managing labels on Building Detail page

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#515]
Implementing the ability to manage label on the individual building detail page 

See #493 for the original spec for this feature

@pipermerriam -- I am assigning this to you for the Feb 2016 release.

**Comment by nicholasserra** [comment]
@RDmitchell is this still valid?

**Comment by RDmitchell** [comment]
@nicholasserra @danielmcquillen -- yes this is still on the list for the Feb release. 
The two of you might want to have a discussion about it, and since #580 is probably going to be taking up most of his time, @nicholasserra maybe you can take this one on. But as I said, you and Daniel should have a design discussion about it, because we haven't really spec'd it out. And then a spec (maybe pretty simple) should be developed which we can all review (quickly!) and then you can start implementing. 

Does that make sense as a plan?

**Comment by nicholasserra** [comment]
I'll talk with @danielmcquillen and just dive into it when I can.

**Comment by RDmitchell** [comment]
sounds good ! thx

**Comment by nicholasserra** [comment]
@RDmitchell So I just implemented this ticket using the label spec doc and the existing modal for editing labels from the building list view. I just now realized that the familiar modal that we've been using saves the labels as soon as you're done in the modal. Those label changes would be saved before you saved editing changes for the building rows.

Which I don't think is too big a deal, as the user is probably used to the flow of that label modal. 

I want to get your opinion on this. I think we should just show the "add/remove label" button even when you're not in "edit" mode on that building detail page, since editing labels is separate from editing the row data.

As it's set up now, you have to click the main edit button to see the label add/remove button.

So there's 3 choices:
- Show "add/remove label" button whether they click "edit" or not on building detail page
- Only show "add/remove label" button when they click edit, but leave it as is and let it save when the modal is closed
- Only show "add/remove label" button when they click edit, and do some extra work to make it so that changes aren't saved until they click the final save button on the page.

**Comment by rebrownlbnl** [comment]
I would agree that labeling a record is different than editing the data in the record, so the user should be able to add/remove a label without clicking the edit button.

**Comment by nicholasserra** [comment]
Cool, that's how I wired the PR.

**Comment by RDmitchell** [comment]
This feature is working well. I did encounter one issue but I am going to open a separate issue for that, and close this one. Thanks Nick !
