### ISSUE TITLE
Multiple IDs in Matching Field Fix

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#521]
The Multiple IDs in Matching field feature ( #480 ) isn't working quite the way I was expecting. Below is a link to a doc explaining what I am seeing. 

https://docs.google.com/a/lbl.gov/document/d/1PBgcD6Irm145m8mkJbDU2zcQaa5f9jxo8xhvGqh1qjc/edit?usp=sharing

@pipermerriam -- I am assigning this to you, and depending on what you think once you read the issue, you, @StephenCzarnecki and I might want to have a call to discuss it.

**Comment by pipermerriam** [comment]
Issue received.  Starting to look into it now.  I'll let you know what I find and whether I think I need a call to discuss.

**Comment by RDmitchell** [comment]
sounds good. thanks !

**Comment by pipermerriam** [comment]
Ok, I think I'm seeing where this is happening.  I'm going to take some notes here in the issue so that there in a public place for refererence.

The problem appears to be in the logic of the [`seed.tasks.get_canonical_id_matches`](https://github.com/SEED-platform/seed/blob/f924be35e874787f7fabd577958c4a8323bdb6d4/seed/tasks.py#L1020) function which is called in this call chain

* [seed.tasks.match_buildings`](https://github.com/SEED-platform/seed/blob/f924be35e874787f7fabd577958c4a8323bdb6d4/seed/tasks.py#L1002)
* [seed.tasks._match_buildings`](https://github.com/SEED-platform/seed/blob/f924be35e874787f7fabd577958c4a8323bdb6d4/seed/tasks.py#L1300)
* [seed.tasks.handle_id_matches](https://github.com/SEED-platform/seed/blob/f924be35e874787f7fabd577958c4a8323bdb6d4/seed/tasks.py#L1082)
* [`seed.tasks.get_canonical_id_matches`](https://github.com/SEED-platform/seed/blob/f924be35e874787f7fabd577958c4a8323bdb6d4/seed/tasks.py#L1020)

The `get_canonical_id_matches` function does a query where it returns `BuildingSnapshots` that match *any* of `pm_id, tax_id, custom_id` and even stranger, it will match records who's PM_ID matches the TAX_ID.  It then takes *all* of those matches and merges them into a single record.

What it looks like we're seeing is that the buildings start a separate entities and don't get matched because they don't have any of the three matching fields (pm_id, tax_id, custom_id) in common.  Then, when the second file is uploaded that has the common PM_ID, it creates new snapshots which now have a common matching field.  The matching logic see's these two are the same (even though the tax_id's are different) and merges them.

**Comment by pipermerriam** [comment]
I've opened https://github.com/SEED-platform/seed/pull/523 which is almost for sure going to break something else so that you can see the change that fixes this specific issue.  I've re-run your testing procedure against this new code and I end up with the expected results of two buildings at the end.  

I'll need some advice on whether this change is acceptable.  It seems pretty significant and it also logically seems like the correct query to be running.

**Comment by pipermerriam** [comment]
The fix in PR #523 introduces some breakage in existing tests.

https://travis-ci.org/SEED-platform/seed/builds/95670776#L2740

**Comment by rebrownlbnl** [comment]
I think the original logic in that matching function assumed that the ID fields were interchangeable, so *any* match between ID fields was considered good enough to match the records. This is based on the assumption that you can't control how the users map their input data fields, so the IDs in the uploaded records can get mapped to virtually any field, so the ID fields were seen as interchangeable.

This issue shows the implication of that assumption -- if the IDs are interchangeable we get unintuitive matching.

I think it is preferable to put the burden on the user to map their data properly, and then assume that the IDs are *not* interchangeable, and only match between the same fields in each record. 
So the approach in PR #523 is probably how we want to go.
But I'd need to look at the tests that break to understand what other impact this has.

**Comment by pipermerriam** [comment]
@rebrownlbnl a little investigation shows that the broken tests are a single test that merely demonstrates this cross-field matching.  I've pushed a commit (1ca3b6a) which fixes the failing test.

The remaining failures are selenium based and seem somewhat non-deterministic.

**Comment by RDmitchell** [comment]
I guess I don't quite understand what this line in the PR means

"the query has been adjusted such that it matches records which have all of the fields in common"

I do agree with Rich that we should change the mapping so that it only matches across fields that are the same, so the program would match Tax Lot ID to Tax Lot ID, and PM Property ID to PM Property ID, but not Tax Lot ID to PM Property ID.

@pipermerriam -- is this what the change you made does?

**Comment by pipermerriam** [comment]
@RDmitchell yes, it now only matches PM to PM, or Tax to Tax.

**Comment by RDmitchell** [comment]
@pipermerriam -- looking at the code you changed in tasks.py I think it makes complete sense that instead of matching all IDs to all IDs, that you are now only matching on each specific ID. I always thought that original logic didn't make sense, and could end up in many false positive matches. 

pm_id:
+        params.append(Q(pm_property_id=pm_id) | Q(pm_property_id__isnull=True))
     if tax_id:
+        params.append(Q(tax_lot_id=tax_id) | Q(tax_lot_id__isnull=True))
     if custom_id:
+        params.append(Q(custom_id_1=custom_id) | Q(custom_id_1__isnull=True))

So I guess now the only question is whether this breaks something else. I would be inclined to merge this PR and test it on seedtest, but I think @StephenCzarnecki is going to chime in after he looks at your changes.

**Comment by rebrownlbnl** [comment]
@pipermerriam I'm not sure the modified test is valid because it's matching two buildings that have the same values for both pm_property_id and custom_id_1, so won't that always guarantee a match, regardless of which IDs we are matching on?

**Comment by StephenCzarnecki** [comment]
@pipermerriam I'm not sure I understand how this change fixes the problem.  As I understand it this fix only applies to when one record has a field that corresponds to the value in a different field in another record.

For example, if Record 1 has
tax_lot_id = 12345
and Record 2 has
pm_property_id = 12345

Then under the old scheme these two records will be matched because the will check if tax_lot_id == pm_property_id.

But in this case the examples don't seem to have any overlap between those two fields.

Looking at Robin's example https://docs.google.com/document/d/1PBgcD6Irm145m8mkJbDU2zcQaa5f9jxo8xhvGqh1qjc/edit
 the tax_lot_ids are 5840022 and 6490020 while the pm_property_id is 6798215 which doesn't overlap.  

I haven't actually run the files through a debugger yet so maybe I am mistaken about something.

**Comment by pipermerriam** [comment]
@StephenCzarnecki the problem is that if record 1 & 2 have different tax ids but identical PM id's they will be merged and one of the tax ids will be *clobbered*.

This changes it so that for the three id fields, records will only be merged *if* the queried fields are the same (or one of them is null).

Does that clear it up?

**Comment by pipermerriam** [comment]
@rebrownlbnl Looking at the test that I modified, I'm unsure what exactly it is testing, or what exactly I'd need to change to maintain the correctness of the test.  The assertions are just looking at the `match_type` which hasn't changed.

Can you advise on what needs to be done here?

**Comment by StephenCzarnecki** [comment]
@pipermerriam Ah I see.  I missed that you removed the "or" operator on the results too.  So then is the following correct?

(Ignoring the cross-field matching for the moment because that seems like it's own issue) Previously a record had **any** of the four key fields (pm_property_id, tax_lot_id, address_line_1, custom_id_1) matched **any** value in one of those fields in the record it would be a match.  E.G.  Record 1:
    pm_property_id = 123
    tax_lot_id = 456

Record 2:
    pm_property_id = 123
    tax_lot_id = 789

Those two records would match because the search is doing an or on all the field matches.  pm_property_id == other.pm_property_id OR tax_lot_id == other.tax_lot_id.  So the pm_property_id matches even though the tax_lot_id does not and gives a match. 

Now it seems you effectively changed the query from *or* to *and*.  Then using this new match in the above example those two records would **not** match.  Because while the pm_property_id matches tax_lot_id does not.  pm_property_id == other.pm_property_id AND tax_lot_id == other.tax_lot_id

In the case where
Record 3:
    pm_property_id = 123

Then since there is no tax_lot_id then it will just match on pm_property_id and Record 3 will get matched to both record #1 and #2.

And in the case where
Record 4:
    pm_property_id = 123
    custom_id_1 = 999

That will also match to everything because while it has a custom_id_1 field everything else does not and therefore will be found because of the "custom_id_1__isnull=True" clause.

**Comment by pipermerriam** [comment]
@StephenCzarnecki I'll plan on getting you answers to your questions tomorrow.  Overall, I think everything you said is correct, but I'm not 100% whether either of those cases are going to result in undesirable merging or matching.

**Comment by RDmitchell** [comment]
@pipermerriam I am going to try to come up with some tests that will test you new method of matching IDs, and maybe we will abandon the test that you and Rich are talking about.

**Comment by RDmitchell** [comment]
I am closing this issue as we reverted these changes due to lack of correct data model
