### ISSUE TITLE
Invalid Date in Data Cleansing Screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#544]
I am getting an "invalid date" for the Date Uploaded in the Data Cleansing screen.

![image](https://cloud.githubusercontent.com/assets/6314950/11754191/69e68360-9ffe-11e5-9d84-2962f8a14982.png)

I have only tested with one file, but will test with others and see if it makes a difference what type of file it is. 

@axelstudios -- I am assigning this to you. thx.

**Comment by axelstudios** [comment]
Hmm, I'm not able to reproduce that, even by clicking `Data Mapping`->`Data Cleansing` on a file I uploaded weeks ago.  That value is pulled directly from the database for the ImportRecord's finish_time

**Comment by axelstudios** [comment]
Yeah, I think we're going to need a database migration to be able to store timestamps of when files were uploaded because that doesn't currently exist. The database table `data_importer_importfile` only has metadata about the file content and processing status (no timestamps), whereas the *dataset* table `data_importer_importrecord` does maintain timestamps for the entire dataset.

We could probably make that change with the upcoming work to add a filetype database table.

**Comment by RDmitchell** [comment]
@axelstudios -- Seems like a timestamp for the data files would be a good addition. Users may have multiple datafiles inside a dataset, and they can have different import dates.

Let's put this on the work for after the Dec release, so for the Feb release. I will change the milestone. Thx !

**Comment by RDmitchell** [comment]
Looks good !

![image](https://cloud.githubusercontent.com/assets/6314950/15559855/a1aee5de-229a-11e6-9b25-12300896d4ef.png)
