### ISSUE TITLE
Label filter should be case insensitive

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#552]
The label filter dropdown is currently case sensitive, so typing "cal" does not show "Call"

The filter should be case insensitive, i.e. we should see the following dropdown whether the user entered "C" or "c"..

![image](https://cloud.githubusercontent.com/assets/119496/11770382/b028643e-a250-11e5-82ca-4b6f8c41a2d8.png)

**Comment by pipermerriam** [comment]
@danielmcquillen I looked into this.  It's internal to the ng-tags library and I didn't see any configuration options to allow case-insensitive searching.

I **strongly** discourage hacking this in if it can't be done through official supported API's.  I think we'd be better off just using a nice looking select with all of the values since it's likely to be a manageable list of labels.

**Comment by RDmitchell** [comment]
I would agree, no need to hack.

I have already written in my documentation for labels about this. Very low priority and far away if we do anything.

**Comment by nicholasserra** [comment]
Should we leave this open or close it? Sounds like a wontfix.

**Comment by rebrownlbnl** [comment]
Yes, I agree we won't fix this anytime soon.
Robin said she put this in the documentation, but I'm wondering if we need a tool tip somewhere around the filter text box explaining that the filtering is case-sensitive?

**Comment by nicholasserra** [comment]
cc @RDmitchell for whether to close this.

**Comment by RDmitchell** [comment]
I will take this back for now. We need to figure out several "tool tips" to add to the program, probably for June, so we can address this issue then.

**Comment by axelstudios** [comment]
No longer an issue - active label filtering is currently case insensitive
