### ISSUE TITLE
Add "Matched" filter to Building List screens.

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#581]
Add the label feature to the Matching screen so that users can label unmatched records, or records that they want to come back to in the Matching screen for further scrutiny. Once we assign this issue we can develop a more comprehensive design doc

![image](https://cloud.githubusercontent.com/assets/6314950/11833350/78f5304c-a376-11e5-8b17-7131b8120e02.png)

![image](https://cloud.githubusercontent.com/assets/6314950/11833332/5038f544-a376-11e5-8573-de00c5cba088.png)

**Comment by danielmcquillen** [comment]
We discussed this feature and the reasons motivating it. We realized that really all Robin wants is the ability to filter on All/Matched/Unmatched on the building list screen, just as she now can on the matching screen. Labels were a roundabout way to get there (although using labels would also buy some more advanced uses like subdividing groups within matching screen).

Therefore, we should be able to get the required functionalty by just making the search_service's call to the BE look for the `children__isnull` property on the filter_params object, treating it as just one more filter to use when building the building list.

Background: The building list in the matching screen allows filtering by the All/Matched/Unmatched pulldown in the following way: the `matching_controller` adds a `children__isnull` property (with an `undefined`, `true` or `false` value) to the `filter_params` object.

Now, in other places in the application where the building list allows filtering, the `search_service.filter_params` object is used to set filter properties. Then, the `search_service.filter_search()` method is used whenever a new query needs to be made to update the building list, and this method eventually sends along those filter params to the BE endpoint `/app/search_buildings/`

However, in the `matching_controller` somebody has written a *custom* method to do this query, rather than relying on `search_service`. The controller then calls `building_services.search_matching_buildings` rather than the `search_service`. That FE method ultimately calls the BE endpoint `/app/search_building_snapshots/`

By the way, there's a comment in the `matching_controller` indicating that the author had intended to refactor this controller method into the `search_service` at some point.

At any rate, this is why the matching page can use the `children__isnull` filter param and other building lists cannot (yet) do this. They use different service methods to query different endpoints on BE.

So, adding the `children__isnull` parameter to the building list (and project building list if necessary) would mean updating the BE methods used by search_service -- saerch_buildings -- so that it too respects this filter.

Assuming that each situation is using the right BE endpoint (i.e. the building list needs to search 'buildings' and matching screen building list needs to search 'building snapshots'), I'm not sure if any FE code needs to be reorganized at this point, and if so how. However, we might just update the BE endpoint /app/search_buildings to recognize `children__isnull` and worry about refactoring later.

**Comment by RDmitchell** [comment]
@pipermerriam -- if you have time in your window of opportunity to ponder the solution proposed by Daniel, particularly in terms of the BE (and FE) aspects, that would be great. thx !

**Comment by danielmcquillen** [comment]
Piper let me know if you want to chat about the issue. For myself, I'm trying to understand better why the matching building list uses search_building_snapshots and the main building list uses search_buildings. I thought that by the time the user reaches the matching screen we're dealing just with canonical buildings (and combining canonical bldgs to make new canonical bldgs) but perhaps not and therefore the need to use a specific "building snapshots" method (whose name would seem to imply some may not be canonical).

At any rate, is adding the All/Matched/Unmatched filter to building list view as simple as getting /app/search_buildings to recognize the children__isnull property in the filter_params? I see in /app/search_building_snapshots that this 'children__isnull' property is manually added to the db_columns array to get it to work. https://github.com/SEED-platform/seed/blob/develop/seed/views/main.py#L730

Maybe we just need to do something similar for /app/search_buildings?

**Comment by pipermerriam** [comment]
@danielmcquillen I think the approach you've come up with looks solid.  Here are my responses to the questions you asked.

> At any rate, is adding the All/Matched/Unmatched filter to the building list view as simple as getting /app/search_buildings to recognize the children__isnull property in the filter_params?

No.  If you take a look at [`seed.search.create_building_queryset`](https://github.com/SEED-platform/seed/blob/develop/seed/search.py#L437) you'll see that all of the queries contain ` canonicalbuilding__active=True` which will only return snapshots that are canonical.

I like the idea of being able to get at any snapshot via the `/app/search/` endpoint though so I think it's worth going down this path.  What I believe needs to be done is to go ahead and get  `children__isnull` included in the `db_columns` as well as adding a new parameter to the search query `show_non_canonical` which defaults to `False`.

This would require changes to [`seed.search.process_search_params`](https://github.com/SEED-platform/seed/blob/develop/seed/search.py#L293) as well as [`search_service.construct_search_query`](https://github.com/SEED-platform/seed/blob/develop/seed/static/seed/js/services/search_service.js#L137).

The new parameter `show_non_canonical` would then need to be passed through to [`seed.search.create_building_queryset`](https://github.com/SEED-platform/seed/blob/develop/seed/search.py#L437) at both [`seed.search.orchestrate_search_filter_sort`](https://github.com/SEED-platform/seed/blob/develop/seed/search.py#L586) and [`seed.search.search_public_buildings`](https://github.com/SEED-platform/seed/blob/develop/seed/search.py#L409)

This may be enough to warrant it's own ticket for the backend work (which I'm happy to do and can probably get done today if I get the green light)

cc @RDmitchell

**Comment by pipermerriam** [comment]
I've got a channel created for this issue in slack.  Daniel, have you gotten an invite?

**Comment by danielmcquillen** [comment]
Yes I'm on slack now.

Thanks Piper. I hope I'm getting your proposal right:

1) We are going to allow the building list and project building list to filter for All/Matched/Unmatched buildings by now sending in a `children__isnull` property as part of filter_params, just like the matching screen current does. This prop's value can be undefined (all), false (unmatched), or true (matched).

2) We'll do this by making sure the `/app/search_buildings` endpoint now recognizes the 'children__isnull' filter within filter_params, just like the `/app/search_building_snapshots` endpoint

3) Furthermore, to make the API more robust, we'll add "show_non_canonical" to the parameters expected by the endpoint at `/app/search_buildings`

But for the purposes of this issue, I'll just be setting `show_non_canonical` to False, since we still want only canonical buildings for these searches (that hasn't changed).

Is that right? Or are you suggesting to unify `/app/search_buildings` and `/app/search_building_snapshots` into one api endpoint? Is that what you meant by the /app/search/ endpoint reference in your note above?

If that's the case, then would all calls that used to hit `/app/search_building_snapshots` now hit `/app/search/` with `show_non_canonical` = true, and all calls that used to hit `/app/search_buildings` will hit `/app/search/ `with show_non_canonical = false?

**Comment by danielmcquillen** [comment]
I updated the title to better reflect our consensus on the feature we need.

**Comment by danielmcquillen** [comment]
The current service methods on the FE seem a bit redundant:

service | method | endpoint called...
----------|------------|----------
building_service | search_buildings | /app/search_buildings
building_service | search_building_snapshots | /app/search_building_snapshots
building_service | search_matching_buildings | /app/search_building_snapshots
search_service | search_buildings | /app/search_buildings

**Comment by danielmcquillen** [comment]
I added a branch with some initial code to test out adding a filter. Piper, feel free to contribute or make PRs against. https://github.com/SEED-platform/seed/tree/581-add-matched-filter

**Comment by RDmitchell** [comment]
@nicholasserra -- after talking to Daniel, it seems like most of the work on 580 is going to be on the FE, with maybe a few BE changes. I was thinking this would be a lot of BE work. 

Therefore, I am assigning this issue, 581, to you to work on, since Daniel now won't have time to do it. 

Let me know what you think.

**Comment by RDmitchell** [comment]
@nicholasserra @StephenCzarnecki  -- you two should probably have a conversation about this feature, and decide the correct approach, and then decide who should implement it.

**Comment by nicholasserra** [comment]
@RDmitchell @StephenCzarnecki @danielmcquillen Sounds like @pipermerriam  and Daniel have it all sorted out above. So i'm just going to try to go that route and see if I can get it working correctly.

**Comment by RDmitchell** [comment]
OK, sounds good. Thanks.

**Comment by nicholasserra** [comment]
Some points from our discussion today:

Our current plan to identify an unmatched building is to query for buildings without parents or children. We have not come to a solid conclusion on whether the CanonicalBuilding.active field comes into play, but if so, we have a clear path to adding it to the frontend payload.

**Comment by nicholasserra** [comment]
@RDmitchell Can you give me a couple data files to test matched vs unmatched? Basically we have this working for building list, just need to test it. What would be best is if you provide a couple files I can import locally, that have data that will have both matched and unmatched results.

**Comment by RDmitchell** [comment]
I am off site today and tomorrow but ahould have some time tonight to put
together some sample files

**Comment by danielmcquillen** [comment]
I've tested this with the standard 512-line files covered-buildings-sample.csv and portfolio-manager-sample.csv.

I loaded each and mapped, then matched them, then manually unmatched 6 rows.

The building list correctly showed 518 for all buildings, 506 for matched and 12 for unmatched. So that's good!

**Comment by danielmcquillen** [comment]
Attaching .zip of standard 512-line files mentioned in my note above.

[archive.zip](https://github.com/SEED-platform/seed/files/100129/archive.zip)

**Comment by danielmcquillen** [comment]
Nick I sent you a link to the standard test data

**Comment by nicholasserra** [comment]
Nice! I'll test this when I get done with another ticket.

**Comment by RDmitchell** [comment]
@nicholasserra -- I am handing this back to you. The problem is that when you select either Matched or Unmatched, and the results are displayed, if you then leave the Building list (with one of those states selected), when you come back to the Building List the pull down shows "Show All" but the displayed records are still showing whatever state they were in when you last left the Building List (ie, showing matched or unmatched records, not all records). And it is not clear to me how to force the program to "show all" once it is in that state. If I reselect the pulldown, the program doesn't change the view -- it still shows whatever state it was in when you left the building list view. Also, Refreshing the browser doesn't change the view to show all the records.

I can make a short video if you can't reproduce this problem. 
![image](https://cloud.githubusercontent.com/assets/6314950/12658455/0b86b4d0-c5be-11e5-9c5d-a6c07de42988.png)

**Comment by RDmitchell** [comment]
I am seeing this when I log into my LBNL 11 seedtest account.

**Comment by nicholasserra** [comment]
Probably an issue with the sessionStorage caching. I bet if you close the browser window and reopen it's fine. I'll check it out now.

**Comment by nicholasserra** [comment]
Tested, and cycling through the pull down from show all (with nothing showing) -> matched -> show all gives me back buildings. Should be a quick fix.

**Comment by RDmitchell** [comment]
took this back for testing when the PR is merged

**Comment by RDmitchell** [comment]
The basic functionality is working well. There is still a caching issue, possibly, but I will make a new issue for that, and close this one. Thanks Nick !
