### ISSUE TITLE
If no matching fields mapped, can't get to Building Details

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#585]
If, for whatever reason, you don't map any of the 4 matching fields in a data file, when you go to the Building List, because there are no matching fields, which are usually displayed with a link to the Building Detail view, there are no links to get to the Detail view. 

Not sure what to do about it, but seems like a design flaw.

**Comment by rebrownlbnl** [comment]
On data import, should users be required to map at least one field to one of the 4 matching fields?
Otherwise, the building list page needs to change so that other fields (besides the 4 matching fields) can be hyperlinked to the detail view.
I lean toward the former approach, since it's hard to imagine a building that doesn't have some type of ID or an address. (although I'm probably overlooking some kind of unusual edge case)

**Comment by RDmitchell** [comment]
I don't think we should enforce setting a matching field. At this point, I think it's not going to be an issue, because everyone using the software is setting at least one matching field. I just happened to be testing an edge case and didn't set it and then discovered this issue. 

I actually think the current UI doesn't make sense -- why should only the matching field link to the details screen? any field in that record links to the same detail. 

So I would be in favor of changing the screen UI a bit at some point (I was thinking possibly for either the May release) where you can get to the Detail view some other way besides just the link that shows up for a matching field.

**Comment by RDmitchell** [comment]
Not relevant anymore with UI Grid in V 2.0. The "i" icon links to the Detail view, so no linked matching fields are needed to do that.
