### ISSUE TITLE
Missing {{STATIC_URL}}seed/images/DOE-SEED-Logo_v4.jpg

### ISSUE THREAD

**Issue by teeterc** [SEED-platform/seed#587]
Open google chrome developer tools and view errors on the landing page (before logging in)
static/seed/images/DOE-SEED-Logo_v4.jpg 404 (Not Found)

This is on the development branch

Cheers,
Clay

**Comment by rebrownlbnl** [comment]
There's probably a more elegant way to do this, but that image is missing is because it is a trademarked logo and the person/organization installing SEED has to sign a license with LBNL for permission to use the logo publicly. The licensing process is described [here](http://seedinfo.lbl.gov/SEED-Affiliates/affiliate-criteria) under Hosting Provider.
Basically, there's a different process to get that logo than going through the public github repo.

Is there a nicer way to make a placeholder for an optional image?
I suppose we could put a conditional statement around it that checks an environment variable, but that will throw an error if the variable isn't defined.

**Comment by tallus** [comment]
The SEED affiliate page no longer exists.

Locally I created a 1px by 1px image and saved it to static/seed/images/DOE-SEED-Logo_v4.jpg. 

AFAICT this image is only used  in one template on the landing page which is rendered from a django template: seed/landing/templates/landing/_marketing_bullets.html
we could switch out the file name set in config which can point to the logo or a place holder depending on what's there.

**Comment by rebrownlbnl** [comment]
The affiliate page was moved here:
http://seedinfo.lbl.gov/SEED-Technical-Allies
Putting the image file name in a config file seems like a good approach.
This isn't very high priority, but look into it if you have some extra time.

**Comment by RDmitchell** [comment]
@axelstudios -- I still see this error on seeddev. How was this resolved?
