### ISSUE TITLE
Filtering floating point numbers that are rounded/truncated

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#613]
**Summary**
I can't seem to get only values exactly equal to 100 in one of the numeric fields in the sample data

**To recreate**
Import the sample PM data (portfolio-manager-sample.csv) as a Portfolio Manager file, accept all the automatic mapping suggestions from the program, the program generates the building records.

Set filter to > 100, get the following -- seems like the program shouldn't show values equal to 100 for the > case
![image](https://cloud.githubusercontent.com/assets/6314950/11915315/e3ffdd6a-a655-11e5-98f7-16e12357ab5e.png)

Set filter to 100, program shows the following results -- program shows 101 I guess because it is doing some sort of fuzzy matching, or contains or something? Not sure, but this might be ok.
![image](https://cloud.githubusercontent.com/assets/6314950/11915322/1b10505a-a656-11e5-876a-52f9916f2838.png)

Set filter to =100, program shows no results. Isn't this the way that I would set up the filter to just show values exactly equal to 100?
![image](https://cloud.githubusercontent.com/assets/6314950/11915326/4e46526c-a656-11e5-8924-a016e5261bca.png)

**Comment by pipermerriam** [comment]
The field you are filtering on `site_eui_weather_normalized` is actually a floating point number in the database.  I tried this in my database which has records with the following values `103.5, 103.6, 105.3, 105.6`.  Since these numbers get rounded, the `103.5, 103.6` numbers get rounded to `104`.  When I tried searching for `==104` I get nothing and for `>=104` my first record is always `105` which is also correct since it's the first record greater-than-or-equal-to 104.

This seems like a problem with storing one number on the backend and displaying it truncated on the frontend.  I'm not exactly sure what my recommendation would be for fixing this.  Does this information give you any thoughts?

**Comment by nicholasserra** [comment]
@RDmitchell is this still valid?

**Comment by RDmitchell** [comment]
It seems like we should display the values in the form that they are stored in the database, and possibly in this case not round them. 

This is a design question that I should probably put to the users. 

I will assign this issue to myself to get some feedback about what to do -- could be in the end the users will want to have control over the decimals that are displayed, etc.

**Comment by macintoshpie** [comment]
Looks like this works as desired now
<img width="163" alt="Screen Shot 2021-09-28 at 1 25 48 PM" src="https://user-images.githubusercontent.com/18518728/135144511-5686af0b-eaa7-483b-affd-77ca1e82e2a8.png">

<img width="164" alt="Screen Shot 2021-09-28 at 1 25 39 PM" src="https://user-images.githubusercontent.com/18518728/135144522-00aad180-41c0-4789-8fd2-770a95d96e68.png">
