### ISSUE TITLE
When sorting on fields that are stored in the JSON Blob extra data field, if the field is not in the blob, the record is not included in the sort

### ISSUE THREAD

**Issue by MarshallDDB** [SEED-platform/seed#64]
Sorting the buildings list by an attribute hides all buildings that have a null value for that attribute. This means the searching for null values is impossible. this is a problem!

**Comment by RDmitchell** [comment]
Emailed Marshall to get clarification on this issue.

**Comment by RDmitchell** [comment]
I believe the issue here is that when data is stored in the JSON Blob extra data field, by default only non-null data fields are stored. This means that for the same dataset, there may be fields that are in some records but not others -- if the field value was null in the original imported data file, that field is not created in the JSON Blob. Therefore, in the building list, if you are sorting on a field from the JSON blob, only records that have data in the field being sorted on will be returned. This can be very disconcerting if you have 100 records in your building list, but you sort on a field, say Energy Star Score, and only 90 records appear, because 10 of the records don't have that field in the JSON Blob.

**Comment by MarshallDDB** [comment]
Ah, that makes sense!

**Comment by RDmitchell** [comment]
I am closing this issue because it is captured in Issue # 136.
