### ISSUE TITLE
Reference list of BEDES properties

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#648]
Just an observation/idea:

When in the mapping phase, it would be nice to allow the user to call up a complete list of BEDES properties, just for reference in case the user isn't familiar with standard names or needs to browse to get an idea of the best property to map to.

You can start typing into the input field to get a partial list, but that doesn't give you the complete list.

![image](https://cloud.githubusercontent.com/assets/119496/12185757/2a5fe764-b5f1-11e5-9acd-3f29345b81f9.png)

Perhaps a simple modal would work here, similar to the reference modal you get in an app like Gmail when you want to see control keys (in Gmail you type '?' to get the modal popup)...

**Comment by RDmitchell** [comment]
Actually, what we really need to do is have a way to distinguish, in the pulldown list, what are BEDES terms and what are user defined terms. As soon as a user types in their own field name, it becomes part of the default list (which is good because the program remembers the mapping and the user doesn't have to type their new field name in again), but then there is not a way to distinguish which fields are the standard BEDES fields and which are the user defined field names. 

This is something for the June release (or possibly even later in the year) -- we actually need to revamp the mapping screen in several different ways.

**Comment by nllong** [comment]
Wrap this into general BEDES mapping functionality which is not yet defined.

**Comment by RDmitchell** [comment]
See #1960
