### ISSUE TITLE
Mapping/Matching cancel button placement

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#693]
When the user clicks "Save Mapping" in the Mapping screen, the following dialog appears
![image](https://cloud.githubusercontent.com/assets/6314950/12664241/f718bdf2-c5e2-11e5-8835-9943be443dbf.png)
When the user clicks the "Confirm mappings & start matching" button, the  dialog below appears -- the Cancel button is pretty much in exactly the same location as the "Confirm mappings & start matching" button, so unless the user changes their mouse position, the mouse pointer is hovering over the Cancel button. Not the end of the world, but it would be easy to accidentally cancel out of this operation because of that. Am setting it to a low priority, but it might be something to deal with in a GUI pass at some point. 
![image](https://cloud.githubusercontent.com/assets/6314950/12664262/24d02b72-c5e3-11e5-9247-2a354542e797.png)

**Comment by danielmcquillen** [comment]
Robin, I wonder if we could chat more about this as I think we could improve the clarity of this step by talking about the semantics around data import.

At this stage in the import process, the user has already persisted both a raw data row and mapped data row in the database. So in one sense the data is already mapped. The only thing left to do is to either assign a canonical reference to the mapped rows, or join them with an existing canonical row to create a new child row, which happens in matching.

So to say "Save mappings?" isn't actually true. The mappings already are saved. The final step of creating canonical rows from those mappings is what still needs to happen. Does the user need to know? Of course, we should shield the user from technical details, but at the same time we have to be accurate in our description of the state of the system

Therefore, a question: is the user trained to understand "Mapped" mean that the mapping has happened and persisted to the database, or does it mean the mapping has happened and persisted to database *and* a canonical reference created (so the building shows up in the building list)?

If we do want them to think of the mapping not being complete until matching is done, then I suggest the following:

1) Change title of modal dialog to "Save mappings?" Get rid of "confirm" text.

2) Update the text in the dialog to include some regular text to remind the user about the state of the database. Something like "You have imported your data into the SEED building database, but you have not finalized it yet by matching it against existing buildings, so it won't yet show up in your building list. To finalize these mappings, click the blue button below."  

3) Then beneath that normal text, keep the current yellow help text "Did you review your mappings? It's a good idea to double check your mappings before finalizing them. Once SEED matches your buildings you can not undo or edit these mappings." 

4) Get rid of "x" in yellow warning callout as it doesn't make sense in the context of a modal dialog.

5) Change the primary button label to **Save Matches and start matching**

6) Change cancel button label to   **Go back and review matches** so that it directly follows what the help text is saying.

**Comment by rebrownlbnl** [comment]
The second approach sounds good.
On step 6, do you mean "Go back and review mapping?"

**Comment by RDmitchell** [comment]
@danielmcquillen -- thanks for the ideas. We can work on this for the June release -- one of the things we might want to do is actually separate the two actions, ie, have an explicit Save Mappings step, and a completely separate Match records step, which will need some serious design thought. I would like to tackle this in the March - May time period, for the June release. Thanks for pondering this, I think your understanding of what is going on in the background will help us figure out the best way to structure this.

**Comment by danielmcquillen** [comment]
@rebrownlbnl argh! Mapping and matching. So easy to mix them up. I just edited my comment above to say 'mapping.'
@RDmitchell ok, I'll wait until then to pick up again if you want to assign it to me.
