### ISSUE TITLE
Allow user to disable columns in import files and handle redundant column names in import files

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#709]
The program can't deal automatically with a file that has two fields with the exact same name. We should require the user to fix the file so that there are not duplicated field names, and then reimport it. 
So in the case where there are two field names in a data file that are identical, the program should detect that and put up a message to the effect of:

The program has detected the following fields that have identical names <xx,xx>. Please make the field names unique in your data file and reimport. 

Once we get to this issue, we can refine the message and possibly the behavior.

**Comment by RDmitchell** [comment]
@bravacheLBL will make a sample file and a more complete description of the program's current behavior to add context to this issue.

**Comment by bravacheLBL** [comment]
The sample file is here:
https://drive.google.com/a/lbl.gov/file/d/0B-Qu-Oc76NpJdlYtRVV2eDM5RkU/view?usp=sharing

In that file I duplicated the address column and left the same field name. I also deleted some of the data in the duplicate to be able to differentiate the two.

It seems that the way this is handled by SEED is to detect that there are two fields with the same name, but to only attach the last column to that name (twice).

![image](https://cloud.githubusercontent.com/assets/14808873/12766497/0760fd94-c9b9-11e5-87cb-7733a5d08d49.png)

If you try to name the two fields differently, only one of them will contain the data while the other will be created but empty.

![image](https://cloud.githubusercontent.com/assets/14808873/12766696/c66ffdb6-c9b9-11e5-952c-b9427010a499.png)

(the field "Address Line 1" is completely empty)

The easiest solution would be to block that type of file and print an error for the user to fix it, so that he can differentiate the two fields manually, knowing what they represent.

**Comment by RDmitchell** [comment]
see issue #781

**Comment by RDmitchell** [comment]
instance: staging (LBNL)
SHA: 36cc59d (2.3.1 release)

I'm not sure the title of this issue really captures the problem, but decided to leave it. 

The program still exhibits this behavior, and I am not even sure what to do as a user. So I think the "Duplicate" indication is left over from other code. 

So we need to figure out how we want the program to handle this and then bring it into the current world. Seems like the program should let you map the fields to different SEED names, but maybe that's not possible given the way the mapping table works. 

So maybe the user just has to abandon the mapping, fix the file outside the program, and then reimport it? 

![image](https://user-images.githubusercontent.com/6314950/37236894-7f0b2c52-23c1-11e8-8720-07bdeac896f7.png)

**Comment by nllong** [comment]
We need to allow the user to be able to disable a specific column that is being imported.  So I suggest that we keep this open and re-enable the ability to ignore entire columns in import dataset

**Comment by adrian-lara** [comment]
@nllong I see how this issue/feature came to be. Given your last comment I just want to double check on the "handle redundant column names" part. Is it the case that SEED should allow for two _file columns_ of the same names to be imported as long as they get assigned to two different _SEED columns_?

**Comment by RDmitchell** [comment]
@nllong -- I'm not sure that ignoring the field solves the problem in the original description, which is that the user has 2 columns with the same name. If they don't want to ignore one of them, but actually meant to have them both imported, but need to change the name of one of them, does our current mapping world allow that? Or do they still need the information from SEED that there are two fields with the same name and they should change the names outside of SEED, and reimport the file with the renamed fields ?

**Comment by adrian-lara** [comment]
After discussion - we think it'd be best to prevent a file with two columns of the same name from being imported - both on the BE (return failed response) and on the FE (disable 'Map Your Data' button and show an HTML `alert-danger` warning).

Although it will be possible to disable an import file column (and presumably disable one of the duplicate column), the "prevent import" decision above will help prevent the introduction of complexities around displaying historical column mappings for an import file.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 758cbdd5
Org: LBNL 301
Cycle: Test Duplicate Field Name

Program is working as designed, ie, won't allow file to be mapped (and thus not imported) when there is a duplicate field name in the file. 
![image](https://user-images.githubusercontent.com/6314950/71219086-ca14c480-2278-11ea-9748-17b5a700c928.png)
