### ISSUE TITLE
Create proposal for how to control order of columns in various lists, including truncation / wrapping issues

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#71]
Allow user to set field order as well as visibility in the Edit Columns/List Settings.
In both the Matching screen (Edit Columns) and the Building List (List Settings) screen the user can control the “visibility” of a field by checking or unchecking it. But the program is showing the fields in alphabetical order in both cases. Allow the user (in the settings screens) to change the order of the fields (and keep that order until the user changes it again). This could also be part of an admin setup feature (see # 22)

**Comment by juliecov** [comment]
For resizing table columns, there are two options that I like:

Option 1: jQuery UI resizable
-	This one is very popular/commonly used and recommended, and included with jQuery UI
-	The current minimum width setting on columns in the filter row limits how small you can make a column
-	Resizing a column affects all other columns
-	Would need some work to resolve lag between mouse and column border - this is due to table auto-adjusting the width of the other columns while you resize one

Option 2: third party colResizable
-	Resizing only affects adjacent column
-	Includes optional handle for mobile use
-	I like the action better on this one (only resizing the adjacent column), but I don't think this implementation is as clean - so would probably require some extra tweaking
-	http://www.bacubacu.com/colresizable/ 

You can see a rough demo of both in action at http://seed.cakesystems.com/static/temp/resizeColumns.html 

Note that I updated the header cells to wrap if necessary, and also added a class to the data cells to limit the text to the column width and use ellipses to indicate that the entire field is not visible.  This is more obvious on the second example, because I removed the filter row.  This seems like a good way to handle potentially long text values, especially since the user can just widen the column to see the entire value.  We could also add some functionality to show the full text if the user hovers over the cell, but I don’t know that you really need it. 
	
I also mocked up some new functionality for reordering the columns in the table (rough demo at http://seed.cakesystems.com/static/temp/manageColumns.html )  You can use the buttons to toggle between Show/Hide Columns, and Column Order.  Basically the Column Order just lists the visible columns, and you can drag them around to update the order.  There are a couple issues to work out, but you can get the idea of how it would work.

**Comment by RDmitchell** [comment]
Julie -- this is great !!! Thank you for putting these mockups together. It's a perfect way to show the functionalities.

It is interesting to see the two different options for the column resizing, and I think the column ordering looks like a good solution. 

I want to put these links up on our SEED User Forum to get comments from users, and we will also present this at our SEED User Meeting next Wednesday and try to extract some more user feedback.

Then we can make a decision about which way to go. 

Also, comments from other developers are also welcome !

**Comment by rebrownlbnl** [comment]
For the column reordering, I think the user might need a little hint to know that they drag the column names into their desired order.
Something like this in the header under the buttons:
"**Column Name** (drag names to reorder)"

**Comment by RDmitchell** [comment]
Julie -- I am going to get final input from a group of SEED users this week, and then we will be good to go to implement these features -- I will find out from them which column resizing option they think is best and if they have any suggestions for refining the column ordering (I think it is good the way it is but it is always good to get other feedback). So hopefully by the end of the week you can implement these. Thanks! Robin

**Comment by RDmitchell** [comment]
Julie -- I presented this proposal to a group of pilot cities, and the features got good reception. So please implement them. I have put comments below -- most of the comments are probably things we will put in other issues for future refinements, and we will just implement these two features in their most simple form now to get the basic functionality working without having to spend too much time on it. Let me know if you have any questions, particularly as you are starting to implement them. 

Here is what the group decided, with comments for future refinements of this feature

**Column Resizing -- Option 1 was chosen.**

Two comments about that option -- If these are easy to do, you can add them, but if they add too much complexity to the implementation, we can put them in another issue for future implementation as refinements (I don't want this to be too complicated or time consuming for you to implement):

  * Can a feature be added so that if you double click on the right hand column boundary, the program resizes the column to fit the data (not the width of the field name)?

  * Add a button (or something else) which allows the program to resize all columns to fit the data (and for data that has more columns that fit on the screen, the program would resize based on what fits reasonably on the screen, and then the scroll bar allows the user to get to the rest of the data (which I guess in the perfect world would also be resized to fit the data).)

**Order of fields**

Everyone thought the field ordering feature was good. 

* I noticed that it is not possible to drag a field into the first position -- you can get a field into the first position but it takes two steps -- get it into second position, and then move the first field down somewhere else. If this is easy to fix, do it, if not, we can live with it. 

* I asked if people thought an "Alphabetize" button would be useful, but that got very lukewarm reception, so we won't implement that now. 

* There was some interest in a "reset" button that would put the fields back in the original order from the imported file, but again, I think this is a feature we can implement in the future.

* Rich's suggestion of adding a bit of help text is probably a good idea.

**Comment by juliecov** [comment]
I added the resizing and sorting to the building list and settings and also to the project list and settings.  There are a variety of UI changes worth reviewing and critiquing, including:
-	Wording and placement of show/hide and reorder links
-	Text directions for reordering the columns
so let me know what you think of it all or if anyone has any suggestions for improvement.  We can also make other tables resizable as well, let me know if there are any in particular you want me to update.

**Comment by RDmitchell** [comment]
Great. Miles can merge your PR and we can review your changes on seedtest. Thanks ! Robin

**Comment by cycustodio** [comment]
Julie,
The column ordering works. The resizing columns is not working, I think the directives are getting overwritten somehow. I took a screen cap of the directives. 

Here we have the column City that we are trying to resize. 
![baseline_column_size](https://cloud.githubusercontent.com/assets/8461331/9777357/3acabc42-5718-11e5-9814-b07142b11cb9.png)

I drag the column border and you can see the width increased in the javascript but it's not showing on the GUI and when I let go of the border it snaps back to the original width value. 
![unresized_column](https://cloud.githubusercontent.com/assets/8461331/9777356/3ac9bd56-5718-11e5-87c8-7ca5a7a384c6.png)

**Comment by juliecov** [comment]
Hi Claudine,

The resizing wasn't working when the table was showing a lot of columns (or if your browser size is thin) because the columns have a minimum width to allow the filters to show properly, and the table width was limited to the width of the browser.  I've checked in an update to allow the table width to extend past the browser width, so you can scroll to view all the columns.  I also added a min-width so you can't make the table thinner than the browser width, let me know if you think it would be better to allow the table to be skinnier and I can remove that.

**Comment by cycustodio** [comment]
Personally, I like how the table has a minimum width. Thanks for implement the column reordering and resizing. It looks great. Are there plans to extend this functionality to the matching screen as mentioned in the original issue?

**Comment by RDmitchell** [comment]
I think this is good for the first cut. I will close this issue and make a new one to add this same functionality to a few more places -- matching view as well as the building detail view. Thanks Julie
