### ISSUE TITLE
Investigate necessity of Schema model

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#809]
Investigate the necessity of the Schema model on the BE. On production, there is only one row in the DB. The `get_column_mapping_suggestions` endpoint does complex logic to get the Schema for each column, but ultimately, they're all the same.

Not sure if this can be removed and hardcoded, or if it's in there for future use.

cc @RDmitchell

**Comment by RDmitchell** [comment]
What is the functionality of the schema? I am wondering if it was put in place for a need that we know about but having seen the need to implement yet?

**Comment by nicholasserra** [comment]
I'm not sure yet. All i've gathered so far is that there's only 1 row in the production database for it, and that the codebase doesn't create them at all. From what I can see, I can hardcode its value right now without any issue. I need to spend a few hours digging into it.

**Comment by rebrownlbnl** [comment]
This may have been a way to store field mappings in the database, rather than in text files, which is what we do now. Is that possible?
Where is this in the code?

**Comment by nicholasserra** [comment]
`seed_schema` table. Only one row, and the only content is a column called `name` with content `BEDES`.

**Comment by nicholasserra** [comment]
Basically, it seems that every Column object is supposed to have a schema. But every column just points to this one Schema, BEDES.

**Comment by rebrownlbnl** [comment]
okay, I know what this is doing. This is how SEED originally know whether the little green check mark should show up in the mapping screen, to indicate if a field came from "BEDES" or not. (BEDES is a standard data spec for building-related data).
At that time, BEDES was the only schema we had, which is why all the fields say BEDES.
I think we deprecated that approach, right?
If we are no longer showing the check mark we should stop doing that query of the schema table.

We've reconsidered our whole use of BEDES in SEED, so if and when we re-implement this it needs to be redesigned from the ground up.

**Comment by RDmitchell** [comment]
Good sleuthing !!! 

And I agree that if we need to reimplement it (which we might at some point) we would redesign it from the ground up. 

So, it can go !!!

**Comment by nicholasserra** [comment]
Cool, so i'll remove the model and any code around it. Should speed some things up too.

**Comment by RDmitchell** [comment]
yup, go for it !

**Comment by RDmitchell** [comment]
don't know if there is any monkey testing I can do regarding this. I haven't hit any issues in mapping that I know of. So am closing.
