### ISSUE TITLE
Uploading files with duplicate data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#83]
Almost all users are going to have the issue of uploading data files, such as Portfolio Manager, multiple time during their benchmarking process. SEED should only load the data that is not already associated with the building record, and should ask the user if they want to update changed data for records already in the master building list. 

The first step is to create a design / specification document.

**Comment by RDmitchell** [comment]
Here is a link to the current specification. 
https://docs.google.com/a/lbl.gov/document/d/1GH8VdxhBOVjU7iObpryLu-IwxPp0KdxwIM0wZ5HGZCQ/edit?usp=sharing

For this first cut, it is a relatively simple implementation of not writing "copies" of existing data to a building snapshot. We are not going to do any UI changes for this first implementation, it will all happen behind the scenes.

**Comment by danielmcquillen** [comment]
Hi Robin,

Just requested access to this doc.

I noticed you assigned Stephen to the issue. Is your thinking that he'll do
all the client-side Javascript and just turn to me for any UI that's
needed, if it turns out that a dialog or something is required? Or do you
want me to be involved in writing the client-side Angular code?

Daniel


  [image: photo]
*Daniel McQuillen*
McQuillen Interactive Pty. Ltd.
 p:+61 4 9980 2564 | e:daniel@mcquilleninteractive.com | w:
www.simplediagrams.com | a:Melbourne, Australia
 <http://facebook.com/simplediagrams>
<http://au.linkedin.com/in/mcquilleninteractive/>
<http://twitter.com/simplediagrams>
<http://plus.google.com/+Simplediagrams>
    Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=>

**Comment by RDmitchell** [comment]
Daniel -- I just made a new issue for the UI side of this, which at this point is displaying a log file. I have assigned the issue to you. However, we may not generate the log file in this first iteration of this issue, so the logging and UI display of those logs may not happen in the August or even Sept timeframe. 

Robin

**Comment by RDmitchell** [comment]
I have made an addition to the spec for this feature to make a log file and display it. However, for the first iteration of this feature, we will probably not include that logging capability.

**Comment by StephenCzarnecki** [comment]
I created a pull request (https://github.com/SEED-platform/seed/pull/327)  The travis builds seem to be failing but as best I can tell this is due to the database migration.  Should I be checking in the migration files made from manage.py makemigrations or is this something that people run locally?

**Comment by nllong** [comment]
I suggest that you upload the migration files.

**Comment by StephenCzarnecki** [comment]
Looks like that did the trick, thanks.

**Comment by StephenCzarnecki** [comment]
Comment from an email, preserving it here for posterity:

When you import a file there are 2 (well, in some cases 3) BuildingSnapshot records created.  There is a BuildingSnapshot with the raw data and one with the processed data.  It is the one with the processed data that should be marked as a duplicate and then can be removed.  The one with the raw data needs to stay around so that the "remap data" screen still works.  I think the idea is if they changed the mapping then it might not be a duplicate anymore.

**Comment by StephenCzarnecki** [comment]
"Duplicate" definition:  A BuildingSnapshot record is a duplicate if all of the fields except the following are identical:

* All fields with "_source" in the name
*id
*created
*modified
*match_type
*confidence
*source_type
*canonical_building_id
*import_file_id
*_state
*_import_file_cache
*Import_record

**Comment by StephenCzarnecki** [comment]
Pull request for the issues detected by Claudine's tests here: https://github.com/SEED-platform/seed/pull/349

**Comment by RDmitchell** [comment]
I did a quick test on our 3 years of multiple data, which should have all matched to each other but not found any duplicates, and that all worked. So seems good so far. Claudine is doing some more rigorous testing.

**Comment by RDmitchell** [comment]
I did the following test, and the program did exactly what it should have done: A total of 19 records, 1 of which had two columns in the building detail view because it was a modification, the others that were duplicates were not loaded a second time. I am closing this issue.

![image](https://cloud.githubusercontent.com/assets/6314950/9564465/60e0697c-4e5d-11e5-913c-7724f908758d.png)

**Comment by StephenCzarnecki** [comment]
To elaborate on some of the details in the pull request specifically regarding API interaction:

The call to delete the duplicates is a separate api call and is not part of the match_buildings api call.  Once match_buildings is called any duplicates are flagged as such and not used in canonical buildings but they are not removed from the database until delete_duplicates_from_import_file is explicitly called.

**Comment by cycustodio** [comment]
I need clarification for the dataset display of number of buildings. Do we want to show the total number of buildings in the file or the number of buildings that are uploaded from the file? 

In the duplicate data test, the second covered buildings has 10 duplicate and 9 new buildings. Should the column # of Buildings for ```covered-buildings-sample_allbldgs``` be 19 or 9?
![numofbuildings_duplicates](https://cloud.githubusercontent.com/assets/8461331/9593878/30083746-5009-11e5-8926-352ea6fb98ae.png)

If we look at the matching page we only see the 9 new buildings that were uploaded. 
![numofbuildings_duplicates_matching](https://cloud.githubusercontent.com/assets/8461331/9593885/49bda1da-5009-11e5-8c59-8cfb1ed23cde.png)
