### ISSUE TITLE
Superuser admin -- Add Creation Date to Organization list

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#860]
In the list of orgs at the bottom of the admin screen that you see in superuser mode, if it is possible, add the date the organization was created -- maybe another column? For the existing orgs, if there is not a way to determine that, just leave it blank or whatever. But going forward it would be nice to keep track of when orgs are created, so that if they are inactive, we will know how long they have been there and that it's ok to delete them. 

![image](https://cloud.githubusercontent.com/assets/6314950/13895767/80979bf6-ed35-11e5-9f5a-9e92c12b71b3.png)

**Comment by nicholasserra** [comment]
Orgs don't have a created date so i'll be adding a new field for this.

**Comment by nicholasserra** [comment]
For some reason the orgs app does not have migrations, so I need to fix that for us to be able to add anything.

**Comment by nicholasserra** [comment]
Unfortunately it seems there isn't a clean way I can accomplish this because of issues with migrations. There is a new flag in Django 1.9 that will allow me to implement this, assuming 1.9 is on our roadmap. This may have to be on hold until then.

https://github.com/django/django/commit/db97a8849519a3933bf4abd2184efd68ebc21965

**Comment by RDmitchell** [comment]
Ok, that's fine. We can put this off until after the June release -- I will change the Milestone. 

Thanks for investigating it.

**Comment by RDmitchell** [comment]
Tested ! Looks Great !! Thanks !
