### ISSUE TITLE
Build Migration Scripts to move data from old to new tables

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#933]

**Comment by RDmitchell** [comment]
I have some thoughts about the migration scripts. I plan to work with Stephen the week of 5/9 to 5/13 to figure at least some of this out, at the very least to figure out how hard it's going to be to do a really good migration (it might be kind of hard !).

* To be really useful, and to show the cities in the June release that we can actually do what they need the program to do with this new data model, we need to be able to migrate existing data that contains cases B and C (at least) into the new world, where the M2M table shows that relationship. I don't know how hard that is going to be, but we need to try to figure out how to do it. If we can't show that in the June release, we won't have much worthwhile to show. 

* I plan to produce a spreadsheet for Stephen (similar to a spreadsheet I made for him when he and I were putting together the Portfolio Manager file default mapping) that will have, for each of the 12 partner cities that we are supporting right now, all the fields that I know about from their raw data, and where I think they should go in the new data model (ie, into either the Lot or the Properties table). This can be used to generate a custom mapping file for each city, which I am hoping we can reuse when we get the Mapping world hooked back up again, so that we might be able to streamline the mapping process for the city, if they can just point to that file. We can figure out what we want to do about the Mapping UI when we get there. 

* In the mapping file for each city, I think we need to define the following characteristics:
 * **SEED Field name** ==> I supposed if I define is as "tablename.fieldname" we don't need the "SEED Table" property listed below
 * **SEED Display name** ==> this can be whatever the user wants it to be and will be what shows up in the UI and any exports, reports, etc.
 * **Original Data field name** ==> the name of the field in the users data that is being mapped to the SEED field name
 * **BEDES Field name** ==> this is used for the eventuality of SEED exporting data in BEDES format
 * **SEED table** ==> Lot, Property, etc 
 * **Data Type** ==> Integer, String, Date/Time, whatever

I think that summarizes what I have been thinking about so far. I'm sure other things will pop into my head

**Comment by RDmitchell** [comment]
Also, I have put together a lot of test data for the different cases (A, B, C and D) that I can perfect after talking to Stephen about what would be useful to him in order to test migrating those particular cases.

**Comment by StephenCzarnecki** [comment]
Here's a list of questions that I have after the initial work last sprint.  Some of it will likely be solved by things Robin mentioned in her previous comment.

**Cycles:**

User vs Organization:  The current Cycle model has a key to user.  In the existing model the BuildingSnapshot table just ties back to Organization.  There was some talk of making Cycle have a key into Organization instead.  If it stays tied to the user I can just make cycles for each user in each org during the import.

How can we get cycles from the existing data?  If we assume only yearly cycles I can create a new cycle whenever I find a building for a different year.

How do we decide what data goes in which cycle?  It is likely that an existing canonical snapshot represents a tree containing data from several cycles.  I think there are at least two issues here: figuring out what data to use for the "canonical" value for that cycle and figuring out the audit log for that cycle.  Since we are not dealing with the audit log quite yet I am going to focus on the issue of figuring out the "canonical" value for that cycle.  The current BuildingSnapshot has the following (non extra data) fields that might relate to either the record's cycle or place in the audit log:

- created: django field representing when the database record was first created.  Likely only applies to position in audit log (if at all).
- modified: django field representing when the database record was last modified.  Likely only applies to position in audit log (if at all).
- year_ending:
- generation_date:
- release_date:
- *_source_id fields:  These point to the source of the various values in the BuildingSnapshot.  Do we need to make sure they obey any particular rules when migrating?  For a hypothetical example if a record has a release_date of 2014 do we need to do any checking to see if any of the values come from a 2015 record?

Are there any fields in extra_data to look for to determine cycles?


**Property:**

Can we determine if something is a campus from the BuildingSnapshot data?  The only non extra data property fields I see are pm_property_id, property_notes, and property_name.  There is also the address information.  Can that be used somehow to figure out if something is part of a campus?

Same questions about the parent_property field.


**PropertyState vs TaxLotState:**

How do we determin which values go to PropertyState and which to TaxLotState? PropertyState and TaxLotState have similar (or even identical) fields:  address, city, state, postal_code, etc...  However these represent potentially different pieces of information.  For example, given a BuildingSnapshot record how do we determin whether the "city" value should go to a PropertyState record or a TaxLotState?  We can do things like figure out the initial type of file the data was imported from or look for clues in extra_data.  Do any of these fields need to be evaluated as a group?  For example if a BuildingSnapshot record has a "city" from a PM file and a "state" from a tax file is that OK?

**jurisdiction identifiers:**

These will likely vary based on the jurisdiction involved.  So we will likely need those mappings.

**TaxLotState:**

Is number_properties the same as building_count, a value to be found in extra_data, or can it be determined otherwise?

**TaxLotProperty:**

TaxLotProperty has a cycle, a property_view and a taxlot_view.  Both of the views also have their own cycle.  Do we need to do any validation to make sure these cycles end up the same?  It might (hopefully) work out based on some of the decisions above but should we do any validation?

**Comment by RDmitchell** [comment]
We need to start keeping this information in a spec doc, so I have started one.
Here is a link to that doc
https://docs.google.com/a/lbl.gov/document/d/1P9w4VGkesAMjAoNGGutIGQKTOm4Nz5hzMfghKqi89uw/edit?usp=sharing

I have put the following info in that doc, but will also put it here

**Cycles:**
* I think we need to have the cycles be at the organization level, not at the account level. Individuals do not determine the compliance cycle for an entity such as a city, the city does.

* Determining cycles from existing data -- *I am going to confirm this in the next few days, but I think the fields represent the following*
 * In Portfolio Manager files, **year_ending** is used to define the compliance cycle; so if the year_ending date is 12/31/2015, we can define a record in the cycle table with the name "2015 Compliance", start date = 1/1/2015, end date = 12/31/2015
 * **release_date** determines when the owner released it to the city; I believe this could be in a different year than the year_ending, if a city fixed a record and is resubmitting it for a previous year.
 * **generation_date** is when the city downloaded the data from Portfolio Manager. I believe this could be in a different year than the year_ending, if a city fixed a record and is resubmitting it for a previous year.

**Parent Properties**
We should be able to determine the campus situation. Again I will confirm this, but I believe if we look for records with a value in Parent Property ID, and then find any matching Parent Property IDs in other records, that is how Portfolio Manager denotes the fact that a property has been entered as a campus. I will fill in more details in the spec.

**PropertyState vs TaxLotState**
This is what I will help with in terms of the mapping. I can find out from the cities what information in their original data came from each source. If they mapped them with the same name, we can't necessarily tell the source, but in many cases, the cities are not mapping them with the same name between the Tax Lot data and the Portfolio Manager data, so we might be able to figure out most of it.

**Jurisdiction Identifiers**
These will be different for each city, and if they mapped them to Tax Lot ID, then we can use that. If they didn't map it to Tax Lot ID, the mapping file that I will generate for each city will have that relationship identified.

**TaxLotState**
Where is "number of properties" defined? If it is a new field in the Tax Lot State table, then we need to figure out what it represents, and whether building_count contains the correct data.

**Comment by RDmitchell** [comment]
My comment about getting the Cycle information from the Portfolio Manager year_ending date will only apply to the properties table. We need to ponder how to determine the Cycle information for that tax lot data. Can we determine that from the Tax Assessor / Covered Building data files that were used to import the data. In some cases, they may have that information. I can work with the cities to figure that out. There are only a few cities that will have more than one year's worth of data

**Comment by StephenCzarnecki** [comment]
I was looking at year ending dates, here is a complete list from the dump of the production database:

"1889-01-01"
"2005-03-31"
"2010-03-31"
"2010-12-31"
"2011-09-30"
"2011-11-30"
"2011-12-31"
"2012-01-31"
"2012-04-30"
"2012-05-31"
"2012-06-30"
"2012-08-31"
"2012-09-30"
"2012-10-31"
"2012-11-30"
"2012-12-31"
"2013-01-31"
"2013-02-28"
"2013-03-31"
"2013-04-30"
"2013-05-31"
"2013-06-30"
"2013-07-31"
"2013-08-31"
"2013-11-30"
"2013-12-31"
"2014-01-31"
"2014-03-31"
"2014-05-31"
"2014-06-30"
"2014-07-31"
"2014-08-31"
"2014-09-30"
"2014-12-31"
"2015-01-31"
"2015-07-10"
"2015-12-31"
"2020-12-31"


There are quite a few that are not on Dec. 31.  

I picked one at random, 2013-04-30, and all of those buildings belong to San Joaquin Valley Clean Energy Organization.  So does 2013-08-31

Picking another (2014-09-30) and that belongs to LBNL - Baptiste.  As does 
2015-07-10

Would it be worth checking the rest of the non-Dec 31 year ending dates to see if there is anything that isn't San Joaquine or Baptiste?

**Comment by StephenCzarnecki** [comment]
Looking at Kansas City I see ~37k records but none with a year_ending, release_date, or generation_date

**Comment by RDmitchell** [comment]
Yes. 

I want to clean up the database before we migrate the data -- most of the organizations in it are not relevant, mostly being test data. We really only need to migrate the data for the twelve SEED Collaborative Partner entities, which I can give to you.

**Comment by RDmitchell** [comment]
I think that is because they haven't loaded any Portfolio Manager data yet. At least in the data dump that you are probably working with.

**Comment by RDmitchell** [comment]
am closing this. Data that needed migrating from V 1.5 to 2.0 has been migrated.
