### ISSUE TITLE
Investigate Sentry errors

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#942]

**Comment by RDmitchell** [comment]
@nicholasserra -- I noticed there was a new sentry error this morning from philadelphia, having to do with projects. Maybe it is something we have already fixed, but if you could look into it that would be great. thx

**Comment by RDmitchell** [comment]
@nicholasserra -- just got this Sentry error when I was trying to filter on Year Ending, which is a date field, so you have to enter min and max values -- it's actually very funky. 

ValidationError: [u"'2010-01-01T08:00:00.000Z' value has an invalid date format. It must be in YYYY-MM-DD format."]
(15 additional frame(s) were not displayed)
...
  File "seed/utils/api.py", line 97, in _wrapped
    return fn(request, *args, **kwargs)
  File "seed/decorators.py", line 103, in wrapper
    response = func(request, *args, **kwargs)
  File "seed/views/main.py", line 648, in search_buildings
    user=request.user,
  File "seed/search.py", line 621, in orchestrate_search_filter_sort
    buildings_queryset, other_search_params, db_columns
  File "seed/search.py", line 221, in filter_other_params
    queryset = queryset.filter(query_filters)

this was with my rdmitchell+22 account.

**Comment by RDmitchell** [comment]
And now I can't even get the building list to appear -- gets an error on search buildings. sigh ...

**Comment by RDmitchell** [comment]
I just loaded sample data from issue 85 (multi year data) in order to do some testing on date filtering. I imported the data onto seed production in my +25 account, which didn't have any data in it (not sure whether it used to or not). Imported, mapped and matched the covered building list, the program reported 10 records imported, I clicked on the Buildings nav bar and got the search buildings error (same as shown above)

**Comment by nicholasserra** [comment]
Looks like the datepicker is sending the wrong values.

**Comment by nicholasserra** [comment]
Okay so just realized the datepicker is a chrome only thing. Is that what was used when the error happened? I don't think I can make a fix for that on the frontend.

**Comment by RDmitchell** [comment]
I was using Chrome, but I am puzzled that this is an issue. I am pretty sure it worked before on Chrome, although it is true that I haven't tested this in a very long time. 

I am wondering if we should abandon the current filtering UI for dates -- it is very hard to use, and doesn't seem very effective. 

Would it be possible to just do a single filter box, like all of the others, and still be able to filter on a single date or a range of dates? Something like "> 1/1/2013, < 1/1/2015" to get all records with dates in that range? It's a bit techie, but all our current users would be capable of doing this type of thing, and it would certainly be better than the weird way the program works now. Just the fact that it assumes a date range doesn't make sense. A lot of times you just want to get all the records with one date, ie, year_ending = 12/31/2014 or whatever. 

@nicholasserra -- let me know what you think the level of effort to make this change would be. I know we have a lot of other things we need to be tackling, but at least one user (and probably more as they start to get their Portfolio Manager data in the next month or so) needs the date function to work now. 

Also, this might be something that @danielmcquillen could do the front end work on if you did the backend work.

**Comment by nicholasserra** [comment]
The issue is that there isn't really frontend work to do, the native chrome datepicker is putting in an invalid format. Chrome may have changed the way this works. I'll just need to validate the format on the backend.

**Comment by RDmitchell** [comment]
OK, and in the interim, using another browser should still work?

**Comment by nicholasserra** [comment]
Just don't use the datepicker. Put in then format manually as YYYY-MM-DD

**Comment by RDmitchell** [comment]
hmmm, I guess I didn't realize I was using the "datepicker". I thought I was just typing in the date, but maybe I'm wrong. I will do a bit of testing.

**Comment by RDmitchell** [comment]
This is what I see when I look a the year_ending date in the UI
![image](https://cloud.githubusercontent.com/assets/6314950/15335901/f64fe548-1c28-11e6-9c2c-7f320832b4a1.png)

If I enter in the values 1/1/2011 for the first input and 12/31/2011 for the 2nd input
![image](https://cloud.githubusercontent.com/assets/6314950/15335964/258b5fd6-1c29-11e6-9289-23d56d20f679.png)

I still get a server error on search_buildings -- but I am not using the "date picker", at least not the calendar piece. But the input box still controls the values I input in terms of month, day and year. I can't just type in the values. 
![image](https://cloud.githubusercontent.com/assets/6314950/15336035/7000cd4e-1c29-11e6-93e9-c379a5a2b7a8.png)

So is there some other way to enter the dates that would not generate this error?

**Comment by nicholasserra** [comment]
Chrome must be forcing those values on date inputs. No worries. I'll just fix it on the backend.

**Comment by RDmitchell** [comment]
great, thx!

**Comment by RDmitchell** [comment]
I tried Mozilla Firefox on seed production, and it doesn't give an error but also doesn't do the filter correctly.

In Mozilla, there are no input controls, so you can just enter the values, but then the filter doesn't work. 

In this example, only the first record should be displayed after the Update Filter button is selected, but all the records are displayed.

![image](https://cloud.githubusercontent.com/assets/6314950/15337185/581bc96c-1c2f-11e6-9abf-1b5e5aa55e44.png)

And it generated a Sentry error when I tried it on seedtest
![image](https://cloud.githubusercontent.com/assets/6314950/15337728/de7ea36a-1c31-11e6-8960-60ce3f6c26c7.png)

![image](https://cloud.githubusercontent.com/assets/6314950/15337749/f82eeb26-1c31-11e6-9ef1-c72bea8bf31b.png)

**Comment by RDmitchell** [comment]
**Seems to be working for Chrome but not Mozilla**
Will close this issue and add another to fix the issue in Mozilla

Testing the date filtering with real data (RM + 7):

* 2 PM files, 2012, 2013
* 1291 Total records
* 1,178 records with year ending = 12/31/2013
* 113 records with year ending = 12/31/2012
* 1,178 + 113 = 1291

In Google Chrome, tested (using Enter key to initiate the filter):
 
* Entered dates by typing in numbers into each of the Month, Day, Year blocks (awkward but works)
* Selected dates from the calendar -- worked

Entered dates as follows, to filter for records that all had year ending date of 12/31/12 
* Start = 12/31/2012, End = 12/31/2012 ==> 113 records
* Start = 5/13/2012, End = 12/31/2012 ==> 113 records
* Start = 1/1/2012, End = 12/31/2012 ==> 113 records 

Seem to take a very long time to process the filters as well as clear them. 

**In Mozilla Firefox, the date filtering doesn't seem to be working** (used the Update Filter button to initiate the filter) -- I will make a new issue for this, for after the June release

* Start = 12/31/2013, End = 12/31/2013 ==> 1,291 records, so filter didn't work
* Start = 12/31/13, End = 12/31/13 ==> 1,291 records, so filter didn't work
* Start = 01/01/13, End = 12/31/13 ==> 1,291 records, so filter didn't work
* Start = 01/01/2013, End = 12/31/2013 ==> 1,291 records, so filter didn't work

I entered the date criteria in the form 12/31/13 and 12/31/2013 and in both cases the program returned the total number of records, ie 1,291, rather than 1,178

Also entered start = 01/01/213 and end = 

![image](https://cloud.githubusercontent.com/assets/6314950/15555240/af1221fa-227c-11e6-87a6-36a52d705f9d.png)
