### ISSUE TITLE
Date filtering not working in Mozilla Firefox

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#962]
In Mozilla Firefox, the date filtering doesn't seem to be working (used the Update Filter button to initiate the filter) -- see previous issue #942, which fixed this issue for Google Chrome
- Start = 12/31/2013, End = 12/31/2013 ==> 1,291 records, so filter didn't work
- Start = 12/31/13, End = 12/31/13 ==> 1,291 records, so filter didn't work
- Start = 01/01/13, End = 12/31/13 ==> 1,291 records, so filter didn't work
- Start = 01/01/2013, End = 12/31/2013 ==> 1,291 records, so filter didn't work

testing on seedtest, RM+7

**Comment by RDmitchell** [comment]
We need to make sure that the date filtering works on the following browsers -- Chrome (I believe it now does), Firefox (I don't think it does) and Explorer (I haven't tested). 

@tallus -- I am giving you this issue. It would be nice to get it into the V 1.5 release, because some users are trying to do date filtering in non-Chrome browsers.

**Comment by tallus** [comment]
Date filtering works ok if you give it the right format e.g. 2016-01-01, which is not super helpful as that's not the format we use for display.

 I've added a validator that will warn the user if they enter a date in the correct format.

@RDmitchell can you take a look at the attached screenshot and tell me what you think of the UI?
![seed platform - mozilla firefox_128](https://cloud.githubusercontent.com/assets/347498/15732639/ccd1a53c-2833-11e6-945b-bc48e3bd36a5.png)

**Comment by tallus** [comment]
Something to note: it starts to validate as soon as the user starts typing. I've set a 750ms delay on the message, but average typing speed is around 3 characters per sec, so it's still likely to appear before the user has finished typing (even if its a valid format since partial dates as considered invalid).

We could also set it to appear  after they have left the box.

**Comment by tallus** [comment]
Chrome isn't affected since it uses the HTML5 date picker. I haven't tested on IE (I'm on Linux) put this approach should be platform agnostic. I will install a virtual machine and confirm once we are happy with this approach.

**Comment by RDmitchell** [comment]
@tallus -- I think the big red bar across the page is probably too much in terms of warning the user, but if there could be a rollover on the date fields, or a smaller error message on the UI that would probably be more appropriate. Right now we don't really have error checking on the UI, so there isn't really a precedent to follow. 

@danielmcquillen -- do you want to weigh in on a nice way to show information like this in the UI, or put up a message when the user enters the date in the wrong format (browser specific).

But we could also do nothing, and just put on our Knowledge Base how the dates should be formatted. 

I tested Explorer and it has the same issue -- if you enter the dates with the YYYY-MM-DD format, the filtering works. 

So at least there isn't a bug to fix, just user education.

I am also wondering why the dates in the actual data being displayed are not shown in that format, if that's what those browsers default to in terms of date format. If the dates were displayed as YYYY-M-DD in the table, I suspect the users would automatically put the dates in the filter boxes in that same format. But then I guess the display of the dates needs to be browser specific, which seems a bit cumbersome.

**Comment by RDmitchell** [comment]
Also, relative to your comment about the validation starting to happen as soon as the user types, we probably don't want that behavior. I think it would be better to validate after they have either clicked on the Update Filters button or hit the Enter key to start the filter. 

But again, we have to decide if we want to do the validation and if we do, what the error message should look like. 

I am tempted not to do anything this round and do something a bit more thoughtful after the June release.

**Comment by tallus** [comment]
@RDMItchell 
I don't think display would need to be platform specific, Chrome users see the date picker without a box to type in, so it can be the same for everyone.

On that note we could change the starting text in those boxes to be YYY-MM-DD instead of Min or Max, but there's not enough room for that to be really visible. 

Angular has tooltips so we could add a rollover with the correct format if we want to push out a decision on validation.

**Comment by tallus** [comment]
@danielmcquillen 
You might have more insight into this.
The way I got it working is too add a subform in angular, since its outside a form* and angular validation requires one to work. A side effect of this is that the div containing the messaging is actually inside the table header with the boxes. I then reposition the spans with the error messaging using CSS. This is based off of the .status-message style with a different background color. I also made it full width, and fixed position as there were some quirks in how in was working because of where the container div is placed, 

* at least I couldn't figure out which form they are attached to, if any.

**Comment by tallus** [comment]
Quick mockup of tooltip onfocus
![tooltip](https://cloud.githubusercontent.com/assets/347498/15754816/de44d0a2-28ae-11e6-90d1-ffe02f9be599.png)

**Comment by RDmitchell** [comment]
I think because this is not a real bug, I don't want to make any changes about this for the 1.5 release, which we need to get out as soon as possible. 

So I am going to change the Milestone date on this to later in the summer, and we can pick it up again then. And @tallus, I will unassign it from you. But thanks for figuring out that the filtering actually worked if you just put the input in the right format -- that was a big help.

**Comment by RDmitchell** [comment]
This issue is no longer relevant -- the program no longer has the min / max date entries in the filter box.
