### ISSUE TITLE
Export not working when filtering on label

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#970]
Need to do more testing to make sure exactly what the problem is.

**Comment by RDmitchell** [comment]
so the export problem does not have to do with the semicolon or not -- I tried it on a small dataset and the program exports the data without problem. 

What I was working on before was the large 13k datafile, so maybe the export of 265 records just takes a very long time. I will let it sit for a while and see if it finishes.

**Comment by RDmitchell** [comment]
@tallus -- I just sent you an email to join an organization (LBNL 855) on our seedtest instance. I will make a doc that shows the steps I am going through -- maybe I am just not waiting long enough for the export to finish, even though it is only 265 records. And then if you need to import the data directly into your dev environment to really see what is going on, I will put a link in the doc to the data, how it should be imported, and mapped, etc.

**Comment by RDmitchell** [comment]
Here is a link to a video that shows the export problem. 
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LM2RaZWxrazdWWVE/view?usp=sharing

**Comment by RDmitchell** [comment]
Export had been running for several minutes at 6:07 pm. Let it run until 6:21 -- no errors on the console tab. Killed it after that.

**Comment by RDmitchell** [comment]
@tallus -- I shared a link with you for the Portfolio Manager file with 13K records in it. 
Import it as a Portfolio manager file, and accept all the default mappings. Hopefully you will get the program to save the mapping (see my latest issue #971), and then once you have saved the mapping and gone through the matching step (the file is just matching to itself, and I don't think there will be any matches), you should try the export I was doing in the video. Let me know if you have any questions.

**Comment by tallus** [comment]
CSV export works, XLS does not. This seems to happen regardless of how many records or the presence of a semi-colon. However the failure is dependent on the presence of this particular record set, I delete all the buildings and just reimport the sample data set it works fine.

I've added the traceback below, but essentially the issue seems to be that  we can't write more than 256 columns to a xls spreadsheet. This appears to be hard-coded into the package we using for writing xls and comes from a hard limit on the number of columns in older version of Excel. It doesn't appear that we impose a limit on the number of columns so there is no easy fix for this and I think the wider issue uncovered is beyond the scope of this ticket. The best solution is probably documenting the issue.

@RDmitchell comments?

This is the traceback generated:

web-celery_1   | [2016-06-02 12:46:10,842: INFO/MainProcess] Received task: seed.tasks.export_buildings[1259cbe6-7fc6-4e35-9cd4-0641702b07de]
web_1          | [pid: 53|app: 0|req: 84/113] 172.17.0.1 () {46 vars in 1002 bytes} [Thu Jun  2 12:46:10 2016] POST /app/export_buildings/ => generated 204 bytes in 174 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 0)
web-celery_1   | [2016-06-02 12:46:10,856: ERROR/MainProcess] Task seed.tasks.export_buildings[1259cbe6-7fc6-4e35-9cd4-0641702b07de] raised unexpected: ValueError('column index (256) not an int in range(256)',)
web-celery_1   | Traceback (most recent call last):
web-celery_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
web-celery_1   |     R = retval = fun(*args, **kwargs)
web-celery_1   | [2016-06-02 12:46:10,856: ERROR/MainProcess] Task seed.tasks.export_buildings[1259cbe6-7fc6-4e35-9cd4-0641702b07de] raised unexpected: ValueError('column index (256) not an int in range(256)',)
web-celery_1   | Traceback (most recent call last):
web-celery_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
web-celery_1   |     R = retval = fun(*args, **kwargs)
web-celery_1   |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
web-celery_1   |     return self.run(*args, **kwargs)
web-celery_1   |   File "/seed/seed/tasks.py", line 117, in export_buildings
web-celery_1   |     exporter.export(selected_buildings, selected_fields, _row_cb)
web-celery_1   |   File "/seed/seed/lib/exporter.py", line 166, in export
web-celery_1   |     export_method(buildings, fields, row_cb)
web-celery_1   |   File "/seed/seed/lib/exporter.py", line 269, in export_xls
web-celery_1   |     worksheet.write(0, i, header)
web-celery_1   |   File "/usr/local/lib/python2.7/dist-packages/xlwt/Worksheet.py", line 1030, in write
web-celery_1   |     self.row(r).write(c, label, style)
web-celery_1   |   File "/usr/local/lib/python2.7/dist-packages/xlwt/Row.py", line 235, in write
web-celery_1   |     self.__adjust_bound_col_idx(col)
web-celery_1   |   File "/usr/local/lib/python2.7/dist-packages/xlwt/Row.py", line 78, in __adjust_bound_col_idx
web-celery_1   |     raise ValueError("column index (%r) not an int in range(256)" % arg)
web-celery_1   | ValueError: column index (256) not an int in range(256)

**Comment by RDmitchell** [comment]
Excellent sleuthing! Thanks much. The users can control the number of fields that are being displayed and they are painfully aware of the 256 limit of Excel files, so this is a user education issue for now. 

Thanks again ! I will close this ticket.
