### ISSUE TITLE
Error mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#971]
Trying to map a PM file for Issue #970, I got the following error on mapping

This was in my LBNL 84 test account -- I deleted all the building records as a super user before importing an mapping this file. 

@mmclark -- I am giving this to you -- maybe you can look at the server logs and figure out what happened. I can also give you access to the file in question. It imported into another test org (LBNL 855) without issue. 

![image](https://cloud.githubusercontent.com/assets/6314950/15696476/767af96e-2765-11e6-8d36-ac8c5bf13d2b.png)

raven.js:757 POST https://seedtest.lbl.gov/app/progress/ 400 (Bad Request)(anonymous function) @ raven.js:757(anonymous function) @ angular.js:10765sendReq @ angular.js:10558serverRequest @ angular.js:10268processQueue @ angular.js:14792(anonymous function) @ angular.js:14808Scope.$eval @ angular.js:16052Scope.$digest @ angular.js:15870Scope.$apply @ angular.js:16160(anonymous function) @ angular.js:17927completeOutstandingRequest @ angular.js:5552(anonymous function) @ angular.js:5829c @ raven.js:329
angular.js:12520 Unhandled Error: duplicate key value violates unique constraint "data_importer_importfile_pkey"
DETAIL:  Key (id)=(2727) already exists.
(anonymous function) @ angular.js:12520(anonymous function) @ data_upload_modal_ctrl.js:286(anonymous function) @ uploader_service.js:128processQueue @ angular.js:14792(anonymous function) @ angular.js:14808Scope.$eval @ angular.js:16052Scope.$digest @ angular.js:15870Scope.$apply @ angular.js:16160done @ angular.js:10589completeRequest @ angular.js:10787requestLoaded @ angular.js:10728c @ raven.js:329
angular.js:12520 Traceback (most recent call last):
  File "/home/ubuntu/prj/seed/seed/tasks.py", line 805, in _save_raw_data
    cache_first_rows(import_file, parser)
  File "/home/ubuntu/prj/seed/seed/tasks.py", line 735, in cache_first_rows
    import_file.save()
  File "/home/ubuntu/prj/seed/seed/data_importer/models.py", line 675, in save
    super(ImportFile, self).save(_args, *_kwargs)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(_args, *_kwargs)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "data_importer_importfile_pkey"
DETAIL:  Key (id)=(2727) already exists.

**Comment by RDmitchell** [comment]
@tallus -- I am giving this issue to you. Here is a link to the file that is giving the error
https://drive.google.com/open?id=0B3fTKpZ9Dx7LaVd2c1BMWTFNdUU
Try importing it into your development environment and see if you can replicate the problem I am seeing. And if not, that too is interesting. It could be something with my account setup .

**Comment by tallus** [comment]
I can't recreate this, though that is not altogether unsurprising (its not related to the specific file). The stack trace is complaining that the primary  key for the Import file.  That field is auto-incrementing and the records gets creates by a call to create() in seed/data_importer/views.py which will never pass in a pk/id so it *should* always be unique. Postgres does some stuff on the backend to prevent race conditions and make sure it is unique so its unusual to have a collision like this. 

Moreover, it didn't throw an exception when the file was initially uploaded which creates the record, but later in the process when that ImportFile record is saved with extra fields representing the (cached) first five rows are created suggesting that it got created twice but Postgres used the same id without noticing.

**Comment by tallus** [comment]
What's happening in the DB:

The import process start with an ajax call to upload a file which passes in an import_record_id (from `data_importer_importrecord`) which represents at data set, and a file name.

The exact function called depends on whether S3 is used or not but both make a call to  ImportFile.objects.create(import_record=record, file=filename... no id is passed in and its an auto-incrementing seq/primary so it should be unique.
This happened before the exception thrown so at this stage there should have been a unique db record at this stage. The id for this get returned as `import_file_id` as is used in the various operations that happen next.

Next a call to POST /app/save_raw_data/ is made with the import_file_id and organization

This hits  save_raw_data (in views/main.py) which sets up a background task to import raw data from an ImportFile into BuildingSnapshot objects.

This parcels this out to the function of the same name in seed/tasks.py which sets up the actual celery task (with the lock_and_track decorator) which is _save_raw_data in the same file.
This does some preliminary processing before chunking out the data, 100 rows at a time,  to celery tasks in order to create the building snapshots.

Before it does the chunking it calls cache_first_rows. This stores the headers and first five rows on the ImportFile records so they can displayed to the user (before the chunking finishes, presumably).

This is when the exception thrown: ie. when is saved the model, which call an `INSERT` to update. The error bubbled up from postgres as the primary key (== import_file_id) as not unique at this stage, so it appears that a duplicate record was created at some stage. 

I don't have access to the db but it would be worth looking to see if there are duplicate ids (id=2727) and if so are the rows identical.

**Comment by RDmitchell** [comment]
closing.
