### ISSUE TITLE
Unchecked fields in Mapping screen are imported but not available in Building List Settings #972

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#973]
according to the helpful information icon on the mapping screen, if you uncheck the checkbox on the left hand side, the program will import the data but use the Data File Header name instead of a new name that you give it. 
![image](https://cloud.githubusercontent.com/assets/6314950/15727161/b082bb02-2809-11e6-8ed7-63db1d5c2ea1.png)

The program does import the field, with the Data File Header as the field name, but that field name doesn't appear in the list of fields in the List Setting option in the Building List (or the Building Info) screens.

I believe this is because the field names are not put into the Column_Mappings table. But it seems like they should be. 

The task here is to understand what is happening, ie, 

* are the checked fields being put into the column_mappings table and the unchecked field are not?
* Is the list displayed in List Settings generated from the data in column_mappings?

If these thing are both true, seems like we need to change the program to add those field names to the column_mappings table, or figure out some other way for them to get into the List Settings list.

Once we have made this change, we also need to do a data migration to get all the fields that are not being displayed into the proper table for existing users, so that they can see all the fields in their data set. 

I am setting this for the June 1.5 update -- this may be ambitious, but a few users need this functionality, so depending on the level of effort, we should try to fix it now if possible.

**Comment by RDmitchell** [comment]
@tallus -- I am assigning this to you. So you need to understand how these pieces of the software work, and then see what is involved in making the suggested change. Or proposing something else depending on what you discover. 

@StephenCzarnecki knows a bit about mapping, so if you have questions, you could ask him. thx

**Comment by RDmitchell** [comment]
@tallus -- definitely investigate this and understand the issues, but I think we will not deal with this for the 1.5 update release, since I want to get that out as soon as possible. But understanding the issue and potential solution is good and we can fix it for the next version. So I am changing the milestone.

**Comment by RDmitchell** [comment]
@tallus -- am also changing this to priority = 2 (the number "2" label) to indicate that other work for the June release or other Priority = 1 issues would take precedence over working on this.

**Comment by tallus** [comment]
> are the checked fields being put into the column_mappings table and the unchecked field are not?
yes
>Is the list displayed in List Settings generated from the data in column_mappings?
apparently so

Data from unchecked fields is stored in the extra data field but doesn't appear accessible, so the messaging is true, but not very useful. However leaving it checked and entering a custom name in the first box (or leaving as is) will cause the field to be stored in  the column_mapping so it appears in the list settings, with the corresponding data stored in  the extra_data field. This seems close to the desired behaviour. 

If we were to store the field name from unchecked boxes, on import,  however we would render the box useless: checking it would have no effect as we would always store the field name and data regardless.

For any given imported field there are 3 options for what to do with it

1. Match it to a canonical field name e.g .Tax Lot ID
2. Add a custom field name (which can just be the filed name form the data, as suggested at present)
3. Ignore it altogether

The issue arises due to the way 3 is handled : we ignore the field name but not the data. This in itself is not bad -- there are arguments for never throwing  data unnecessarily. However doing so creates an orphan record. We then compound the problem by telling the user that we store the data which makes it appears as if it should  accessible, which it never will be in a meaningful way as we have no corresponding field name. This makes 3 sound like a variant of 2.

The easiest path might be to change the messaging to make it clear that unchecking the box means it will be ignored (we can still store the data behind the scenes).

If there is a demand for getting at the orphaned data we could add a tool that would parse the extra data field and add a new column name to the appropriate table. This seems a better approach that storing it regardless Potentially we could add an unmapped columns tables and stick unmapped fields into it at import time to make this process easier (though we would still have to parse the extra data fields in order to migrate existing data).

We might want to rethink the list settings page, at the moment you get the option to add any canonical field names, regardless of whether the data exists (I guess to it can be manually added) but it makes for a very long list. A better  solution might be to split this up.
1. a list of the existing columns
2. A mechanism to add a canonical field
3. (optionally) a mechanism to add unmapped field.

3. would need to be more than just reusing the field name from the data. Users should be able to map this to a canonical or custom field name. 

What I haven't covered here is the implications of creating a new mapping e.g. how it relates to the building record tree.

**Comment by tallus** [comment]
Some more points

Its possible in the mapping stage to check the box but leave the column name (left field) blank, which has the same effect as leaving the box unchecked, this should surely throw an error. You can't do this if you blank an existing field but the software remembers previous mappings so this field is blank but you can still check the box.

If you uncheck a box that corresponds to a canonical file/db column e.g. Energy alerts the data is not stored*, in contrast to things in extra data, however the column does appear in list setting so the field will be bank  if you select it. You can effectively retrieve it by reimporting the same data source (amusingly the software reports  a 90% confidence rate that these are the same records, I haven't looked into how its determining this, but that seems a little off).

*at least in the current record that gets pointed to, we might store that data in the original import(deleting building doesn't remove them from the db so its a little hard to tell just by looking at db records.

**Comment by tallus** [comment]
I also want to flag the security implications of adding previously hidden extra data fields.

Suppose we have a scenario where some one is uploading a document that contains sensitive info that other members of their team have access to.

They uncheck the box since they don't want them to be able to see it. If that column still appears in list settings the other people who shouldn't be privvy to it might be able to gain easy access to by selecting it from the list settings (and the column name alone might leak sensitive info (imagine a field named ssn) and give some one a motive for malicious actions) .

Its possible to control access via sub organizations, and while I think that's ok for mapped columns I don't think its true for unmapped columns, since it requires positive action on the part of the user, which is not something to be relied upon given that unmapped columns don't appear. 

We could make it so that it takes action on the part of an authorised user for these to appear in list settings. However this has security implications of its own -- any time you create a roadblock of some sort you also create an incentive to undermine it, for the sake of convenience, which can leave you worse off. A uploads some data, b can't see X, asks A to make it viewable, so A adds its. Then C ask for Y and B asks for Z at which point A thinks, I'm to busy to deal with this every 5 minutes and checks all the columns and sensitive info is leaked everywhere -- bear in mind info can be shared with the public.  Murphy's law always applies here.

**Comment by tallus** [comment]
Some other notes:

I tried importing some data* and selecting just the additional data (on the grounds the other data already exists and this was new data  I wanted  to add). Two things happened from this.

1. Whenever you import new data and map it it rewrites the columns, this left me with 1 column  and all the existing information was orphaned.

2 . The data was present during mapping but appeared to be blank after matching, After re-uploading the data with other columns present (but no tax lot id) and playing around with list settings to show hidden fields  it became clear that is was present but duplicate building had been created due to a missing tax lot id. (retrying with all data except tax lot id confirmed this thought there should have been enough data to match) so it seems that if a tax lot id is present a match will never be made for a new record that is missing one, this should probably be made clearer (address_line_1 was present but insufficient).

When you reimport data it doesn't suggest column mappings (as it does the first time the system sees them) , if you had unchecked these in a previous import/mapping so this made it problematic to rematch. This is mostly out of scope for this ticket, however previously checked columns are available in list settings if they are hidden by the last mapping and this makes it more difficult to match them (it should suggest pre-existing mappings and if these don't exist the same suggestion as if it as new column).

**Comment by tallus** [comment]
# Summary:

### The existing system.
The present system is inconsistent. Whether we store unchecked data and column names depends on whether that column maps to a column in the building snapshot field or not. If it does we don't store the data or column name for unchecked fields. If it doesn't we store the column/data as a key value pair for everything that doesn't match an existing column, regardless of whether its checked.  (this includes fields that map to a db column but aren't mapped to it). This makes adding previously unchecked fields problematic since we won't consistently have data for it in the current building record, Sometimes reselecting the column in list setting is sufficient to show it, it it was checked, then unchecked,  but seemingly not always (I will need to start with a clean db to figure out when/how this happens since deleting building doesn't remove the record from the db). 

Previously checked columns (from extra data) do appear in list settings, though they might be hidden in the current view if unchecked or not present in new uploads.

Its possible to add this data back in by re-uploading the original data source but you have to be careful to make sure your building matches. This is made harder because the suggested field is left blank if it had been previously checked, then unchecked at a later date.

### Moving Forward:
First we should determine the correct approach to storing data so it can be consistently applied going forward and communicated to users.

Either unchecked columns should never be stored, or they should always be stored. 

If the former we should clean the json blob before storing it and make it clear that unchecked won't be stored.

If the later we need to carefully think through the implications and make it clear to users they will need to clean data before uploading it if it contains sensitive information or other things they do not wish stored.  

If we chose the latter we can add appropriate fields to the database to act as a flag to indicate active and inactive columns.  This should NOT be used to indicate whether a column is displayed. It can be used  indicate whether it appears in list settings. This MUST be tied to an organisation ID so that it can be set differently for sub-organisations. 

We also need to determine scope: does checking a column during mapping affect all data under this column or just the data being uploaded. If the latter and it was previously checked what is the outcome? Does it hide the column from list settings? If it only applies to the data imported it suggests that this data should not be shown regardless of whether a column is selected and data appears elsewhere. If this is the case what would be the mechanism for making that data visible and/or hiding other data, and how would this be grouped (by filter or my upload file?). If checking or unchecking it affects all data we need to make sure users are aware of the implications of this.

Additionally if a column is unchecked we need to consider how it will be stored. What happens if it matches a field in the database e.g. postal_code. It it occurs under a different name e.g. zip code how to store the mapping? How is it stored if there was a previous mapping? Is it safe to always reuse this subsequently? If we don't reuse it how do we handle it if it is subsequently checked?

These notes only apply to data added going forward. It would be possible to apply it to (some) existing data, it might not always be possible or could otherwise be unreliable. It might also be an expensive process depending on how thorough we are. We should consider this vis a vis users re-importing and matching data (and what the effects on the records are) to add columns back in.

**Comment by RDmitchell** [comment]
solution is to not allow unmapped fields, ie, remove the checkbox from the mapping screen. This is already in PT https://www.pivotaltracker.com/story/show/131635165. Closing it here
