### ISSUE TITLE
Building Detail Column width control doesn't work properly in IE

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#982]
The new feature added for V 1.5 that allows the user to control the width of the column in the Building Detail (Information) view doesn't work properly in IE. It does work as expected in Chrome. It hasn't been tested in Mozilla. I will make a video that shows the behavior in IE.

**Comment by RDmitchell** [comment]
Here is a link to the video showing the behavior. 
https://drive.google.com/open?id=0B3fTKpZ9Dx7LYzNocjhUX2lxSFk

**Comment by RDmitchell** [comment]
This is a perfect candidate for a Selenium test, ie, once this is fixed, write a Selenium test that tests it in all the major browsers (Mozilla Firefox, Chrome, IE), and then get that Selenium test into our CI framework.

**Comment by RDmitchell** [comment]
I did the video recording / test in 11.0.0600.18349
![image](https://cloud.githubusercontent.com/assets/6314950/16099974/19891d38-3310-11e6-8051-827ac202af5b.png)

**Comment by RDmitchell** [comment]
Which appears to be the latest version at this moment.

**Comment by tallus** [comment]
Do you have some more details on how it was behaving. I can't reproduce this in IE11. I will test on older version tomorrow.

**Comment by RDmitchell** [comment]
The behavior you see in the video is using IE 11. 

You might want to see if you can reproduce it on our seedtest server, rather than just your dev environment. I can give you and account there (if you don't already have one) tomorrow. In my example I just loaded the sample data (covered building and portfolio manager).

**Comment by tallus** [comment]
On June 15, 2016 6:32:52 PM PDT, RDmitchell <notifications@github.com> wrote:
>The behavior you see in the video is using IE 11. 
>
>You might want to see if you can reproduce it on our seedtest server,
>rather than just your dev environment. I can give you and account there
>(if you don't already have one)

That would be handy.  I have a different number of columns on my dev box and it might get triggered if no of columns > 2

 tomorrow. In my example I just loaded
>the sample data (covered building and portfolio manager).
>
>---
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/SEED-platform/seed/issues/982#issuecomment-226366113

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RDmitchell** [comment]
Paul -- I just made you a member of the organization where I have been testing on seedtest. See if you can reproduce what I was seeing with IE11 in that org.

**Comment by tallus** [comment]
This is restricted to Chrome. The same things happens in Firefox (47.0/Ubuntu 14.04). It does not happen on my dev box, it does happen on seed test. The immediate difference I see is in Angular versions: v1.4.10 on my dev box, v1.4.8 on Seed test. There also appears to be a difference in bootstrap versions (as part of Angular)

However the the resizing component lives in jquery and both versions are the same.  This works my setting   style="position: relative; width: Npx;" on the table header. Inspecting it with Firebug you can see the value changed in both, however it is not applied on seed test. In fact though firebug show the width set, when you click on the element it immediately changes to 60px (the actual width) and then goes to the new value, but this is not applied. Looking at the computed values the @element.style width is not set in the seed test version.  This makes me suspect that it is not propagating to the DOM correctly. Angular uses jquery for DOM handling,  either an existing version if it finds one or its own jqlite if it does not.

**Comment by rebrownlbnl** [comment]
Assuming you're running current Develop branch on your dev box?
I'm wondering why the Angular version is different there than on seedtest -- the two versions shouldn't be that different, unless we incremented Angular for the blue sky development?

**Comment by RDmitchell** [comment]
when you say "restricted to Chrome" -- Chrome is the browser that the feature works with. It does not work with IE, for example.

**Comment by tallus** [comment]
> when you say "restricted to Chrome" -- Chrome is the browser that the feature works with. It does > not work with IE, for example. 

that's corrected, I meant to say not restricted to IE


Angular: version
It's 1.4.8. vs 1.4.10
bower.json says 
dependencies": {
    "angular": "~1.4.7",
  "resolutions": {
    "angular": "1.4.7"

~1.4.7 will be satisfied by >= 1.4.7 <1.5.0

**Comment by tallus** [comment]
So we set 
table th.ellipsis {
    max-width: 80px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

in style.css
It was added here: https://github.com/SEED-platform/seed/commit/9c18be24efd044b5cc102980095bb5014d81166a

Removing the max-width by editing it in firebug on seed test makes everything work ok, so it looks like setting the max-wdith is causing the issue, which makes sense.

This doesn't get applied on my dev box, it does on seedtest.  On my dev box it's there in the scss but not the css file, which explains the difference, why this should be the case I'm not sure.

**Comment by tallus** [comment]
". On my dev box it's there in the scss but not the css file, which explains the difference, why this should be the case I'm not sure."

Its not there the committed css file on the develop branch.

**Comment by tallus** [comment]
Note the td below does have the same ellipsis class set.
The purpose of the ellipsis class is to add an ellipsis for overflow text. 
max-width appears to be needed here as with out it the computed width is set to that of any containing elements, presumably because whitespace: nowrap is inherited form ellipsis so they won't line break, so the width will always include enough room for the text to display.

What's happening here is that 80px max-width on the td becomes the effective  minimum  width for the th element

Without the th ellipsis class set the minimum width is either 80px or the width of the containing text., which ever is greater. This is consistent across all browsers.

With it IE and Firefox apply the max-width immediately the element is resized. Chrome doesn't. It sort of ignores it, but doesn't restrict the width to that of the containing element, it applies the rest of the class and 80px effectively becomes a minimum width.

Chrome's behavoiur produces better results here, but I'm not sure its really "correct" vis a vis the others (since its ignores the max-width).

In either case the behaviour without  the ellipsis class on the th seems better but does prevent the column being resized correctly since it can't be shrunk below the width of the contained text.

**Comment by tallus** [comment]
![selection_131](https://cloud.githubusercontent.com/assets/347498/16159471/ce1d2e7a-3477-11e6-98e9-91fa260fa78f.png)
Screen shot showing layout with css fix on seedtest:
max-width on th removed, min-width:80px, 170px on first column to prevent labels overflowing. table-layout: fixed (this is waht makes in work).

Note how header and cell contents have ellipsis.

**Comment by tallus** [comment]
Pull request is now in, but note that Selenium testing is kinda broken now due to issues with webdrivers + selenium (nothing to do with our code). I put some workarounds in place.

There is no selenium test for IE as IE is not available across all Platforms so won't work on peoples dev boxes unless they are running Windows. Travis doesn't use a browser for Selenium testing.
It might be possible to set it up to control them on another server but that's for another day/ticket.

**Comment by RDmitchell** [comment]
Do you have any suggestions about how to test the application across the major browsers? It seems that we need to do it, and we need to automate it.

**Comment by tallus** [comment]
We can do this with SauceLabs, I've just cut another branch off of this one to better handle multiple browsers. It looks like its mostly a matter of providing different desired_capabilities to the tests.
I also want to eliminate duplicate/cunt-n--paste tests.

**Comment by RDmitchell** [comment]
Tested in IE -- column resizing works well
Tested in Chrome -- column resizing works well
Tested in Mozilla -- column resizing works well
